/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { ListenV1ResponseMetadata } from '../models/listenV1ResponseMetadata.js';
import { ListenV1ResponseResults } from '../models/listenV1ResponseResults.js';

/**
 * Creates an instance of ListenV1Response
 */
interface ListenV1Response {
  metadata: ListenV1ResponseMetadata;
  results: ListenV1ResponseResults;
  additionalProperties?: Record<string, unknown>;
}

export class ListenV1ResponseError extends ApiError<ListenV1Response> {}
