/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  isMappedValueValidForSchema,
  lazy,
  oneOf,
  Schema,
} from '../../schema.js';
import {
  AgentThinkModelsV1ResponseModelsItems0,
  agentThinkModelsV1ResponseModelsItems0Schema,
} from '../agentThinkModelsV1ResponseModelsItems0.js';
import {
  AgentThinkModelsV1ResponseModelsItems1,
  agentThinkModelsV1ResponseModelsItems1Schema,
} from '../agentThinkModelsV1ResponseModelsItems1.js';
import {
  AgentThinkModelsV1ResponseModelsItems2,
  agentThinkModelsV1ResponseModelsItems2Schema,
} from '../agentThinkModelsV1ResponseModelsItems2.js';
import {
  AgentThinkModelsV1ResponseModelsItems3,
  agentThinkModelsV1ResponseModelsItems3Schema,
} from '../agentThinkModelsV1ResponseModelsItems3.js';
import {
  AgentThinkModelsV1ResponseModelsItems4,
  agentThinkModelsV1ResponseModelsItems4Schema,
} from '../agentThinkModelsV1ResponseModelsItems4.js';

/** This is a container type for one-of types. */
export type AgentThinkModelsV1ResponseModelsItems =
  | AgentThinkModelsV1ResponseModelsItems0
  | AgentThinkModelsV1ResponseModelsItems1
  | AgentThinkModelsV1ResponseModelsItems2
  | AgentThinkModelsV1ResponseModelsItems3
  | AgentThinkModelsV1ResponseModelsItems4;

export const agentThinkModelsV1ResponseModelsItemsSchema: Schema<AgentThinkModelsV1ResponseModelsItems> = lazy(
  () =>
    oneOf([
      agentThinkModelsV1ResponseModelsItems0Schema,
      agentThinkModelsV1ResponseModelsItems1Schema,
      agentThinkModelsV1ResponseModelsItems2Schema,
      agentThinkModelsV1ResponseModelsItems3Schema,
      agentThinkModelsV1ResponseModelsItems4Schema,
    ])
);

export namespace AgentThinkModelsV1ResponseModelsItems {
  /**
   * Validation method to narrow down union type to AgentThinkModelsV1ResponseModelsItems0 type case.
   *
   * This is AgentThinkModelsV1ResponseModelsItems0 case.
   */
  export function isAgentThinkModelsV1ResponseModelsItems0(
    value: unknown
  ): value is AgentThinkModelsV1ResponseModelsItems0 {
    return isMappedValueValidForSchema(
      value,
      agentThinkModelsV1ResponseModelsItems0Schema
    );
  }

  /**
   * Validation method to narrow down union type to AgentThinkModelsV1ResponseModelsItems1 type case.
   *
   * This is AgentThinkModelsV1ResponseModelsItems1 case.
   */
  export function isAgentThinkModelsV1ResponseModelsItems1(
    value: unknown
  ): value is AgentThinkModelsV1ResponseModelsItems1 {
    return isMappedValueValidForSchema(
      value,
      agentThinkModelsV1ResponseModelsItems1Schema
    );
  }

  /**
   * Validation method to narrow down union type to AgentThinkModelsV1ResponseModelsItems2 type case.
   *
   * This is AgentThinkModelsV1ResponseModelsItems2 case.
   */
  export function isAgentThinkModelsV1ResponseModelsItems2(
    value: unknown
  ): value is AgentThinkModelsV1ResponseModelsItems2 {
    return isMappedValueValidForSchema(
      value,
      agentThinkModelsV1ResponseModelsItems2Schema
    );
  }

  /**
   * Validation method to narrow down union type to AgentThinkModelsV1ResponseModelsItems3 type case.
   *
   * This is AgentThinkModelsV1ResponseModelsItems3 case.
   */
  export function isAgentThinkModelsV1ResponseModelsItems3(
    value: unknown
  ): value is AgentThinkModelsV1ResponseModelsItems3 {
    return isMappedValueValidForSchema(
      value,
      agentThinkModelsV1ResponseModelsItems3Schema
    );
  }

  /**
   * Validation method to narrow down union type to AgentThinkModelsV1ResponseModelsItems4 type case.
   *
   * This is AgentThinkModelsV1ResponseModelsItems4 case.
   */
  export function isAgentThinkModelsV1ResponseModelsItems4(
    value: unknown
  ): value is AgentThinkModelsV1ResponseModelsItems4 {
    return isMappedValueValidForSchema(
      value,
      agentThinkModelsV1ResponseModelsItems4Schema
    );
  }
}
