/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { oneOf, Schema, unknown } from '../../schema.js';

/** This is a container type for one-of types. */
export type CreateKeyV1Request = unknown;

export const createKeyV1RequestSchema: Schema<CreateKeyV1Request> = oneOf([
  unknown(),
]);

export namespace CreateKeyV1Request {
}
