/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { isMappedValueValidForSchema, oneOf, Schema } from '../../schema.js';
import {
  V2SpeakPostParametersSampleRate0,
  v2SpeakPostParametersSampleRate0Schema,
} from '../v2SpeakPostParametersSampleRate0.js';
import {
  V2SpeakPostParametersSampleRate1,
  v2SpeakPostParametersSampleRate1Schema,
} from '../v2SpeakPostParametersSampleRate1.js';
import {
  V2SpeakPostParametersSampleRate2,
  v2SpeakPostParametersSampleRate2Schema,
} from '../v2SpeakPostParametersSampleRate2.js';
import {
  V2SpeakPostParametersSampleRate3,
  v2SpeakPostParametersSampleRate3Schema,
} from '../v2SpeakPostParametersSampleRate3.js';

/** This is a container type for one-of types. */
export type GenerateSampleRate2 =
  | V2SpeakPostParametersSampleRate0
  | V2SpeakPostParametersSampleRate1
  | V2SpeakPostParametersSampleRate2
  | V2SpeakPostParametersSampleRate3;

export const generateSampleRate2Schema: Schema<GenerateSampleRate2> = oneOf([
  v2SpeakPostParametersSampleRate0Schema,
  v2SpeakPostParametersSampleRate1Schema,
  v2SpeakPostParametersSampleRate2Schema,
  v2SpeakPostParametersSampleRate3Schema,
]);

export namespace GenerateSampleRate2 {
  /**
   * Validation method to narrow down union type to V2SpeakPostParametersSampleRate0 type case.
   *
   * This is V2SpeakPostParametersSampleRate0 case.
   */
  export function isV2SpeakPostParametersSampleRate0(
    value: unknown
  ): value is V2SpeakPostParametersSampleRate0 {
    return isMappedValueValidForSchema(
      value,
      v2SpeakPostParametersSampleRate0Schema
    );
  }

  /**
   * Validation method to narrow down union type to V2SpeakPostParametersSampleRate1 type case.
   *
   * This is V2SpeakPostParametersSampleRate1 case.
   */
  export function isV2SpeakPostParametersSampleRate1(
    value: unknown
  ): value is V2SpeakPostParametersSampleRate1 {
    return isMappedValueValidForSchema(
      value,
      v2SpeakPostParametersSampleRate1Schema
    );
  }

  /**
   * Validation method to narrow down union type to V2SpeakPostParametersSampleRate2 type case.
   *
   * This is V2SpeakPostParametersSampleRate2 case.
   */
  export function isV2SpeakPostParametersSampleRate2(
    value: unknown
  ): value is V2SpeakPostParametersSampleRate2 {
    return isMappedValueValidForSchema(
      value,
      v2SpeakPostParametersSampleRate2Schema
    );
  }

  /**
   * Validation method to narrow down union type to V2SpeakPostParametersSampleRate3 type case.
   *
   * This is V2SpeakPostParametersSampleRate3 case.
   */
  export function isV2SpeakPostParametersSampleRate3(
    value: unknown
  ): value is V2SpeakPostParametersSampleRate3 {
    return isMappedValueValidForSchema(
      value,
      v2SpeakPostParametersSampleRate3Schema
    );
  }
}
