/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { isMappedValueValidForSchema, oneOf, Schema } from '../../schema.js';
import {
  V1SpeakPostParametersContainer0,
  v1SpeakPostParametersContainer0Schema,
} from '../v1SpeakPostParametersContainer0.js';
import {
  V1SpeakPostParametersContainer1,
  v1SpeakPostParametersContainer1Schema,
} from '../v1SpeakPostParametersContainer1.js';
import {
  V1SpeakPostParametersContainer2,
  v1SpeakPostParametersContainer2Schema,
} from '../v1SpeakPostParametersContainer2.js';
import {
  V1SpeakPostParametersContainer3,
  v1SpeakPostParametersContainer3Schema,
} from '../v1SpeakPostParametersContainer3.js';
import {
  V1SpeakPostParametersContainer4,
  v1SpeakPostParametersContainer4Schema,
} from '../v1SpeakPostParametersContainer4.js';

/** This is a container type for one-of types. */
export type GenerateContainer =
  | V1SpeakPostParametersContainer0
  | V1SpeakPostParametersContainer1
  | V1SpeakPostParametersContainer2
  | V1SpeakPostParametersContainer3
  | V1SpeakPostParametersContainer4;

export const generateContainerSchema: Schema<GenerateContainer> = oneOf([
  v1SpeakPostParametersContainer0Schema,
  v1SpeakPostParametersContainer1Schema,
  v1SpeakPostParametersContainer2Schema,
  v1SpeakPostParametersContainer3Schema,
  v1SpeakPostParametersContainer4Schema,
]);

export namespace GenerateContainer {
  /**
   * Validation method to narrow down union type to V1SpeakPostParametersContainer0 type case.
   *
   * This is V1SpeakPostParametersContainer0 case.
   */
  export function isV1SpeakPostParametersContainer0(
    value: unknown
  ): value is V1SpeakPostParametersContainer0 {
    return isMappedValueValidForSchema(
      value,
      v1SpeakPostParametersContainer0Schema
    );
  }

  /**
   * Validation method to narrow down union type to V1SpeakPostParametersContainer1 type case.
   *
   * This is V1SpeakPostParametersContainer1 case.
   */
  export function isV1SpeakPostParametersContainer1(
    value: unknown
  ): value is V1SpeakPostParametersContainer1 {
    return isMappedValueValidForSchema(
      value,
      v1SpeakPostParametersContainer1Schema
    );
  }

  /**
   * Validation method to narrow down union type to V1SpeakPostParametersContainer2 type case.
   *
   * This is V1SpeakPostParametersContainer2 case.
   */
  export function isV1SpeakPostParametersContainer2(
    value: unknown
  ): value is V1SpeakPostParametersContainer2 {
    return isMappedValueValidForSchema(
      value,
      v1SpeakPostParametersContainer2Schema
    );
  }

  /**
   * Validation method to narrow down union type to V1SpeakPostParametersContainer3 type case.
   *
   * This is V1SpeakPostParametersContainer3 case.
   */
  export function isV1SpeakPostParametersContainer3(
    value: unknown
  ): value is V1SpeakPostParametersContainer3 {
    return isMappedValueValidForSchema(
      value,
      v1SpeakPostParametersContainer3Schema
    );
  }

  /**
   * Validation method to narrow down union type to V1SpeakPostParametersContainer4 type case.
   *
   * This is V1SpeakPostParametersContainer4 case.
   */
  export function isV1SpeakPostParametersContainer4(
    value: unknown
  ): value is V1SpeakPostParametersContainer4 {
    return isMappedValueValidForSchema(
      value,
      v1SpeakPostParametersContainer4Schema
    );
  }
}
