/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { isMappedValueValidForSchema, oneOf, Schema } from '../../schema.js';
import {
  V1SpeakPostParametersSampleRate0,
  v1SpeakPostParametersSampleRate0Schema,
} from '../v1SpeakPostParametersSampleRate0.js';
import {
  V1SpeakPostParametersSampleRate1,
  v1SpeakPostParametersSampleRate1Schema,
} from '../v1SpeakPostParametersSampleRate1.js';
import {
  V1SpeakPostParametersSampleRate2,
  v1SpeakPostParametersSampleRate2Schema,
} from '../v1SpeakPostParametersSampleRate2.js';
import {
  V1SpeakPostParametersSampleRate3,
  v1SpeakPostParametersSampleRate3Schema,
} from '../v1SpeakPostParametersSampleRate3.js';
import {
  V1SpeakPostParametersSampleRate4,
  v1SpeakPostParametersSampleRate4Schema,
} from '../v1SpeakPostParametersSampleRate4.js';

/** This is a container type for one-of types. */
export type GenerateSampleRate =
  | V1SpeakPostParametersSampleRate0
  | V1SpeakPostParametersSampleRate1
  | V1SpeakPostParametersSampleRate2
  | V1SpeakPostParametersSampleRate3
  | V1SpeakPostParametersSampleRate4;

export const generateSampleRateSchema: Schema<GenerateSampleRate> = oneOf([
  v1SpeakPostParametersSampleRate0Schema,
  v1SpeakPostParametersSampleRate1Schema,
  v1SpeakPostParametersSampleRate2Schema,
  v1SpeakPostParametersSampleRate3Schema,
  v1SpeakPostParametersSampleRate4Schema,
]);

export namespace GenerateSampleRate {
  /**
   * Validation method to narrow down union type to V1SpeakPostParametersSampleRate0 type case.
   *
   * This is V1SpeakPostParametersSampleRate0 case.
   */
  export function isV1SpeakPostParametersSampleRate0(
    value: unknown
  ): value is V1SpeakPostParametersSampleRate0 {
    return isMappedValueValidForSchema(
      value,
      v1SpeakPostParametersSampleRate0Schema
    );
  }

  /**
   * Validation method to narrow down union type to V1SpeakPostParametersSampleRate1 type case.
   *
   * This is V1SpeakPostParametersSampleRate1 case.
   */
  export function isV1SpeakPostParametersSampleRate1(
    value: unknown
  ): value is V1SpeakPostParametersSampleRate1 {
    return isMappedValueValidForSchema(
      value,
      v1SpeakPostParametersSampleRate1Schema
    );
  }

  /**
   * Validation method to narrow down union type to V1SpeakPostParametersSampleRate2 type case.
   *
   * This is V1SpeakPostParametersSampleRate2 case.
   */
  export function isV1SpeakPostParametersSampleRate2(
    value: unknown
  ): value is V1SpeakPostParametersSampleRate2 {
    return isMappedValueValidForSchema(
      value,
      v1SpeakPostParametersSampleRate2Schema
    );
  }

  /**
   * Validation method to narrow down union type to V1SpeakPostParametersSampleRate3 type case.
   *
   * This is V1SpeakPostParametersSampleRate3 case.
   */
  export function isV1SpeakPostParametersSampleRate3(
    value: unknown
  ): value is V1SpeakPostParametersSampleRate3 {
    return isMappedValueValidForSchema(
      value,
      v1SpeakPostParametersSampleRate3Schema
    );
  }

  /**
   * Validation method to narrow down union type to V1SpeakPostParametersSampleRate4 type case.
   *
   * This is V1SpeakPostParametersSampleRate4 case.
   */
  export function isV1SpeakPostParametersSampleRate4(
    value: unknown
  ): value is V1SpeakPostParametersSampleRate4 {
    return isMappedValueValidForSchema(
      value,
      v1SpeakPostParametersSampleRate4Schema
    );
  }
}
