/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  isMappedValueValidForSchema,
  number,
  oneOf,
  Schema,
} from '../../schema.js';
import {
  V2SpeakPostParametersBitRate0,
  v2SpeakPostParametersBitRate0Schema,
} from '../v2SpeakPostParametersBitRate0.js';

/** This is a container type for one-of types. */
export type GenerateBitRate2 = V2SpeakPostParametersBitRate0 | number;

export const generateBitRate2Schema: Schema<GenerateBitRate2> = oneOf([
  v2SpeakPostParametersBitRate0Schema,
  number(),
]);

export namespace GenerateBitRate2 {
  /**
   * Validation method to narrow down union type to V2SpeakPostParametersBitRate0 type case.
   *
   * This is V2SpeakPostParametersBitRate0 case.
   */
  export function isV2SpeakPostParametersBitRate0(
    value: unknown
  ): value is V2SpeakPostParametersBitRate0 {
    return isMappedValueValidForSchema(
      value,
      v2SpeakPostParametersBitRate0Schema
    );
  }

  /**
   * Validation method to narrow down union type to number type case.
   *
   * This is Number case.
   */
  export function isNumber(value: unknown): value is number {
    return typeof value === 'number';
  }
}
