/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { isMappedValueValidForSchema, oneOf, Schema } from '../../schema.js';
import {
  V2SpeakPostParametersEncoding0,
  v2SpeakPostParametersEncoding0Schema,
} from '../v2SpeakPostParametersEncoding0.js';
import {
  V2SpeakPostParametersEncoding1,
  v2SpeakPostParametersEncoding1Schema,
} from '../v2SpeakPostParametersEncoding1.js';
import {
  V2SpeakPostParametersEncoding2,
  v2SpeakPostParametersEncoding2Schema,
} from '../v2SpeakPostParametersEncoding2.js';
import {
  V2SpeakPostParametersEncoding3,
  v2SpeakPostParametersEncoding3Schema,
} from '../v2SpeakPostParametersEncoding3.js';
import {
  V2SpeakPostParametersEncoding4,
  v2SpeakPostParametersEncoding4Schema,
} from '../v2SpeakPostParametersEncoding4.js';
import {
  V2SpeakPostParametersEncoding5,
  v2SpeakPostParametersEncoding5Schema,
} from '../v2SpeakPostParametersEncoding5.js';
import {
  V2SpeakPostParametersEncoding6,
  v2SpeakPostParametersEncoding6Schema,
} from '../v2SpeakPostParametersEncoding6.js';

/** This is a container type for one-of types. */
export type GenerateEncoding2 =
  | V2SpeakPostParametersEncoding0
  | V2SpeakPostParametersEncoding1
  | V2SpeakPostParametersEncoding2
  | V2SpeakPostParametersEncoding3
  | V2SpeakPostParametersEncoding4
  | V2SpeakPostParametersEncoding5
  | V2SpeakPostParametersEncoding6;

export const generateEncoding2Schema: Schema<GenerateEncoding2> = oneOf([
  v2SpeakPostParametersEncoding0Schema,
  v2SpeakPostParametersEncoding1Schema,
  v2SpeakPostParametersEncoding2Schema,
  v2SpeakPostParametersEncoding3Schema,
  v2SpeakPostParametersEncoding4Schema,
  v2SpeakPostParametersEncoding5Schema,
  v2SpeakPostParametersEncoding6Schema,
]);

export namespace GenerateEncoding2 {
  /**
   * Validation method to narrow down union type to V2SpeakPostParametersEncoding0 type case.
   *
   * This is V2SpeakPostParametersEncoding0 case.
   */
  export function isV2SpeakPostParametersEncoding0(
    value: unknown
  ): value is V2SpeakPostParametersEncoding0 {
    return isMappedValueValidForSchema(
      value,
      v2SpeakPostParametersEncoding0Schema
    );
  }

  /**
   * Validation method to narrow down union type to V2SpeakPostParametersEncoding1 type case.
   *
   * This is V2SpeakPostParametersEncoding1 case.
   */
  export function isV2SpeakPostParametersEncoding1(
    value: unknown
  ): value is V2SpeakPostParametersEncoding1 {
    return isMappedValueValidForSchema(
      value,
      v2SpeakPostParametersEncoding1Schema
    );
  }

  /**
   * Validation method to narrow down union type to V2SpeakPostParametersEncoding2 type case.
   *
   * This is V2SpeakPostParametersEncoding2 case.
   */
  export function isV2SpeakPostParametersEncoding2(
    value: unknown
  ): value is V2SpeakPostParametersEncoding2 {
    return isMappedValueValidForSchema(
      value,
      v2SpeakPostParametersEncoding2Schema
    );
  }

  /**
   * Validation method to narrow down union type to V2SpeakPostParametersEncoding3 type case.
   *
   * This is V2SpeakPostParametersEncoding3 case.
   */
  export function isV2SpeakPostParametersEncoding3(
    value: unknown
  ): value is V2SpeakPostParametersEncoding3 {
    return isMappedValueValidForSchema(
      value,
      v2SpeakPostParametersEncoding3Schema
    );
  }

  /**
   * Validation method to narrow down union type to V2SpeakPostParametersEncoding4 type case.
   *
   * This is V2SpeakPostParametersEncoding4 case.
   */
  export function isV2SpeakPostParametersEncoding4(
    value: unknown
  ): value is V2SpeakPostParametersEncoding4 {
    return isMappedValueValidForSchema(
      value,
      v2SpeakPostParametersEncoding4Schema
    );
  }

  /**
   * Validation method to narrow down union type to V2SpeakPostParametersEncoding5 type case.
   *
   * This is V2SpeakPostParametersEncoding5 case.
   */
  export function isV2SpeakPostParametersEncoding5(
    value: unknown
  ): value is V2SpeakPostParametersEncoding5 {
    return isMappedValueValidForSchema(
      value,
      v2SpeakPostParametersEncoding5Schema
    );
  }

  /**
   * Validation method to narrow down union type to V2SpeakPostParametersEncoding6 type case.
   *
   * This is V2SpeakPostParametersEncoding6 case.
   */
  export function isV2SpeakPostParametersEncoding6(
    value: unknown
  ): value is V2SpeakPostParametersEncoding6 {
    return isMappedValueValidForSchema(
      value,
      v2SpeakPostParametersEncoding6Schema
    );
  }
}
