/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  isMappedValueValidForSchema,
  number,
  oneOf,
  Schema,
} from '../../schema.js';
import {
  V1SpeakPostParametersBitRate0,
  v1SpeakPostParametersBitRate0Schema,
} from '../v1SpeakPostParametersBitRate0.js';

/** This is a container type for one-of types. */
export type GenerateBitRate = V1SpeakPostParametersBitRate0 | number;

export const generateBitRateSchema: Schema<GenerateBitRate> = oneOf([
  v1SpeakPostParametersBitRate0Schema,
  number(),
]);

export namespace GenerateBitRate {
  /**
   * Validation method to narrow down union type to V1SpeakPostParametersBitRate0 type case.
   *
   * This is V1SpeakPostParametersBitRate0 case.
   */
  export function isV1SpeakPostParametersBitRate0(
    value: unknown
  ): value is V1SpeakPostParametersBitRate0 {
    return isMappedValueValidForSchema(
      value,
      v1SpeakPostParametersBitRate0Schema
    );
  }

  /**
   * Validation method to narrow down union type to number type case.
   *
   * This is Precision case.
   */
  export function isNumber(value: unknown): value is number {
    return typeof value === 'number';
  }
}
