/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { isMappedValueValidForSchema, oneOf, Schema } from '../../schema.js';
import {
  V2SpeakPostParametersContainer0,
  v2SpeakPostParametersContainer0Schema,
} from '../v2SpeakPostParametersContainer0.js';
import {
  V2SpeakPostParametersContainer1,
  v2SpeakPostParametersContainer1Schema,
} from '../v2SpeakPostParametersContainer1.js';
import {
  V2SpeakPostParametersContainer2,
  v2SpeakPostParametersContainer2Schema,
} from '../v2SpeakPostParametersContainer2.js';
import {
  V2SpeakPostParametersContainer3,
  v2SpeakPostParametersContainer3Schema,
} from '../v2SpeakPostParametersContainer3.js';
import {
  V2SpeakPostParametersContainer4,
  v2SpeakPostParametersContainer4Schema,
} from '../v2SpeakPostParametersContainer4.js';

/** This is a container type for one-of types. */
export type GenerateContainer2 =
  | V2SpeakPostParametersContainer0
  | V2SpeakPostParametersContainer1
  | V2SpeakPostParametersContainer2
  | V2SpeakPostParametersContainer3
  | V2SpeakPostParametersContainer4;

export const generateContainer2Schema: Schema<GenerateContainer2> = oneOf([
  v2SpeakPostParametersContainer0Schema,
  v2SpeakPostParametersContainer1Schema,
  v2SpeakPostParametersContainer2Schema,
  v2SpeakPostParametersContainer3Schema,
  v2SpeakPostParametersContainer4Schema,
]);

export namespace GenerateContainer2 {
  /**
   * Validation method to narrow down union type to V2SpeakPostParametersContainer0 type case.
   *
   * This is V2SpeakPostParametersContainer0 case.
   */
  export function isV2SpeakPostParametersContainer0(
    value: unknown
  ): value is V2SpeakPostParametersContainer0 {
    return isMappedValueValidForSchema(
      value,
      v2SpeakPostParametersContainer0Schema
    );
  }

  /**
   * Validation method to narrow down union type to V2SpeakPostParametersContainer1 type case.
   *
   * This is V2SpeakPostParametersContainer1 case.
   */
  export function isV2SpeakPostParametersContainer1(
    value: unknown
  ): value is V2SpeakPostParametersContainer1 {
    return isMappedValueValidForSchema(
      value,
      v2SpeakPostParametersContainer1Schema
    );
  }

  /**
   * Validation method to narrow down union type to V2SpeakPostParametersContainer2 type case.
   *
   * This is V2SpeakPostParametersContainer2 case.
   */
  export function isV2SpeakPostParametersContainer2(
    value: unknown
  ): value is V2SpeakPostParametersContainer2 {
    return isMappedValueValidForSchema(
      value,
      v2SpeakPostParametersContainer2Schema
    );
  }

  /**
   * Validation method to narrow down union type to V2SpeakPostParametersContainer3 type case.
   *
   * This is V2SpeakPostParametersContainer3 case.
   */
  export function isV2SpeakPostParametersContainer3(
    value: unknown
  ): value is V2SpeakPostParametersContainer3 {
    return isMappedValueValidForSchema(
      value,
      v2SpeakPostParametersContainer3Schema
    );
  }

  /**
   * Validation method to narrow down union type to V2SpeakPostParametersContainer4 type case.
   *
   * This is V2SpeakPostParametersContainer4 case.
   */
  export function isV2SpeakPostParametersContainer4(
    value: unknown
  ): value is V2SpeakPostParametersContainer4 {
    return isMappedValueValidForSchema(
      value,
      v2SpeakPostParametersContainer4Schema
    );
  }
}
