/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { isMappedValueValidForSchema, oneOf, Schema } from '../../schema.js';
import {
  V1SpeakPostParametersEncoding0,
  v1SpeakPostParametersEncoding0Schema,
} from '../v1SpeakPostParametersEncoding0.js';
import {
  V1SpeakPostParametersEncoding1,
  v1SpeakPostParametersEncoding1Schema,
} from '../v1SpeakPostParametersEncoding1.js';
import {
  V1SpeakPostParametersEncoding2,
  v1SpeakPostParametersEncoding2Schema,
} from '../v1SpeakPostParametersEncoding2.js';
import {
  V1SpeakPostParametersEncoding3,
  v1SpeakPostParametersEncoding3Schema,
} from '../v1SpeakPostParametersEncoding3.js';
import {
  V1SpeakPostParametersEncoding4,
  v1SpeakPostParametersEncoding4Schema,
} from '../v1SpeakPostParametersEncoding4.js';
import {
  V1SpeakPostParametersEncoding5,
  v1SpeakPostParametersEncoding5Schema,
} from '../v1SpeakPostParametersEncoding5.js';
import {
  V1SpeakPostParametersEncoding6,
  v1SpeakPostParametersEncoding6Schema,
} from '../v1SpeakPostParametersEncoding6.js';

/** This is a container type for one-of types. */
export type GenerateEncoding =
  | V1SpeakPostParametersEncoding0
  | V1SpeakPostParametersEncoding1
  | V1SpeakPostParametersEncoding2
  | V1SpeakPostParametersEncoding3
  | V1SpeakPostParametersEncoding4
  | V1SpeakPostParametersEncoding5
  | V1SpeakPostParametersEncoding6;

export const generateEncodingSchema: Schema<GenerateEncoding> = oneOf([
  v1SpeakPostParametersEncoding0Schema,
  v1SpeakPostParametersEncoding1Schema,
  v1SpeakPostParametersEncoding2Schema,
  v1SpeakPostParametersEncoding3Schema,
  v1SpeakPostParametersEncoding4Schema,
  v1SpeakPostParametersEncoding5Schema,
  v1SpeakPostParametersEncoding6Schema,
]);

export namespace GenerateEncoding {
  /**
   * Validation method to narrow down union type to V1SpeakPostParametersEncoding0 type case.
   *
   * This is V1SpeakPostParametersEncoding0 case.
   */
  export function isV1SpeakPostParametersEncoding0(
    value: unknown
  ): value is V1SpeakPostParametersEncoding0 {
    return isMappedValueValidForSchema(
      value,
      v1SpeakPostParametersEncoding0Schema
    );
  }

  /**
   * Validation method to narrow down union type to V1SpeakPostParametersEncoding1 type case.
   *
   * This is V1SpeakPostParametersEncoding1 case.
   */
  export function isV1SpeakPostParametersEncoding1(
    value: unknown
  ): value is V1SpeakPostParametersEncoding1 {
    return isMappedValueValidForSchema(
      value,
      v1SpeakPostParametersEncoding1Schema
    );
  }

  /**
   * Validation method to narrow down union type to V1SpeakPostParametersEncoding2 type case.
   *
   * This is V1SpeakPostParametersEncoding2 case.
   */
  export function isV1SpeakPostParametersEncoding2(
    value: unknown
  ): value is V1SpeakPostParametersEncoding2 {
    return isMappedValueValidForSchema(
      value,
      v1SpeakPostParametersEncoding2Schema
    );
  }

  /**
   * Validation method to narrow down union type to V1SpeakPostParametersEncoding3 type case.
   *
   * This is V1SpeakPostParametersEncoding3 case.
   */
  export function isV1SpeakPostParametersEncoding3(
    value: unknown
  ): value is V1SpeakPostParametersEncoding3 {
    return isMappedValueValidForSchema(
      value,
      v1SpeakPostParametersEncoding3Schema
    );
  }

  /**
   * Validation method to narrow down union type to V1SpeakPostParametersEncoding4 type case.
   *
   * This is V1SpeakPostParametersEncoding4 case.
   */
  export function isV1SpeakPostParametersEncoding4(
    value: unknown
  ): value is V1SpeakPostParametersEncoding4 {
    return isMappedValueValidForSchema(
      value,
      v1SpeakPostParametersEncoding4Schema
    );
  }

  /**
   * Validation method to narrow down union type to V1SpeakPostParametersEncoding5 type case.
   *
   * This is V1SpeakPostParametersEncoding5 case.
   */
  export function isV1SpeakPostParametersEncoding5(
    value: unknown
  ): value is V1SpeakPostParametersEncoding5 {
    return isMappedValueValidForSchema(
      value,
      v1SpeakPostParametersEncoding5Schema
    );
  }

  /**
   * Validation method to narrow down union type to V1SpeakPostParametersEncoding6 type case.
   *
   * This is V1SpeakPostParametersEncoding6 case.
   */
  export function isV1SpeakPostParametersEncoding6(
    value: unknown
  ): value is V1SpeakPostParametersEncoding6 {
    return isMappedValueValidForSchema(
      value,
      v1SpeakPostParametersEncoding6Schema
    );
  }
}
