/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  isMappedValueValidForSchema,
  lazy,
  oneOf,
  Schema,
} from '../../schema.js';
import {
  GetModelV1Response0,
  getModelV1Response0Schema,
} from '../getModelV1Response0.js';
import {
  GetModelV1Response1,
  getModelV1Response1Schema,
} from '../getModelV1Response1.js';

/** This is a container type for one-of types. */
export type GetModelV1Response = GetModelV1Response0 | GetModelV1Response1;

export const getModelV1ResponseSchema: Schema<GetModelV1Response> = lazy(() =>
  oneOf([getModelV1Response0Schema, getModelV1Response1Schema])
);

export namespace GetModelV1Response {
  /**
   * Validation method to narrow down union type to GetModelV1Response0 type case.
   *
   * This is GetModelV1Response0 case.
   */
  export function isGetModelV1Response0(
    value: unknown
  ): value is GetModelV1Response0 {
    return isMappedValueValidForSchema(value, getModelV1Response0Schema);
  }

  /**
   * Validation method to narrow down union type to GetModelV1Response1 type case.
   *
   * This is GetModelV1Response1 case.
   */
  export function isGetModelV1Response1(
    value: unknown
  ): value is GetModelV1Response1 {
    return isMappedValueValidForSchema(value, getModelV1Response1Schema);
  }
}
