/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  isMappedValueValidForSchema,
  lazy,
  oneOf,
  Schema,
} from '../../schema.js';
import {
  ListenV1AcceptedResponse,
  listenV1AcceptedResponseSchema,
} from '../listenV1AcceptedResponse.js';
import {
  ListenV1Response,
  listenV1ResponseSchema,
} from '../listenV1Response.js';

/** This is a container type for one-of types. */
export type ListenV1MediaTranscribeResponse200 =
  | ListenV1Response
  | ListenV1AcceptedResponse;

export const listenV1MediaTranscribeResponse200Schema: Schema<ListenV1MediaTranscribeResponse200> = lazy(
  () => oneOf([listenV1ResponseSchema, listenV1AcceptedResponseSchema])
);

export namespace ListenV1MediaTranscribeResponse200 {
  /**
   * Validation method to narrow down union type to ListenV1Response type case.
   *
   * This is ListenV1Response case.
   */
  export function isListenV1Response(
    value: unknown
  ): value is ListenV1Response {
    return isMappedValueValidForSchema(value, listenV1ResponseSchema);
  }

  /**
   * Validation method to narrow down union type to ListenV1AcceptedResponse type case.
   *
   * This is ListenV1AcceptedResponse case.
   */
  export function isListenV1AcceptedResponse(
    value: unknown
  ): value is ListenV1AcceptedResponse {
    return isMappedValueValidForSchema(value, listenV1AcceptedResponseSchema);
  }
}
