/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  isMappedValueValidForSchema,
  lazy,
  oneOf,
  Schema,
} from '../../schema.js';
import {
  ReadV1RequestText,
  readV1RequestTextSchema,
} from '../readV1RequestText.js';
import {
  ReadV1RequestUrl,
  readV1RequestUrlSchema,
} from '../readV1RequestUrl.js';

/** This is a container type for one-of types. */
export type ReadV1Request = ReadV1RequestUrl | ReadV1RequestText;

export const readV1RequestSchema: Schema<ReadV1Request> = lazy(() =>
  oneOf([readV1RequestUrlSchema, readV1RequestTextSchema])
);

export namespace ReadV1Request {
  /**
   * Validation method to narrow down union type to ReadV1RequestUrl type case.
   *
   * This is ReadV1RequestUrl case.
   */
  export function isReadV1RequestUrl(
    value: unknown
  ): value is ReadV1RequestUrl {
    return isMappedValueValidForSchema(value, readV1RequestUrlSchema);
  }

  /**
   * Validation method to narrow down union type to ReadV1RequestText type case.
   *
   * This is ReadV1RequestText case.
   */
  export function isReadV1RequestText(
    value: unknown
  ): value is ReadV1RequestText {
    return isMappedValueValidForSchema(value, readV1RequestTextSchema);
  }
}
