/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  isMappedValueValidForSchema,
  oneOf,
  Schema,
  string,
} from '../../schema.js';
import {
  V1ListenPostParametersModel0,
  v1ListenPostParametersModel0Schema,
} from '../v1ListenPostParametersModel0.js';

/** This is a container type for one-of types. */
export type TranscribeModel = V1ListenPostParametersModel0 | string;

export const transcribeModelSchema: Schema<TranscribeModel> = oneOf([
  v1ListenPostParametersModel0Schema,
  string(),
]);

export namespace TranscribeModel {
  /**
   * Validation method to narrow down union type to V1ListenPostParametersModel0 type case.
   *
   * This is V1ListenPostParametersModel0 case.
   */
  export function isV1ListenPostParametersModel0(
    value: unknown
  ): value is V1ListenPostParametersModel0 {
    return isMappedValueValidForSchema(
      value,
      v1ListenPostParametersModel0Schema
    );
  }

  /**
   * Validation method to narrow down union type to string type case.
   *
   * This is String case.
   */
  export function isString(value: unknown): value is string {
    return typeof value === 'string';
  }
}
