/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  isMappedValueValidForSchema,
  oneOf,
  Schema,
  string,
} from '../../schema.js';
import {
  V1ListenPostParametersVersion0,
  v1ListenPostParametersVersion0Schema,
} from '../v1ListenPostParametersVersion0.js';

/** This is a container type for one-of types. */
export type TranscribeVersion = V1ListenPostParametersVersion0 | string;

export const transcribeVersionSchema: Schema<TranscribeVersion> = oneOf([
  v1ListenPostParametersVersion0Schema,
  string(),
]);

export namespace TranscribeVersion {
  /**
   * Validation method to narrow down union type to V1ListenPostParametersVersion0 type case.
   *
   * This is V1ListenPostParametersVersion0 case.
   */
  export function isV1ListenPostParametersVersion0(
    value: unknown
  ): value is V1ListenPostParametersVersion0 {
    return isMappedValueValidForSchema(
      value,
      v1ListenPostParametersVersion0Schema
    );
  }

  /**
   * Validation method to narrow down union type to string type case.
   *
   * This is String case.
   */
  export function isString(value: unknown): value is string {
    return typeof value === 'string';
  }
}
