/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  isMappedValueValidForSchema,
  oneOf,
  Schema,
  string,
} from '../../schema.js';
import {
  V1ListenPostParametersRedactSchemaOneOf1Items,
  v1ListenPostParametersRedactSchemaOneOf1ItemsSchema,
} from '../v1ListenPostParametersRedactSchemaOneOf1Items.js';

/** This is a container type for one-of types. */
export type TranscribeRedact =
  | string
  | V1ListenPostParametersRedactSchemaOneOf1Items[];

export const transcribeRedactSchema: Schema<TranscribeRedact> = oneOf([
  string(),
  array(v1ListenPostParametersRedactSchemaOneOf1ItemsSchema),
]);

export namespace TranscribeRedact {
  /**
   * Validation method to narrow down union type to string type case.
   *
   * This is String case.
   */
  export function isString(value: unknown): value is string {
    return typeof value === 'string';
  }

  /**
   * Validation method to narrow down union type to V1ListenPostParametersRedactSchemaOneOf1Items[] type case.
   *
   * This is Array of V1ListenPostParametersRedactSchemaOneOf1Items case.
   */
  export function isArrayOfV1ListenPostParametersRedactSchemaOneOf1Items(
    value: unknown
  ): value is V1ListenPostParametersRedactSchemaOneOf1Items[] {
    if (!Array.isArray(value)) {
      return false;
    }
    return isMappedValueValidForSchema(
      value,
      array(v1ListenPostParametersRedactSchemaOneOf1ItemsSchema)
    );
  }
}
