/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, oneOf, Schema, string } from '../../schema.js';

/** This is a container type for one-of types. */
export type V1ListenPostParametersCustomTopic = string | string[];

export const v1ListenPostParametersCustomTopicSchema: Schema<V1ListenPostParametersCustomTopic> = oneOf(
  [string(), array(string())]
);

export namespace V1ListenPostParametersCustomTopic {
  /**
   * Validation method to narrow down union type to string type case.
   *
   * This is String case.
   */
  export function isString(value: unknown): value is string {
    return typeof value === 'string';
  }

  /**
   * Validation method to narrow down union type to string[] type case.
   *
   * This is Array of String case.
   */
  export function isArrayOfString(value: unknown): value is string[] {
    return (
      Array.isArray(value) && value.every((item) => typeof item === 'string')
    );
  }
}
