/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  isMappedValueValidForSchema,
  oneOf,
  Schema,
} from '../../schema.js';
import {
  V1ListenPostParametersSummarize0,
  v1ListenPostParametersSummarize0Schema,
} from '../v1ListenPostParametersSummarize0.js';

/** This is a container type for one-of types. */
export type V1ListenPostParametersSummarize =
  | V1ListenPostParametersSummarize0
  | boolean;

export const v1ListenPostParametersSummarizeSchema: Schema<V1ListenPostParametersSummarize> = oneOf(
  [v1ListenPostParametersSummarize0Schema, boolean()]
);

export namespace V1ListenPostParametersSummarize {
  /**
   * Validation method to narrow down union type to V1ListenPostParametersSummarize0 type case.
   *
   * This is V1ListenPostParametersSummarize0 case.
   */
  export function isV1ListenPostParametersSummarize0(
    value: unknown
  ): value is V1ListenPostParametersSummarize0 {
    return isMappedValueValidForSchema(
      value,
      v1ListenPostParametersSummarize0Schema
    );
  }

  /**
   * Validation method to narrow down union type to boolean type case.
   *
   * This is Boolean case.
   */
  export function isBoolean(value: unknown): value is boolean {
    return typeof value === 'boolean';
  }
}
