/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, boolean, oneOf, Schema, string } from '../../schema.js';

/** This is a container type for one-of types. */
export type V1ListenPostParametersDetectLanguage = boolean | string[];

export const v1ListenPostParametersDetectLanguageSchema: Schema<V1ListenPostParametersDetectLanguage> = oneOf(
  [boolean(), array(string())]
);

export namespace V1ListenPostParametersDetectLanguage {
  /**
   * Validation method to narrow down union type to boolean type case.
   *
   * This is Boolean case.
   */
  export function isBoolean(value: unknown): value is boolean {
    return typeof value === 'boolean';
  }

  /**
   * Validation method to narrow down union type to string[] type case.
   *
   * This is Array of String case.
   */
  export function isArrayOfString(value: unknown): value is string[] {
    return (
      Array.isArray(value) && value.every((item) => typeof item === 'string')
    );
  }
}
