/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  isMappedValueValidForSchema,
  oneOf,
  Schema,
} from '../../schema.js';
import {
  V1ReadPostParametersSummarize0,
  v1ReadPostParametersSummarize0Schema,
} from '../v1ReadPostParametersSummarize0.js';

/** This is a container type for one-of types. */
export type V1ReadPostParametersSummarize =
  | V1ReadPostParametersSummarize0
  | boolean;

export const v1ReadPostParametersSummarizeSchema: Schema<V1ReadPostParametersSummarize> = oneOf(
  [v1ReadPostParametersSummarize0Schema, boolean()]
);

export namespace V1ReadPostParametersSummarize {
  /**
   * Validation method to narrow down union type to V1ReadPostParametersSummarize0 type case.
   *
   * This is V1ReadPostParametersSummarize0 case.
   */
  export function isV1ReadPostParametersSummarize0(
    value: unknown
  ): value is V1ReadPostParametersSummarize0 {
    return isMappedValueValidForSchema(
      value,
      v1ReadPostParametersSummarize0Schema
    );
  }

  /**
   * Validation method to narrow down union type to boolean type case.
   *
   * This is Boolean case.
   */
  export function isBoolean(value: unknown): value is boolean {
    return typeof value === 'boolean';
  }
}
