/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  AgentThinkModelsV1Response,
  agentThinkModelsV1ResponseSchema,
} from '../models/agentThinkModelsV1Response.js';
import { BaseApi } from './baseApi.js';
import { ApiError } from '@apimatic/core';

export class AgentV1SettingsThinkModelsApi extends BaseApi {
  /**
   * Retrieves the available think models that can be used for AI agent processing
   *
   * @return Response from the API call
   */
  async list(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<AgentThinkModelsV1Response>> {
    const req = this.createRequest('GET', '/v1/agent/settings/think/models');
    req.throwOn(400, ApiError, 'Invalid Request');
    req.authenticate([{ apiKeyAuth: true }]);
    return req.callAsJson(agentThinkModelsV1ResponseSchema, requestOptions);
  }
}
