/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  GrantV1Request,
  grantV1RequestSchema,
} from '../models/grantV1Request.js';
import {
  GrantV1Response,
  grantV1ResponseSchema,
} from '../models/grantV1Response.js';
import { optional } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { ApiError } from '@apimatic/core';

export class AuthV1TokensApi extends BaseApi {
  /**
   * Generates a temporary JSON Web Token (JWT) with a 30-second (by default) TTL and usage::write
   * permission for core voice APIs, requiring an API key with Member or higher authorization. Tokens
   * created with this endpoint will not work with the Manage APIs.
   *
   * @param body         Time to live settings
   * @return Response from the API call
   */
  async grant(
    body?: GrantV1Request,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<GrantV1Response>> {
    const req = this.createRequest('POST', '/v1/auth/grant');
    const mapped = req.prepareArgs({
      body: [body, optional(grantV1RequestSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, ApiError, 'Invalid Request');
    req.authenticate([{ apiKeyAuth: true }]);
    return req.callAsJson(grantV1ResponseSchema, requestOptions);
  }
}
