/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  ListenV1MediaTranscribeResponse200,
  listenV1MediaTranscribeResponse200Schema,
} from '../models/containers/listenV1MediaTranscribeResponse200.js';
import {
  TranscribeModel,
  transcribeModelSchema,
} from '../models/containers/transcribeModel.js';
import {
  TranscribeRedact,
  transcribeRedactSchema,
} from '../models/containers/transcribeRedact.js';
import {
  TranscribeVersion,
  transcribeVersionSchema,
} from '../models/containers/transcribeVersion.js';
import {
  V1ListenPostParametersCustomIntent,
  v1ListenPostParametersCustomIntentSchema,
} from '../models/containers/v1ListenPostParametersCustomIntent.js';
import {
  V1ListenPostParametersCustomTopic,
  v1ListenPostParametersCustomTopicSchema,
} from '../models/containers/v1ListenPostParametersCustomTopic.js';
import {
  V1ListenPostParametersDetectLanguage,
  v1ListenPostParametersDetectLanguageSchema,
} from '../models/containers/v1ListenPostParametersDetectLanguage.js';
import {
  V1ListenPostParametersExtra,
  v1ListenPostParametersExtraSchema,
} from '../models/containers/v1ListenPostParametersExtra.js';
import {
  V1ListenPostParametersKeywords,
  v1ListenPostParametersKeywordsSchema,
} from '../models/containers/v1ListenPostParametersKeywords.js';
import {
  V1ListenPostParametersReplace,
  v1ListenPostParametersReplaceSchema,
} from '../models/containers/v1ListenPostParametersReplace.js';
import {
  V1ListenPostParametersSearch,
  v1ListenPostParametersSearchSchema,
} from '../models/containers/v1ListenPostParametersSearch.js';
import {
  V1ListenPostParametersSummarize,
  v1ListenPostParametersSummarizeSchema,
} from '../models/containers/v1ListenPostParametersSummarize.js';
import {
  V1ListenPostParametersTag,
  v1ListenPostParametersTagSchema,
} from '../models/containers/v1ListenPostParametersTag.js';
import {
  ListenV1RequestUrl,
  listenV1RequestUrlSchema,
} from '../models/listenV1RequestUrl.js';
import {
  V1ListenPostParametersCallbackMethod,
  v1ListenPostParametersCallbackMethodSchema,
} from '../models/v1ListenPostParametersCallbackMethod.js';
import {
  V1ListenPostParametersCustomTopicMode,
  v1ListenPostParametersCustomTopicModeSchema,
} from '../models/v1ListenPostParametersCustomTopicMode.js';
import {
  V1ListenPostParametersDiarizeModel,
  v1ListenPostParametersDiarizeModelSchema,
} from '../models/v1ListenPostParametersDiarizeModel.js';
import {
  V1ListenPostParametersEncoding,
  v1ListenPostParametersEncodingSchema,
} from '../models/v1ListenPostParametersEncoding.js';
import { array, boolean, number, optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { ListenV1ResponseError } from '../errors/listenV1ResponseError.js';

export class ListenV1MediaApi extends BaseApi {
  /**
   * Transcribe audio and video using Deepgram's speech-to-text REST API
   *
   * @param authorization      Use `Authorization: Token <API_KEY>` Example:
   *                                                                    `Authorization: Token 12345abcdef`
   * @param callback           URL to which we'll make the callback request
   * @param callbackMethod     HTTP method by which the callback request will
   *                                                                    be made
   * @param extra              Arbitrary key-value pairs that are attached to
   *                                                                    the API response for usage in downstream
   *                                                                    processing
   * @param sentiment          Recognizes the sentiment throughout a
   *                                                                    transcript or text
   * @param summarize          Summarize content. For Listen API, supports
   *                                                                    string version option. For Read API, accepts
   *                                                                    boolean only.
   * @param tag                Label your requests for the purpose of
   *                                                                    identification during usage reporting
   * @param topics             Detect topics throughout a transcript or text
   * @param customTopic        Custom topics you want the model to detect
   *                                                                    within your input audio or text if present
   *                                                                    Submit up to `100`.
   * @param customTopicMode    Sets how the model will interpret strings
   *                                                                    submitted to the `custom_topic` param. When
   *                                                                    `strict`, the model will only return topics
   *                                                                    submitted using the `custom_topic` param. When
   *                                                                    `extended`, the model will return its own
   *                                                                    detected topics in addition to those submitted
   *                                                                    using the `custom_topic` param
   * @param intents            Recognizes speaker intent throughout a
   *                                                                    transcript or text
   * @param customIntent       Custom intents you want the model to detect
   *                                                                    within your input audio if present
   * @param customIntentMode   Sets how the model will interpret intents
   *                                                                    submitted to the `custom_intent` param. When
   *                                                                    `strict`, the model will only return intents
   *                                                                    submitted using the `custom_intent` param. When
   *                                                                    `extended`, the model will return its own
   *                                                                    detected intents in the `custom_intent` param.
   * @param detectEntities     Identifies and extracts key entities from
   *                                                                    content in submitted audio
   * @param detectLanguage     Identifies the dominant language spoken in
   *                                                                    submitted audio
   * @param diarize            Deprecated: use `diarize_model` instead.
   *                                                                    Recognize speaker changes. Each word in the
   *                                                                    transcript will be assigned a speaker number
   *                                                                    starting at 0.
   * @param diarizeModel       Select and enable a specific diarization model
   *                                                                    version. Specifying this parameter enables
   *                                                                    diarization and selects the model — you do not
   *                                                                    need to also set the deprecated `diarize=true`
   *                                                                    parameter. For batch, supported values are
   *                                                                    `latest` (currently v2), `v1`, and `v2`. For
   *                                                                    streaming, supported values are `latest`
   *                                                                    (currently v1) and `v1`; `v2` returns a
   *                                                                    validation error on streaming requests.
   * @param dictation          Dictation mode for controlling formatting with
   *                                                                    dictated speech
   * @param encoding           Specify the expected encoding of your
   *                                                                    submitted audio
   * @param fillerWords        Filler Words can help transcribe interruptions
   *                                                                    in your audio, like "uh" and "um"
   * @param keyterm            Key term prompting improves recognition of
   *                                                                    specialized terminology and brands. Only
   *                                                                    compatible with Nova-3.  `keyterm` accepts
   *                                                                    plain terms only. Unlike the legacy `keywords`
   *                                                                    feature, it does not support weights or
   *                                                                    intensifiers. Appending one (for example,
   *                                                                    `keyterm=term:0.15`) is not rejected—the weight
   *                                                                    is silently ignored and the entire value is
   *                                                                    treated as a literal keyterm.  To boost
   *                                                                    multiple separate keyterms, repeat the
   *                                                                    `keyterm` parameter (for example,
   *                                                                    `keyterm=term1&keyterm=term2`). To boost one
   *                                                                    multi-word phrase as a single keyterm, join the
   *                                                                    words with `%20` or `+` (for example,
   *                                                                    `keyterm=customer%20service`). Do not separate
   *                                                                    keyterms with commas, semicolons, or line
   *                                                                    breaks.
   * @param keywords           Keywords can boost or suppress specialized
   *                                                                    terminology and brands
   * @param language           The [BCP-47 language tag](https://tools.ietf.
   *                                                                    org/html/bcp47) that hints at the primary
   *                                                                    spoken language. Depending on the Model and API
   *                                                                    endpoint you choose only certain languages are
   *                                                                    available
   * @param measurements       Spoken measurements will be converted to their
   *                                                                    corresponding abbreviations
   * @param model              AI model used to process submitted audio
   * @param multichannel       Transcribe each audio channel independently
   * @param numerals           Numerals converts numbers from written format
   *                                                                    to numerical format
   * @param paragraphs         Splits audio into paragraphs to improve
   *                                                                    transcript readability
   * @param profanityFilter    Profanity Filter looks for recognized
   *                                                                    profanity and converts it to the nearest
   *                                                                    recognized non-profane word or removes it from
   *                                                                    the transcript completely
   * @param punctuate          Add punctuation and capitalization to the
   *                                                                    transcript
   * @param redact             Redaction removes sensitive information from
   *                                                                    your transcripts
   * @param replace            Search for terms or phrases in submitted audio
   *                                                                    and replaces them
   * @param search             Search for terms or phrases in submitted
   *                                                                    audio
   * @param smartFormat        Apply formatting to transcript output. When
   *                                                                    set to true, additional formatting will be
   *                                                                    applied to transcripts to improve readability
   * @param utterances         Segments speech into meaningful semantic
   *                                                                    units
   * @param uttSplit           Seconds to wait before detecting a pause
   *                                                                    between words in submitted audio
   * @param version            Version of an AI model to use
   * @param mipOptOut          Opts out requests from the Deepgram Model
   *                                                                    Improvement Program. Refer to our Docs for
   *                                                                    pricing impacts before setting this to true.
   *                                                                    https://dpgr.am/deepgram-mip
   * @param body               Transcribe an audio or video file
   * @return Response from the API call
   */
  async transcribe(
    authorization: string,
    callback?: string,
    callbackMethod?: V1ListenPostParametersCallbackMethod,
    extra?: V1ListenPostParametersExtra,
    sentiment?: boolean,
    summarize?: V1ListenPostParametersSummarize,
    tag?: V1ListenPostParametersTag,
    topics?: boolean,
    customTopic?: V1ListenPostParametersCustomTopic,
    customTopicMode?: V1ListenPostParametersCustomTopicMode,
    intents?: boolean,
    customIntent?: V1ListenPostParametersCustomIntent,
    customIntentMode?: V1ListenPostParametersCustomTopicMode,
    detectEntities?: boolean,
    detectLanguage?: V1ListenPostParametersDetectLanguage,
    diarize?: boolean,
    diarizeModel?: V1ListenPostParametersDiarizeModel,
    dictation?: boolean,
    encoding?: V1ListenPostParametersEncoding,
    fillerWords?: boolean,
    keyterm?: string[],
    keywords?: V1ListenPostParametersKeywords,
    language?: string,
    measurements?: boolean,
    model?: TranscribeModel,
    multichannel?: boolean,
    numerals?: boolean,
    paragraphs?: boolean,
    profanityFilter?: boolean,
    punctuate?: boolean,
    redact?: TranscribeRedact,
    replace?: V1ListenPostParametersReplace,
    search?: V1ListenPostParametersSearch,
    smartFormat?: boolean,
    utterances?: boolean,
    uttSplit?: number,
    version?: TranscribeVersion,
    mipOptOut?: boolean,
    body?: ListenV1RequestUrl,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ListenV1MediaTranscribeResponse200>> {
    const req = this.createRequest('POST', '/v1/listen');
    const mapped = req.prepareArgs({
      authorization: [authorization, string()],
      callback: [callback, optional(string())],
      callbackMethod: [
        callbackMethod,
        optional(v1ListenPostParametersCallbackMethodSchema),
      ],
      extra: [extra, optional(v1ListenPostParametersExtraSchema)],
      sentiment: [sentiment, optional(boolean())],
      summarize: [summarize, optional(v1ListenPostParametersSummarizeSchema)],
      tag: [tag, optional(v1ListenPostParametersTagSchema)],
      topics: [topics, optional(boolean())],
      customTopic: [
        customTopic,
        optional(v1ListenPostParametersCustomTopicSchema),
      ],
      customTopicMode: [
        customTopicMode,
        optional(v1ListenPostParametersCustomTopicModeSchema),
      ],
      intents: [intents, optional(boolean())],
      customIntent: [
        customIntent,
        optional(v1ListenPostParametersCustomIntentSchema),
      ],
      customIntentMode: [
        customIntentMode,
        optional(v1ListenPostParametersCustomTopicModeSchema),
      ],
      detectEntities: [detectEntities, optional(boolean())],
      detectLanguage: [
        detectLanguage,
        optional(v1ListenPostParametersDetectLanguageSchema),
      ],
      diarize: [diarize, optional(boolean())],
      diarizeModel: [
        diarizeModel,
        optional(v1ListenPostParametersDiarizeModelSchema),
      ],
      dictation: [dictation, optional(boolean())],
      encoding: [encoding, optional(v1ListenPostParametersEncodingSchema)],
      fillerWords: [fillerWords, optional(boolean())],
      keyterm: [keyterm, optional(array(string()))],
      keywords: [keywords, optional(v1ListenPostParametersKeywordsSchema)],
      language: [language, optional(string())],
      measurements: [measurements, optional(boolean())],
      model: [model, optional(transcribeModelSchema)],
      multichannel: [multichannel, optional(boolean())],
      numerals: [numerals, optional(boolean())],
      paragraphs: [paragraphs, optional(boolean())],
      profanityFilter: [profanityFilter, optional(boolean())],
      punctuate: [punctuate, optional(boolean())],
      redact: [redact, optional(transcribeRedactSchema)],
      replace: [replace, optional(v1ListenPostParametersReplaceSchema)],
      search: [search, optional(v1ListenPostParametersSearchSchema)],
      smartFormat: [smartFormat, optional(boolean())],
      utterances: [utterances, optional(boolean())],
      uttSplit: [uttSplit, optional(number())],
      version: [version, optional(transcribeVersionSchema)],
      mipOptOut: [mipOptOut, optional(boolean())],
      body: [body, optional(listenV1RequestUrlSchema)],
    });
    req.header('Authorization', mapped.authorization);
    req.header('Content-Type', 'application/json');
    req.query('callback', mapped.callback);
    req.query('callback_method', mapped.callbackMethod);
    req.query('extra', mapped.extra);
    req.query('sentiment', mapped.sentiment);
    req.query('summarize', mapped.summarize);
    req.query('tag', mapped.tag);
    req.query('topics', mapped.topics);
    req.query('custom_topic', mapped.customTopic);
    req.query('custom_topic_mode', mapped.customTopicMode);
    req.query('intents', mapped.intents);
    req.query('custom_intent', mapped.customIntent);
    req.query('custom_intent_mode', mapped.customIntentMode);
    req.query('detect_entities', mapped.detectEntities);
    req.query('detect_language', mapped.detectLanguage);
    req.query('diarize', mapped.diarize);
    req.query('diarize_model', mapped.diarizeModel);
    req.query('dictation', mapped.dictation);
    req.query('encoding', mapped.encoding);
    req.query('filler_words', mapped.fillerWords);
    req.query('keyterm', mapped.keyterm);
    req.query('keywords', mapped.keywords);
    req.query('language', mapped.language);
    req.query('measurements', mapped.measurements);
    req.query('model', mapped.model);
    req.query('multichannel', mapped.multichannel);
    req.query('numerals', mapped.numerals);
    req.query('paragraphs', mapped.paragraphs);
    req.query('profanity_filter', mapped.profanityFilter);
    req.query('punctuate', mapped.punctuate);
    req.query('redact', mapped.redact);
    req.query('replace', mapped.replace);
    req.query('search', mapped.search);
    req.query('smart_format', mapped.smartFormat);
    req.query('utterances', mapped.utterances);
    req.query('utt_split', mapped.uttSplit);
    req.query('version', mapped.version);
    req.query('mip_opt_out', mapped.mipOptOut);
    req.json(mapped.body);
    req.throwOn(400, ListenV1ResponseError, 'Invalid Request');
    req.authenticate([]);
    return req.callAsJson(
      listenV1MediaTranscribeResponse200Schema,
      requestOptions
    );
  }
}
