/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  GetProjectBalanceV1Response,
  getProjectBalanceV1ResponseSchema,
} from '../models/getProjectBalanceV1Response.js';
import {
  ListProjectBalancesV1Response,
  listProjectBalancesV1ResponseSchema,
} from '../models/listProjectBalancesV1Response.js';
import { string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { ApiError } from '@apimatic/core';

export class ManageV1ProjectsBillingBalancesApi extends BaseApi {
  /**
   * Generates a list of outstanding balances for the specified project
   *
   * @param projectId     The unique identifier of the project
   * @param authorization Use `Authorization: Token <API_KEY>` Example: `Authorization: Token 12345abcdef`
   * @return Response from the API call
   */
  async list(
    projectId: string,
    authorization: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ListProjectBalancesV1Response>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      projectId: [projectId, string()],
      authorization: [authorization, string()],
    });
    req.header('Authorization', mapped.authorization);
    req.appendTemplatePath`/v1/projects/${mapped.projectId}/balances`;
    req.throwOn(400, ApiError, 'Invalid Request');
    req.authenticate([]);
    return req.callAsJson(listProjectBalancesV1ResponseSchema, requestOptions);
  }

  /**
   * Retrieves details about the specified balance
   *
   * @param projectId     The unique identifier of the project
   * @param balanceId     The unique identifier of the balance
   * @param authorization Use `Authorization: Token <API_KEY>` Example: `Authorization: Token 12345abcdef`
   * @return Response from the API call
   */
  async get(
    projectId: string,
    balanceId: string,
    authorization: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<GetProjectBalanceV1Response>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      projectId: [projectId, string()],
      balanceId: [balanceId, string()],
      authorization: [authorization, string()],
    });
    req.header('Authorization', mapped.authorization);
    req.appendTemplatePath`/v1/projects/${mapped.projectId}/balances/${mapped.balanceId}`;
    req.throwOn(400, ApiError, 'Invalid Request');
    req.authenticate([]);
    return req.callAsJson(getProjectBalanceV1ResponseSchema, requestOptions);
  }
}
