/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  UsageFieldsV1Response,
  usageFieldsV1ResponseSchema,
} from '../models/usageFieldsV1Response.js';
import { optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { ApiError } from '@apimatic/core';

export class ManageV1ProjectsUsageFieldsApi extends BaseApi {
  /**
   * Lists the features, models, tags, languages, and processing method used for requests in the
   * specified project
   *
   * @param projectId     The unique identifier of the project
   * @param authorization Use `Authorization: Token <API_KEY>` Example: `Authorization: Token 12345abcdef`
   * @param start         Start date of the requested date range. Format accepted is YYYY-MM-DD
   * @param end           End date of the requested date range. Format accepted is YYYY-MM-DD
   * @return Response from the API call
   */
  async list(
    projectId: string,
    authorization: string,
    start?: string,
    end?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<UsageFieldsV1Response>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      projectId: [projectId, string()],
      authorization: [authorization, string()],
      start: [start, optional(string())],
      end: [end, optional(string())],
    });
    req.header('Authorization', mapped.authorization);
    req.query('start', mapped.start);
    req.query('end', mapped.end);
    req.appendTemplatePath`/v1/projects/${mapped.projectId}/usage/fields`;
    req.throwOn(400, ApiError, 'Invalid Request');
    req.authenticate([]);
    return req.callAsJson(usageFieldsV1ResponseSchema, requestOptions);
  }
}
