/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  DeleteProjectV1Response,
  deleteProjectV1ResponseSchema,
} from '../models/deleteProjectV1Response.js';
import {
  GetProjectV1Response,
  getProjectV1ResponseSchema,
} from '../models/getProjectV1Response.js';
import {
  LeaveProjectV1Response,
  leaveProjectV1ResponseSchema,
} from '../models/leaveProjectV1Response.js';
import {
  ListProjectsV1Response,
  listProjectsV1ResponseSchema,
} from '../models/listProjectsV1Response.js';
import {
  UpdateProjectV1Request,
  updateProjectV1RequestSchema,
} from '../models/updateProjectV1Request.js';
import {
  UpdateProjectV1Response,
  updateProjectV1ResponseSchema,
} from '../models/updateProjectV1Response.js';
import { number, optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { ApiError } from '@apimatic/core';

export class ManageV1ProjectsApi extends BaseApi {
  /**
   * Retrieves basic information about the projects associated with the API key
   *
   * @return Response from the API call
   */
  async list(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ListProjectsV1Response>> {
    const req = this.createRequest('GET', '/v1/projects');
    req.throwOn(400, ApiError, 'Invalid Request');
    req.authenticate([{ apiKeyAuth: true }]);
    return req.callAsJson(listProjectsV1ResponseSchema, requestOptions);
  }

  /**
   * Retrieves information about the specified project
   *
   * @param projectId  The unique identifier of the project
   * @param limit      Number of results to return per page. Default 10. Range [1,1000]
   * @param page       Navigate and return the results to retrieve specific portions of information of the
   *                             response
   * @return Response from the API call
   */
  async get(
    projectId: string,
    limit?: number,
    page?: number,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<GetProjectV1Response>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      projectId: [projectId, string()],
      limit: [limit, optional(number())],
      page: [page, optional(number())],
    });
    req.query('limit', mapped.limit);
    req.query('page', mapped.page);
    req.appendTemplatePath`/v1/projects/${mapped.projectId}`;
    req.throwOn(400, ApiError, 'Invalid Request');
    req.authenticate([{ apiKeyAuth: true }]);
    return req.callAsJson(getProjectV1ResponseSchema, requestOptions);
  }

  /**
   * Updates the name or other properties of an existing project
   *
   * @param projectId    The unique identifier of the project
   * @param body         The name of the project
   * @return Response from the API call
   */
  async update(
    projectId: string,
    body?: UpdateProjectV1Request,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<UpdateProjectV1Response>> {
    const req = this.createRequest('PATCH');
    const mapped = req.prepareArgs({
      projectId: [projectId, string()],
      body: [body, optional(updateProjectV1RequestSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/v1/projects/${mapped.projectId}`;
    req.throwOn(400, ApiError, 'Invalid Request');
    req.authenticate([{ apiKeyAuth: true }]);
    return req.callAsJson(updateProjectV1ResponseSchema, requestOptions);
  }

  /**
   * Deletes the specified project
   *
   * @param projectId  The unique identifier of the project
   * @return Response from the API call
   */
  async mDelete(
    projectId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DeleteProjectV1Response>> {
    const req = this.createRequest('DELETE');
    const mapped = req.prepareArgs({ projectId: [projectId, string()] });
    req.appendTemplatePath`/v1/projects/${mapped.projectId}`;
    req.throwOn(400, ApiError, 'Invalid Request');
    req.authenticate([{ apiKeyAuth: true }]);
    return req.callAsJson(deleteProjectV1ResponseSchema, requestOptions);
  }

  /**
   * Removes the authenticated account from the specific project
   *
   * @param projectId  The unique identifier of the project
   * @return Response from the API call
   */
  async leave(
    projectId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<LeaveProjectV1Response>> {
    const req = this.createRequest('DELETE');
    const mapped = req.prepareArgs({ projectId: [projectId, string()] });
    req.appendTemplatePath`/v1/projects/${mapped.projectId}/leave`;
    req.throwOn(400, ApiError, 'Invalid Request');
    req.authenticate([{ apiKeyAuth: true }]);
    return req.callAsJson(leaveProjectV1ResponseSchema, requestOptions);
  }
}
