/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  ListProjectMemberScopesV1Response,
  listProjectMemberScopesV1ResponseSchema,
} from '../models/listProjectMemberScopesV1Response.js';
import {
  UpdateProjectMemberScopesV1Request,
  updateProjectMemberScopesV1RequestSchema,
} from '../models/updateProjectMemberScopesV1Request.js';
import {
  UpdateProjectMemberScopesV1Response,
  updateProjectMemberScopesV1ResponseSchema,
} from '../models/updateProjectMemberScopesV1Response.js';
import { optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { ApiError } from '@apimatic/core';

export class ManageV1ProjectsMembersScopesApi extends BaseApi {
  /**
   * Retrieves a list of scopes for a specific member
   *
   * @param projectId  The unique identifier of the project
   * @param memberId   The unique identifier of the Member
   * @return Response from the API call
   */
  async list(
    projectId: string,
    memberId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ListProjectMemberScopesV1Response>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      projectId: [projectId, string()],
      memberId: [memberId, string()],
    });
    req.appendTemplatePath`/v1/projects/${mapped.projectId}/members/${mapped.memberId}/scopes`;
    req.throwOn(400, ApiError, 'Invalid Request');
    req.authenticate([{ apiKeyAuth: true }]);
    return req.callAsJson(
      listProjectMemberScopesV1ResponseSchema,
      requestOptions
    );
  }

  /**
   * Updates the scopes for a specific member
   *
   * @param projectId    The unique identifier of the project
   * @param memberId     The unique identifier of the Member
   * @param body         A scope to update
   * @return Response from the API call
   */
  async update(
    projectId: string,
    memberId: string,
    body?: UpdateProjectMemberScopesV1Request,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<UpdateProjectMemberScopesV1Response>> {
    const req = this.createRequest('PUT');
    const mapped = req.prepareArgs({
      projectId: [projectId, string()],
      memberId: [memberId, string()],
      body: [body, optional(updateProjectMemberScopesV1RequestSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/v1/projects/${mapped.projectId}/members/${mapped.memberId}/scopes`;
    req.throwOn(400, ApiError, 'Invalid Request');
    req.authenticate([{ apiKeyAuth: true }]);
    return req.callAsJson(
      updateProjectMemberScopesV1ResponseSchema,
      requestOptions
    );
  }
}
