/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  CreateKeyV1Request,
  createKeyV1RequestSchema,
} from '../models/containers/createKeyV1Request.js';
import {
  CreateKeyV1Response,
  createKeyV1ResponseSchema,
} from '../models/createKeyV1Response.js';
import {
  DeleteProjectKeyV1Response,
  deleteProjectKeyV1ResponseSchema,
} from '../models/deleteProjectKeyV1Response.js';
import {
  GetProjectKeyV1Response,
  getProjectKeyV1ResponseSchema,
} from '../models/getProjectKeyV1Response.js';
import {
  ListProjectKeysV1Response,
  listProjectKeysV1ResponseSchema,
} from '../models/listProjectKeysV1Response.js';
import {
  V1ProjectsProjectIdKeysGetParametersStatus,
  v1ProjectsProjectIdKeysGetParametersStatusSchema,
} from '../models/v1ProjectsProjectIdKeysGetParametersStatus.js';
import { optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { ApiError } from '@apimatic/core';

export class ManageV1ProjectsKeysApi extends BaseApi {
  /**
   * Retrieves all API keys associated with the specified project
   *
   * @param projectId     The unique identifier of the project
   * @param authorization Use `Authorization: Token <API_KEY>` Example:
   *                                                                    `Authorization: Token 12345abcdef`
   * @param status        Only return keys with a specific status
   * @return Response from the API call
   */
  async list(
    projectId: string,
    authorization: string,
    status?: V1ProjectsProjectIdKeysGetParametersStatus,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ListProjectKeysV1Response>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      projectId: [projectId, string()],
      authorization: [authorization, string()],
      status: [
        status,
        optional(v1ProjectsProjectIdKeysGetParametersStatusSchema),
      ],
    });
    req.header('Authorization', mapped.authorization);
    req.query('status', mapped.status);
    req.appendTemplatePath`/v1/projects/${mapped.projectId}/keys`;
    req.throwOn(400, ApiError, 'Invalid Request');
    req.authenticate([]);
    return req.callAsJson(listProjectKeysV1ResponseSchema, requestOptions);
  }

  /**
   * Creates a new API key with specified settings for the project
   *
   * @param projectId     The unique identifier of the project
   * @param authorization Use `Authorization: Token <API_KEY>` Example: `Authorization: Token
   *                                            12345abcdef`
   * @param body          API key settings
   * @return Response from the API call
   */
  async create(
    projectId: string,
    authorization: string,
    body?: CreateKeyV1Request,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<CreateKeyV1Response>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({
      projectId: [projectId, string()],
      authorization: [authorization, string()],
      body: [body, optional(createKeyV1RequestSchema)],
    });
    req.header('Authorization', mapped.authorization);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/v1/projects/${mapped.projectId}/keys`;
    req.throwOn(400, ApiError, 'Invalid Request');
    req.authenticate([]);
    return req.callAsJson(createKeyV1ResponseSchema, requestOptions);
  }

  /**
   * Retrieves information about a specified API key
   *
   * @param projectId     The unique identifier of the project
   * @param keyId         The unique identifier of the API key
   * @param authorization Use `Authorization: Token <API_KEY>` Example: `Authorization: Token 12345abcdef`
   * @return Response from the API call
   */
  async get(
    projectId: string,
    keyId: string,
    authorization: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<GetProjectKeyV1Response>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      projectId: [projectId, string()],
      keyId: [keyId, string()],
      authorization: [authorization, string()],
    });
    req.header('Authorization', mapped.authorization);
    req.appendTemplatePath`/v1/projects/${mapped.projectId}/keys/${mapped.keyId}`;
    req.throwOn(400, ApiError, 'Invalid Request');
    req.authenticate([]);
    return req.callAsJson(getProjectKeyV1ResponseSchema, requestOptions);
  }

  /**
   * Deletes an API key for a specific project
   *
   * @param projectId     The unique identifier of the project
   * @param keyId         The unique identifier of the API key
   * @param authorization Use `Authorization: Token <API_KEY>` Example: `Authorization: Token 12345abcdef`
   * @return Response from the API call
   */
  async mDelete(
    projectId: string,
    keyId: string,
    authorization: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DeleteProjectKeyV1Response>> {
    const req = this.createRequest('DELETE');
    const mapped = req.prepareArgs({
      projectId: [projectId, string()],
      keyId: [keyId, string()],
      authorization: [authorization, string()],
    });
    req.header('Authorization', mapped.authorization);
    req.appendTemplatePath`/v1/projects/${mapped.projectId}/keys/${mapped.keyId}`;
    req.throwOn(400, ApiError, 'Invalid Request');
    req.authenticate([]);
    return req.callAsJson(deleteProjectKeyV1ResponseSchema, requestOptions);
  }
}
