/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  ListBillingFieldsV1Response,
  listBillingFieldsV1ResponseSchema,
} from '../models/listBillingFieldsV1Response.js';
import { optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { ApiError } from '@apimatic/core';

export class ManageV1ProjectsBillingFieldsApi extends BaseApi {
  /**
   * Lists the accessors, deployment types, tags, and line items used for billing data in the specified
   * time period. Use this endpoint if you want to filter your results from the Billing Breakdown
   * endpoint and want to know what filters are available.
   *
   * @param projectId  The unique identifier of the project
   * @param start      Start date of the requested date range. Format accepted is YYYY-MM-DD
   * @param end        End date of the requested date range. Format accepted is YYYY-MM-DD
   * @return Response from the API call
   */
  async list(
    projectId: string,
    start?: string,
    end?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ListBillingFieldsV1Response>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      projectId: [projectId, string()],
      start: [start, optional(string())],
      end: [end, optional(string())],
    });
    req.query('start', mapped.start);
    req.query('end', mapped.end);
    req.appendTemplatePath`/v1/projects/${mapped.projectId}/billing/fields`;
    req.throwOn(400, ApiError, 'Invalid Request');
    req.authenticate([{ apiKeyAuth: true }]);
    return req.callAsJson(listBillingFieldsV1ResponseSchema, requestOptions);
  }
}
