/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  DeleteProjectMemberV1Response,
  deleteProjectMemberV1ResponseSchema,
} from '../models/deleteProjectMemberV1Response.js';
import {
  ListProjectMembersV1Response,
  listProjectMembersV1ResponseSchema,
} from '../models/listProjectMembersV1Response.js';
import { string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { ApiError } from '@apimatic/core';

export class ManageV1ProjectsMembersApi extends BaseApi {
  /**
   * Retrieves a list of members for a given project
   *
   * @param projectId     The unique identifier of the project
   * @param authorization Use `Authorization: Token <API_KEY>` Example: `Authorization: Token 12345abcdef`
   * @return Response from the API call
   */
  async list(
    projectId: string,
    authorization: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ListProjectMembersV1Response>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      projectId: [projectId, string()],
      authorization: [authorization, string()],
    });
    req.header('Authorization', mapped.authorization);
    req.appendTemplatePath`/v1/projects/${mapped.projectId}/members`;
    req.throwOn(400, ApiError, 'Invalid Request');
    req.authenticate([]);
    return req.callAsJson(listProjectMembersV1ResponseSchema, requestOptions);
  }

  /**
   * Removes a member from the project using their unique member ID
   *
   * @param projectId     The unique identifier of the project
   * @param memberId      The unique identifier of the Member
   * @param authorization Use `Authorization: Token <API_KEY>` Example: `Authorization: Token 12345abcdef`
   * @return Response from the API call
   */
  async mDelete(
    projectId: string,
    memberId: string,
    authorization: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DeleteProjectMemberV1Response>> {
    const req = this.createRequest('DELETE');
    const mapped = req.prepareArgs({
      projectId: [projectId, string()],
      memberId: [memberId, string()],
      authorization: [authorization, string()],
    });
    req.header('Authorization', mapped.authorization);
    req.appendTemplatePath`/v1/projects/${mapped.projectId}/members/${mapped.memberId}`;
    req.throwOn(400, ApiError, 'Invalid Request');
    req.authenticate([]);
    return req.callAsJson(deleteProjectMemberV1ResponseSchema, requestOptions);
  }
}
