/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  ListProjectPurchasesV1Response,
  listProjectPurchasesV1ResponseSchema,
} from '../models/listProjectPurchasesV1Response.js';
import { number, optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { ApiError } from '@apimatic/core';

export class ManageV1ProjectsBillingPurchasesApi extends BaseApi {
  /**
   * Returns the original purchased amount on an order transaction
   *
   * @param projectId     The unique identifier of the project
   * @param authorization Use `Authorization: Token <API_KEY>` Example: `Authorization: Token 12345abcdef`
   * @param limit         Number of results to return per page. Default 10. Range [1,1000]
   * @return Response from the API call
   */
  async list(
    projectId: string,
    authorization: string,
    limit?: number,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ListProjectPurchasesV1Response>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      projectId: [projectId, string()],
      authorization: [authorization, string()],
      limit: [limit, optional(number())],
    });
    req.header('Authorization', mapped.authorization);
    req.query('limit', mapped.limit);
    req.appendTemplatePath`/v1/projects/${mapped.projectId}/purchases`;
    req.throwOn(400, ApiError, 'Invalid Request');
    req.authenticate([]);
    return req.callAsJson(listProjectPurchasesV1ResponseSchema, requestOptions);
  }
}
