/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  GetModelV1Response,
  getModelV1ResponseSchema,
} from '../models/containers/getModelV1Response.js';
import {
  ListModelsV1Response,
  listModelsV1ResponseSchema,
} from '../models/listModelsV1Response.js';
import { boolean, optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { ApiError } from '@apimatic/core';

export class ManageV1ProjectsModelsApi extends BaseApi {
  /**
   * Returns metadata on all the latest models that a specific project has access to, including non-
   * public models
   *
   * @param projectId        The unique identifier of the project
   * @param includeOutdated  returns non-latest versions of models
   * @return Response from the API call
   */
  async list(
    projectId: string,
    includeOutdated?: boolean,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ListModelsV1Response>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      projectId: [projectId, string()],
      includeOutdated: [includeOutdated, optional(boolean())],
    });
    req.query('include_outdated', mapped.includeOutdated);
    req.appendTemplatePath`/v1/projects/${mapped.projectId}/models`;
    req.throwOn(400, ApiError, 'Invalid Request');
    req.authenticate([{ apiKeyAuth: true }]);
    return req.callAsJson(listModelsV1ResponseSchema, requestOptions);
  }

  /**
   * Returns metadata for a specific model
   *
   * @param projectId  The unique identifier of the project
   * @param modelId    The specific UUID of the model
   * @return Response from the API call
   */
  async get(
    projectId: string,
    modelId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<GetModelV1Response>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      projectId: [projectId, string()],
      modelId: [modelId, string()],
    });
    req.appendTemplatePath`/v1/projects/${mapped.projectId}/models/${mapped.modelId}`;
    req.throwOn(400, ApiError, 'Invalid Request');
    req.authenticate([{ apiKeyAuth: true }]);
    return req.callAsJson(getModelV1ResponseSchema, requestOptions);
  }
}
