/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  CreateProjectInviteV1Request,
  createProjectInviteV1RequestSchema,
} from '../models/createProjectInviteV1Request.js';
import {
  CreateProjectInviteV1Response,
  createProjectInviteV1ResponseSchema,
} from '../models/createProjectInviteV1Response.js';
import {
  DeleteProjectInviteV1Response,
  deleteProjectInviteV1ResponseSchema,
} from '../models/deleteProjectInviteV1Response.js';
import {
  ListProjectInvitesV1Response,
  listProjectInvitesV1ResponseSchema,
} from '../models/listProjectInvitesV1Response.js';
import { optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { ApiError } from '@apimatic/core';

export class ManageV1ProjectsMembersInvitesApi extends BaseApi {
  /**
   * Generates a list of invites for a specific project
   *
   * @param projectId  The unique identifier of the project
   * @return Response from the API call
   */
  async list(
    projectId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ListProjectInvitesV1Response>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ projectId: [projectId, string()] });
    req.appendTemplatePath`/v1/projects/${mapped.projectId}/invites`;
    req.throwOn(400, ApiError, 'Invalid Request');
    req.authenticate([{ apiKeyAuth: true }]);
    return req.callAsJson(listProjectInvitesV1ResponseSchema, requestOptions);
  }

  /**
   * Generates an invite for a specific project
   *
   * @param projectId    The unique identifier of the project
   * @param body         email to invite to the project
   * @return Response from the API call
   */
  async create(
    projectId: string,
    body?: CreateProjectInviteV1Request,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<CreateProjectInviteV1Response>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({
      projectId: [projectId, string()],
      body: [body, optional(createProjectInviteV1RequestSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/v1/projects/${mapped.projectId}/invites`;
    req.throwOn(400, ApiError, 'Invalid Request');
    req.authenticate([{ apiKeyAuth: true }]);
    return req.callAsJson(createProjectInviteV1ResponseSchema, requestOptions);
  }

  /**
   * Deletes an invite for a specific project
   *
   * @param projectId  The unique identifier of the project
   * @param email      The email address of the member
   * @return Response from the API call
   */
  async mDelete(
    projectId: string,
    email: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DeleteProjectInviteV1Response>> {
    const req = this.createRequest('DELETE');
    const mapped = req.prepareArgs({
      projectId: [projectId, string()],
      email: [email, string()],
    });
    req.appendTemplatePath`/v1/projects/${mapped.projectId}/invites/${mapped.email}`;
    req.throwOn(400, ApiError, 'Invalid Request');
    req.authenticate([{ apiKeyAuth: true }]);
    return req.callAsJson(deleteProjectInviteV1ResponseSchema, requestOptions);
  }
}
