/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  GetModelV1Response,
  getModelV1ResponseSchema,
} from '../models/containers/getModelV1Response.js';
import {
  ListModelsV1Response,
  listModelsV1ResponseSchema,
} from '../models/listModelsV1Response.js';
import { boolean, optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { ApiError } from '@apimatic/core';

export class ManageV1ModelsApi extends BaseApi {
  /**
   * Returns metadata on all the latest public models. To retrieve custom models, use Get Project Models.
   *
   * @param includeOutdated  returns non-latest versions of models
   * @return Response from the API call
   */
  async list(
    includeOutdated?: boolean,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ListModelsV1Response>> {
    const req = this.createRequest('GET', '/v1/models');
    const mapped = req.prepareArgs({
      includeOutdated: [includeOutdated, optional(boolean())],
    });
    req.query('include_outdated', mapped.includeOutdated);
    req.throwOn(400, ApiError, 'Invalid Request');
    req.authenticate([{ apiKeyAuth: true }]);
    return req.callAsJson(listModelsV1ResponseSchema, requestOptions);
  }

  /**
   * Returns metadata for a specific public model
   *
   * @param modelId  The specific UUID of the model
   * @return Response from the API call
   */
  async get(
    modelId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<GetModelV1Response>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ modelId: [modelId, string()] });
    req.appendTemplatePath`/v1/models/${mapped.modelId}`;
    req.throwOn(400, ApiError, 'Invalid Request');
    req.authenticate([{ apiKeyAuth: true }]);
    return req.callAsJson(getModelV1ResponseSchema, requestOptions);
  }
}
