/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  BillingBreakdownV1Response,
  billingBreakdownV1ResponseSchema,
} from '../models/billingBreakdownV1Response.js';
import {
  V1ProjectsProjectIdBillingBreakdownGetParametersDeployment,
  v1ProjectsProjectIdBillingBreakdownGetParametersDeploymentSchema,
} from '../models/v1ProjectsProjectIdBillingBreakdownGetParametersDeployment.js';
import {
  V1ProjectsProjectIdBillingBreakdownGetParametersGroupingSchemaItems,
  v1ProjectsProjectIdBillingBreakdownGetParametersGroupingSchemaItemsSchema,
} from '../models/v1ProjectsProjectIdBillingBreakdownGetParametersGroupingSchemaItems.js';
import { array, optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { ApiError } from '@apimatic/core';

export class ManageV1ProjectsBillingBreakdownApi extends BaseApi {
  /**
   * Retrieves the billing summary for a specific project, with various filter options or by grouping
   * options.
   *
   * @param projectId  The unique identifier
   *                                                                                            of the project
   * @param start      Start date of the
   *                                                                                            requested date range.
   *                                                                                            Format accepted is YYYY-
   *                                                                                            MM-DD
   * @param end        End date of the
   *                                                                                            requested date range.
   *                                                                                            Format accepted is YYYY-
   *                                                                                            MM-DD
   * @param accessor   Filter for requests
   *                                                                                            where a specific
   *                                                                                            accessor was used
   * @param deployment Filter for requests
   *                                                                                            where a specific
   *                                                                                            deployment was used
   * @param tag        Filter for requests
   *                                                                                            where a specific tag
   *                                                                                            was used
   * @param lineItem   Filter requests by
   *                                                                                            line item (e.g.
   *                                                                                            streaming::nova-3)
   * @param grouping   Group billing
   *                                                                                            breakdown by one or
   *                                                                                            more dimensions
   *                                                                                            (accessor, deployment,
   *                                                                                            line_item, tags)
   * @return Response from the API call
   */
  async list(
    projectId: string,
    start?: string,
    end?: string,
    accessor?: string,
    deployment?: V1ProjectsProjectIdBillingBreakdownGetParametersDeployment,
    tag?: string,
    lineItem?: string,
    grouping?: V1ProjectsProjectIdBillingBreakdownGetParametersGroupingSchemaItems[],
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<BillingBreakdownV1Response>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      projectId: [projectId, string()],
      start: [start, optional(string())],
      end: [end, optional(string())],
      accessor: [accessor, optional(string())],
      deployment: [
        deployment,
        optional(
          v1ProjectsProjectIdBillingBreakdownGetParametersDeploymentSchema
        ),
      ],
      tag: [tag, optional(string())],
      lineItem: [lineItem, optional(string())],
      grouping: [
        grouping,
        optional(
          array(
            v1ProjectsProjectIdBillingBreakdownGetParametersGroupingSchemaItemsSchema
          )
        ),
      ],
    });
    req.query('start', mapped.start);
    req.query('end', mapped.end);
    req.query('accessor', mapped.accessor);
    req.query('deployment', mapped.deployment);
    req.query('tag', mapped.tag);
    req.query('line_item', mapped.lineItem);
    req.query('grouping', mapped.grouping);
    req.appendTemplatePath`/v1/projects/${mapped.projectId}/billing/breakdown`;
    req.throwOn(400, ApiError, 'Invalid Request');
    req.authenticate([{ apiKeyAuth: true }]);
    return req.callAsJson(billingBreakdownV1ResponseSchema, requestOptions);
  }
}
