/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  UsageBreakdownV1Response,
  usageBreakdownV1ResponseSchema,
} from '../models/usageBreakdownV1Response.js';
import {
  V1ProjectsProjectIdUsageBreakdownGetParametersDeployment,
  v1ProjectsProjectIdUsageBreakdownGetParametersDeploymentSchema,
} from '../models/v1ProjectsProjectIdUsageBreakdownGetParametersDeployment.js';
import {
  V1ProjectsProjectIdUsageBreakdownGetParametersEndpoint,
  v1ProjectsProjectIdUsageBreakdownGetParametersEndpointSchema,
} from '../models/v1ProjectsProjectIdUsageBreakdownGetParametersEndpoint.js';
import {
  V1ProjectsProjectIdUsageBreakdownGetParametersGrouping,
  v1ProjectsProjectIdUsageBreakdownGetParametersGroupingSchema,
} from '../models/v1ProjectsProjectIdUsageBreakdownGetParametersGrouping.js';
import {
  V1ProjectsProjectIdUsageBreakdownGetParametersMethod,
  v1ProjectsProjectIdUsageBreakdownGetParametersMethodSchema,
} from '../models/v1ProjectsProjectIdUsageBreakdownGetParametersMethod.js';
import { boolean, optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { ApiError } from '@apimatic/core';

export class ManageV1ProjectsUsageBreakdownApi extends BaseApi {
  /**
   * Retrieves the usage breakdown for a specific project, with various filter options by API feature or
   * by groupings. Setting a feature (e.g. diarize) to true includes requests that used that feature,
   * while false excludes requests that used it. Multiple true filters are combined with OR logic, while
   * false filters use AND logic.
   *
   * @param projectId          The unique identifier of
   *                                                                                       the project
   * @param authorization      Use `Authorization: Token
   *                                                                                       <API_KEY>` Example:
   *                                                                                       `Authorization: Token
   *                                                                                       12345abcdef`
   * @param start              Start date of the requested
   *                                                                                       date range. Format accepted
   *                                                                                       is YYYY-MM-DD
   * @param end                End date of the requested
   *                                                                                       date range. Format accepted
   *                                                                                       is YYYY-MM-DD
   * @param grouping           Common usage grouping
   *                                                                                       parameters
   * @param accessor           Filter for requests where a
   *                                                                                       specific accessor was used
   * @param alternatives       Filter for requests where
   *                                                                                       alternatives were used
   * @param callbackMethod     Filter for requests where
   *                                                                                       callback method was used
   * @param callback           Filter for requests where
   *                                                                                       callback was used
   * @param channels           Filter for requests where
   *                                                                                       channels were used
   * @param customIntentMode   Filter for requests where
   *                                                                                       custom intent mode was used
   * @param customIntent       Filter for requests where
   *                                                                                       custom intent was used
   * @param customTopicMode    Filter for requests where
   *                                                                                       custom topic mode was used
   * @param customTopic        Filter for requests where
   *                                                                                       custom topic was used
   * @param deployment         Filter for requests where a
   *                                                                                       specific deployment was
   *                                                                                       used
   * @param detectEntities     Filter for requests where
   *                                                                                       detect entities was used
   * @param detectLanguage     Filter for requests where
   *                                                                                       detect language was used
   * @param diarize            Filter for requests where
   *                                                                                       diarize was used
   * @param dictation          Filter for requests where
   *                                                                                       dictation was used
   * @param encoding           Filter for requests where
   *                                                                                       encoding was used
   * @param endpoint           Filter for requests where a
   *                                                                                       specific endpoint was used
   * @param extra              Filter for requests where
   *                                                                                       extra was used
   * @param fillerWords        Filter for requests where
   *                                                                                       filler words was used
   * @param intents            Filter for requests where
   *                                                                                       intents was used
   * @param keyterm            Filter for requests where
   *                                                                                       keyterm was used
   * @param keywords           Filter for requests where
   *                                                                                       keywords was used
   * @param language           Filter for requests where
   *                                                                                       language was used
   * @param measurements       Filter for requests where
   *                                                                                       measurements were used
   * @param method             Filter for requests where a
   *                                                                                       specific method was used
   * @param model              Filter for requests where a
   *                                                                                       specific model uuid was
   *                                                                                       used
   * @param multichannel       Filter for requests where
   *                                                                                       multichannel was used
   * @param numerals           Filter for requests where
   *                                                                                       numerals were used
   * @param paragraphs         Filter for requests where
   *                                                                                       paragraphs were used
   * @param profanityFilter    Filter for requests where
   *                                                                                       profanity filter was used
   * @param punctuate          Filter for requests where
   *                                                                                       punctuate was used
   * @param redact             Filter for requests where
   *                                                                                       redact was used
   * @param replace            Filter for requests where
   *                                                                                       replace was used
   * @param sampleRate         Filter for requests where
   *                                                                                       sample rate was used
   * @param search             Filter for requests where
   *                                                                                       search was used
   * @param sentiment          Filter for requests where
   *                                                                                       sentiment was used
   * @param smartFormat        Filter for requests where
   *                                                                                       smart format was used
   * @param summarize          Filter for requests where
   *                                                                                       summarize was used
   * @param tag                Filter for requests where a
   *                                                                                       specific tag was used
   * @param topics             Filter for requests where
   *                                                                                       topics was used
   * @param uttSplit           Filter for requests where
   *                                                                                       utt split was used
   * @param utterances         Filter for requests where
   *                                                                                       utterances was used
   * @param version            Filter for requests where
   *                                                                                       version was used
   * @return Response from the API call
   */
  async get(
    projectId: string,
    authorization: string,
    start?: string,
    end?: string,
    grouping?: V1ProjectsProjectIdUsageBreakdownGetParametersGrouping,
    accessor?: string,
    alternatives?: boolean,
    callbackMethod?: boolean,
    callback?: boolean,
    channels?: boolean,
    customIntentMode?: boolean,
    customIntent?: boolean,
    customTopicMode?: boolean,
    customTopic?: boolean,
    deployment?: V1ProjectsProjectIdUsageBreakdownGetParametersDeployment,
    detectEntities?: boolean,
    detectLanguage?: boolean,
    diarize?: boolean,
    dictation?: boolean,
    encoding?: boolean,
    endpoint?: V1ProjectsProjectIdUsageBreakdownGetParametersEndpoint,
    extra?: boolean,
    fillerWords?: boolean,
    intents?: boolean,
    keyterm?: boolean,
    keywords?: boolean,
    language?: boolean,
    measurements?: boolean,
    method?: V1ProjectsProjectIdUsageBreakdownGetParametersMethod,
    model?: string,
    multichannel?: boolean,
    numerals?: boolean,
    paragraphs?: boolean,
    profanityFilter?: boolean,
    punctuate?: boolean,
    redact?: boolean,
    replace?: boolean,
    sampleRate?: boolean,
    search?: boolean,
    sentiment?: boolean,
    smartFormat?: boolean,
    summarize?: boolean,
    tag?: string,
    topics?: boolean,
    uttSplit?: boolean,
    utterances?: boolean,
    version?: boolean,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<UsageBreakdownV1Response>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      projectId: [projectId, string()],
      authorization: [authorization, string()],
      start: [start, optional(string())],
      end: [end, optional(string())],
      grouping: [
        grouping,
        optional(v1ProjectsProjectIdUsageBreakdownGetParametersGroupingSchema),
      ],
      accessor: [accessor, optional(string())],
      alternatives: [alternatives, optional(boolean())],
      callbackMethod: [callbackMethod, optional(boolean())],
      callback: [callback, optional(boolean())],
      channels: [channels, optional(boolean())],
      customIntentMode: [customIntentMode, optional(boolean())],
      customIntent: [customIntent, optional(boolean())],
      customTopicMode: [customTopicMode, optional(boolean())],
      customTopic: [customTopic, optional(boolean())],
      deployment: [
        deployment,
        optional(
          v1ProjectsProjectIdUsageBreakdownGetParametersDeploymentSchema
        ),
      ],
      detectEntities: [detectEntities, optional(boolean())],
      detectLanguage: [detectLanguage, optional(boolean())],
      diarize: [diarize, optional(boolean())],
      dictation: [dictation, optional(boolean())],
      encoding: [encoding, optional(boolean())],
      endpoint: [
        endpoint,
        optional(v1ProjectsProjectIdUsageBreakdownGetParametersEndpointSchema),
      ],
      extra: [extra, optional(boolean())],
      fillerWords: [fillerWords, optional(boolean())],
      intents: [intents, optional(boolean())],
      keyterm: [keyterm, optional(boolean())],
      keywords: [keywords, optional(boolean())],
      language: [language, optional(boolean())],
      measurements: [measurements, optional(boolean())],
      method: [
        method,
        optional(v1ProjectsProjectIdUsageBreakdownGetParametersMethodSchema),
      ],
      model: [model, optional(string())],
      multichannel: [multichannel, optional(boolean())],
      numerals: [numerals, optional(boolean())],
      paragraphs: [paragraphs, optional(boolean())],
      profanityFilter: [profanityFilter, optional(boolean())],
      punctuate: [punctuate, optional(boolean())],
      redact: [redact, optional(boolean())],
      replace: [replace, optional(boolean())],
      sampleRate: [sampleRate, optional(boolean())],
      search: [search, optional(boolean())],
      sentiment: [sentiment, optional(boolean())],
      smartFormat: [smartFormat, optional(boolean())],
      summarize: [summarize, optional(boolean())],
      tag: [tag, optional(string())],
      topics: [topics, optional(boolean())],
      uttSplit: [uttSplit, optional(boolean())],
      utterances: [utterances, optional(boolean())],
      version: [version, optional(boolean())],
    });
    req.header('Authorization', mapped.authorization);
    req.query('start', mapped.start);
    req.query('end', mapped.end);
    req.query('grouping', mapped.grouping);
    req.query('accessor', mapped.accessor);
    req.query('alternatives', mapped.alternatives);
    req.query('callback_method', mapped.callbackMethod);
    req.query('callback', mapped.callback);
    req.query('channels', mapped.channels);
    req.query('custom_intent_mode', mapped.customIntentMode);
    req.query('custom_intent', mapped.customIntent);
    req.query('custom_topic_mode', mapped.customTopicMode);
    req.query('custom_topic', mapped.customTopic);
    req.query('deployment', mapped.deployment);
    req.query('detect_entities', mapped.detectEntities);
    req.query('detect_language', mapped.detectLanguage);
    req.query('diarize', mapped.diarize);
    req.query('dictation', mapped.dictation);
    req.query('encoding', mapped.encoding);
    req.query('endpoint', mapped.endpoint);
    req.query('extra', mapped.extra);
    req.query('filler_words', mapped.fillerWords);
    req.query('intents', mapped.intents);
    req.query('keyterm', mapped.keyterm);
    req.query('keywords', mapped.keywords);
    req.query('language', mapped.language);
    req.query('measurements', mapped.measurements);
    req.query('method', mapped.method);
    req.query('model', mapped.model);
    req.query('multichannel', mapped.multichannel);
    req.query('numerals', mapped.numerals);
    req.query('paragraphs', mapped.paragraphs);
    req.query('profanity_filter', mapped.profanityFilter);
    req.query('punctuate', mapped.punctuate);
    req.query('redact', mapped.redact);
    req.query('replace', mapped.replace);
    req.query('sample_rate', mapped.sampleRate);
    req.query('search', mapped.search);
    req.query('sentiment', mapped.sentiment);
    req.query('smart_format', mapped.smartFormat);
    req.query('summarize', mapped.summarize);
    req.query('tag', mapped.tag);
    req.query('topics', mapped.topics);
    req.query('utt_split', mapped.uttSplit);
    req.query('utterances', mapped.utterances);
    req.query('version', mapped.version);
    req.appendTemplatePath`/v1/projects/${mapped.projectId}/usage/breakdown`;
    req.throwOn(400, ApiError, 'Invalid Request');
    req.authenticate([]);
    return req.callAsJson(usageBreakdownV1ResponseSchema, requestOptions);
  }
}
