/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  GetProjectRequestV1Response,
  getProjectRequestV1ResponseSchema,
} from '../models/getProjectRequestV1Response.js';
import {
  ListProjectRequestsV1Response,
  listProjectRequestsV1ResponseSchema,
} from '../models/listProjectRequestsV1Response.js';
import {
  V1ProjectsProjectIdRequestsGetParametersDeployment,
  v1ProjectsProjectIdRequestsGetParametersDeploymentSchema,
} from '../models/v1ProjectsProjectIdRequestsGetParametersDeployment.js';
import {
  V1ProjectsProjectIdRequestsGetParametersEndpoint,
  v1ProjectsProjectIdRequestsGetParametersEndpointSchema,
} from '../models/v1ProjectsProjectIdRequestsGetParametersEndpoint.js';
import {
  V1ProjectsProjectIdRequestsGetParametersMethod,
  v1ProjectsProjectIdRequestsGetParametersMethodSchema,
} from '../models/v1ProjectsProjectIdRequestsGetParametersMethod.js';
import {
  V1ProjectsProjectIdRequestsGetParametersStatus,
  v1ProjectsProjectIdRequestsGetParametersStatusSchema,
} from '../models/v1ProjectsProjectIdRequestsGetParametersStatus.js';
import { number, optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { ApiError } from '@apimatic/core';

export class ManageV1ProjectsRequestsApi extends BaseApi {
  /**
   * Generates a list of requests for a specific project
   *
   * @param projectId     The unique identifier of the project
   * @param authorization Use `Authorization: Token <API_KEY>`
   *                                                                            Example: `Authorization: Token
   *                                                                            12345abcdef`
   * @param start         Start date of the requested date range.
   *                                                                            Formats accepted are YYYY-MM-DD, YYYY-
   *                                                                            MM-DDTHH:MM:SS, or YYYY-MM-DDTHH:MM:
   *                                                                            SS+HH:MM
   * @param end           End date of the requested date range.
   *                                                                            Formats accepted are YYYY-MM-DD, YYYY-
   *                                                                            MM-DDTHH:MM:SS, or YYYY-MM-DDTHH:MM:
   *                                                                            SS+HH:MM
   * @param limit         Number of results to return per page.
   *                                                                            Default 10. Range [1,1000]
   * @param page          Navigate and return the results to
   *                                                                            retrieve specific portions of
   *                                                                            information of the response
   * @param accessor      Filter for requests where a specific
   *                                                                            accessor was used
   * @param requestId     Filter for a specific request id
   * @param deployment    Filter for requests where a specific
   *                                                                            deployment was used
   * @param endpoint      Filter for requests where a specific
   *                                                                            endpoint was used
   * @param method        Filter for requests where a specific
   *                                                                            method was used
   * @param status        Filter for requests that succeeded
   *                                                                            (status code < 300) or failed (status
   *                                                                            code >=400)
   * @return Response from the API call
   */
  async list(
    projectId: string,
    authorization: string,
    start?: string,
    end?: string,
    limit?: number,
    page?: number,
    accessor?: string,
    requestId?: string,
    deployment?: V1ProjectsProjectIdRequestsGetParametersDeployment,
    endpoint?: V1ProjectsProjectIdRequestsGetParametersEndpoint,
    method?: V1ProjectsProjectIdRequestsGetParametersMethod,
    status?: V1ProjectsProjectIdRequestsGetParametersStatus,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ListProjectRequestsV1Response>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      projectId: [projectId, string()],
      authorization: [authorization, string()],
      start: [start, optional(string())],
      end: [end, optional(string())],
      limit: [limit, optional(number())],
      page: [page, optional(number())],
      accessor: [accessor, optional(string())],
      requestId: [requestId, optional(string())],
      deployment: [
        deployment,
        optional(v1ProjectsProjectIdRequestsGetParametersDeploymentSchema),
      ],
      endpoint: [
        endpoint,
        optional(v1ProjectsProjectIdRequestsGetParametersEndpointSchema),
      ],
      method: [
        method,
        optional(v1ProjectsProjectIdRequestsGetParametersMethodSchema),
      ],
      status: [
        status,
        optional(v1ProjectsProjectIdRequestsGetParametersStatusSchema),
      ],
    });
    req.header('Authorization', mapped.authorization);
    req.query('start', mapped.start);
    req.query('end', mapped.end);
    req.query('limit', mapped.limit);
    req.query('page', mapped.page);
    req.query('accessor', mapped.accessor);
    req.query('request_id', mapped.requestId);
    req.query('deployment', mapped.deployment);
    req.query('endpoint', mapped.endpoint);
    req.query('method', mapped.method);
    req.query('status', mapped.status);
    req.appendTemplatePath`/v1/projects/${mapped.projectId}/requests`;
    req.throwOn(400, ApiError, 'Invalid Request');
    req.authenticate([]);
    return req.callAsJson(listProjectRequestsV1ResponseSchema, requestOptions);
  }

  /**
   * Retrieves a specific request for a specific project
   *
   * @param projectId     The unique identifier of the project
   * @param requestId     The unique identifier of the request
   * @param authorization Use `Authorization: Token <API_KEY>` Example: `Authorization: Token 12345abcdef`
   * @return Response from the API call
   */
  async get(
    projectId: string,
    requestId: string,
    authorization: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<GetProjectRequestV1Response>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      projectId: [projectId, string()],
      requestId: [requestId, string()],
      authorization: [authorization, string()],
    });
    req.header('Authorization', mapped.authorization);
    req.appendTemplatePath`/v1/projects/${mapped.projectId}/requests/${mapped.requestId}`;
    req.throwOn(400, ApiError, 'Invalid Request');
    req.authenticate([]);
    return req.callAsJson(getProjectRequestV1ResponseSchema, requestOptions);
  }
}
