/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  ReadV1Request,
  readV1RequestSchema,
} from '../models/containers/readV1Request.js';
import {
  V1ReadPostParametersCustomIntent,
  v1ReadPostParametersCustomIntentSchema,
} from '../models/containers/v1ReadPostParametersCustomIntent.js';
import {
  V1ReadPostParametersCustomTopic,
  v1ReadPostParametersCustomTopicSchema,
} from '../models/containers/v1ReadPostParametersCustomTopic.js';
import {
  V1ReadPostParametersSummarize,
  v1ReadPostParametersSummarizeSchema,
} from '../models/containers/v1ReadPostParametersSummarize.js';
import {
  V1ReadPostParametersTag,
  v1ReadPostParametersTagSchema,
} from '../models/containers/v1ReadPostParametersTag.js';
import {
  ReadV1Response,
  readV1ResponseSchema,
} from '../models/readV1Response.js';
import {
  V1ListenPostParametersCallbackMethod,
  v1ListenPostParametersCallbackMethodSchema,
} from '../models/v1ListenPostParametersCallbackMethod.js';
import {
  V1ListenPostParametersCustomTopicMode,
  v1ListenPostParametersCustomTopicModeSchema,
} from '../models/v1ListenPostParametersCustomTopicMode.js';
import { boolean, optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { ApiError } from '@apimatic/core';

export class ReadV1TextApi extends BaseApi {
  /**
   * Analyze text content using Deepgrams text analysis API
   *
   * @param authorization      Use `Authorization: Token <API_KEY>` Example:
   *                                                                    `Authorization: Token 12345abcdef`
   * @param callback           URL to which we'll make the callback request
   * @param callbackMethod     HTTP method by which the callback request will
   *                                                                    be made
   * @param sentiment          Recognizes the sentiment throughout a
   *                                                                    transcript or text
   * @param summarize          Summarize content. For Listen API, supports
   *                                                                    string version option. For Read API, accepts
   *                                                                    boolean only.
   * @param tag                Label your requests for the purpose of
   *                                                                    identification during usage reporting
   * @param topics             Detect topics throughout a transcript or text
   * @param customTopic        Custom topics you want the model to detect
   *                                                                    within your input audio or text if present
   *                                                                    Submit up to `100`.
   * @param customTopicMode    Sets how the model will interpret strings
   *                                                                    submitted to the `custom_topic` param. When
   *                                                                    `strict`, the model will only return topics
   *                                                                    submitted using the `custom_topic` param. When
   *                                                                    `extended`, the model will return its own
   *                                                                    detected topics in addition to those submitted
   *                                                                    using the `custom_topic` param
   * @param intents            Recognizes speaker intent throughout a
   *                                                                    transcript or text
   * @param customIntent       Custom intents you want the model to detect
   *                                                                    within your input audio if present
   * @param customIntentMode   Sets how the model will interpret intents
   *                                                                    submitted to the `custom_intent` param. When
   *                                                                    `strict`, the model will only return intents
   *                                                                    submitted using the `custom_intent` param. When
   *                                                                    `extended`, the model will return its own
   *                                                                    detected intents in the `custom_intent` param.
   * @param language           The [BCP-47 language tag](https://tools.ietf.
   *                                                                    org/html/bcp47) that hints at the primary
   *                                                                    spoken language. Depending on the Model and API
   *                                                                    endpoint you choose only certain languages are
   *                                                                    available
   * @param body               Analyze a text file
   * @return Response from the API call
   */
  async analyze(
    authorization: string,
    callback?: string,
    callbackMethod?: V1ListenPostParametersCallbackMethod,
    sentiment?: boolean,
    summarize?: V1ReadPostParametersSummarize,
    tag?: V1ReadPostParametersTag,
    topics?: boolean,
    customTopic?: V1ReadPostParametersCustomTopic,
    customTopicMode?: V1ListenPostParametersCustomTopicMode,
    intents?: boolean,
    customIntent?: V1ReadPostParametersCustomIntent,
    customIntentMode?: V1ListenPostParametersCustomTopicMode,
    language?: string,
    body?: ReadV1Request,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ReadV1Response>> {
    const req = this.createRequest('POST', '/v1/read');
    const mapped = req.prepareArgs({
      authorization: [authorization, string()],
      callback: [callback, optional(string())],
      callbackMethod: [
        callbackMethod,
        optional(v1ListenPostParametersCallbackMethodSchema),
      ],
      sentiment: [sentiment, optional(boolean())],
      summarize: [summarize, optional(v1ReadPostParametersSummarizeSchema)],
      tag: [tag, optional(v1ReadPostParametersTagSchema)],
      topics: [topics, optional(boolean())],
      customTopic: [
        customTopic,
        optional(v1ReadPostParametersCustomTopicSchema),
      ],
      customTopicMode: [
        customTopicMode,
        optional(v1ListenPostParametersCustomTopicModeSchema),
      ],
      intents: [intents, optional(boolean())],
      customIntent: [
        customIntent,
        optional(v1ReadPostParametersCustomIntentSchema),
      ],
      customIntentMode: [
        customIntentMode,
        optional(v1ListenPostParametersCustomTopicModeSchema),
      ],
      language: [language, optional(string())],
      body: [body, optional(readV1RequestSchema)],
    });
    req.header('Authorization', mapped.authorization);
    req.header('Content-Type', 'application/json');
    req.query('callback', mapped.callback);
    req.query('callback_method', mapped.callbackMethod);
    req.query('sentiment', mapped.sentiment);
    req.query('summarize', mapped.summarize);
    req.query('tag', mapped.tag);
    req.query('topics', mapped.topics);
    req.query('custom_topic', mapped.customTopic);
    req.query('custom_topic_mode', mapped.customTopicMode);
    req.query('intents', mapped.intents);
    req.query('custom_intent', mapped.customIntent);
    req.query('custom_intent_mode', mapped.customIntentMode);
    req.query('language', mapped.language);
    req.json(mapped.body);
    req.throwOn(400, ApiError, 'Invalid Request');
    req.authenticate([]);
    return req.callAsJson(readV1ResponseSchema, requestOptions);
  }
}
