/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  CreateProjectDistributionCredentialsV1Request,
  createProjectDistributionCredentialsV1RequestSchema,
} from '../models/createProjectDistributionCredentialsV1Request.js';
import {
  CreateProjectDistributionCredentialsV1Response,
  createProjectDistributionCredentialsV1ResponseSchema,
} from '../models/createProjectDistributionCredentialsV1Response.js';
import {
  GetProjectDistributionCredentialsV1Response,
  getProjectDistributionCredentialsV1ResponseSchema,
} from '../models/getProjectDistributionCredentialsV1Response.js';
import {
  ListProjectDistributionCredentialsV1Response,
  listProjectDistributionCredentialsV1ResponseSchema,
} from '../models/listProjectDistributionCredentialsV1Response.js';
import {
  V1ProjectsProjectIdSelfHostedDistributionCredentialsPostParametersProvider,
  v1ProjectsProjectIdSelfHostedDistributionCredentialsPostParametersProviderSchema,
} from '../models/v1ProjectsProjectIdSelfHostedDistributionCredentialsPostParametersProvider.js';
import {
  V1ProjectsProjectIdSelfHostedDistributionCredentialsPostParametersScopesSchemaItems,
  v1ProjectsProjectIdSelfHostedDistributionCredentialsPostParametersScopesSchemaItemsSchema,
} from '../models/v1ProjectsProjectIdSelfHostedDistributionCredentialsPostParametersScopesSchemaItems.js';
import { array, optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { ApiError } from '@apimatic/core';

export class SelfHostedV1DistributionCredentialsApi extends BaseApi {
  /**
   * Lists sets of distribution credentials for the specified project
   *
   * @param projectId     The unique identifier of the project
   * @param authorization Use `Authorization: Token <API_KEY>` Example: `Authorization: Token 12345abcdef`
   * @return Response from the API call
   */
  async list(
    projectId: string,
    authorization: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ListProjectDistributionCredentialsV1Response>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      projectId: [projectId, string()],
      authorization: [authorization, string()],
    });
    req.header('Authorization', mapped.authorization);
    req.appendTemplatePath`/v1/projects/${mapped.projectId}/self-hosted/distribution/credentials`;
    req.throwOn(400, ApiError, 'Invalid Request');
    req.authenticate([]);
    return req.callAsJson(
      listProjectDistributionCredentialsV1ResponseSchema,
      requestOptions
    );
  }

  /**
   * Creates a set of distribution credentials for the specified project
   *
   * @param projectId     The
   *                                                                                                               uniq
   *                                                                                                               ue
   *                                                                                                               iden
   *                                                                                                               tifi
   *                                                                                                               er
   *                                                                                                               of
   *                                                                                                               the
   *                                                                                                               proj
   *                                                                                                               ect
   * @param authorization Use
   *                                                                                                               `Aut
   *                                                                                                               hori
   *                                                                                                               zati
   *                                                                                                               on:
   *                                                                                                               Toke
   *                                                                                                               n
   *                                                                                                               <API
   *                                                                                                               _KEY
   *                                                                                                               >`
   *                                                                                                               Exam
   *                                                                                                               ple:
   *                                                                                                               `Aut
   *                                                                                                               hori
   *                                                                                                               zati
   *                                                                                                               on:
   *                                                                                                               Toke
   *                                                                                                               n
   *                                                                                                               1234
   *                                                                                                               5abc
   *                                                                                                               def`
   * @param scopes        
   *                                                                                                               List
   *                                                                                                               of
   *                                                                                                               perm
   *                                                                                                               issi
   *                                                                                                               on
   *                                                                                                               scop
   *                                                                                                               es
   *                                                                                                               for
   *                                                                                                               the
   *                                                                                                               cred
   *                                                                                                               enti
   *                                                                                                               als
   * @param provider      The
   *                                                                                                               prov
   *                                                                                                               ider
   *                                                                                                               of
   *                                                                                                               the
   *                                                                                                               dist
   *                                                                                                               ribu
   *                                                                                                               tion
   *                                                                                                               serv
   *                                                                                                               ice
   * @param body          The
   *                                                                                                               set
   *                                                                                                               of
   *                                                                                                               dist
   *                                                                                                               ribu
   *                                                                                                               tion
   *                                                                                                               cred
   *                                                                                                               enti
   *                                                                                                               als
   *                                                                                                               to
   *                                                                                                               crea
   *                                                                                                               te
   * @return Response from the API call
   */
  async create(
    projectId: string,
    authorization: string,
    scopes?: V1ProjectsProjectIdSelfHostedDistributionCredentialsPostParametersScopesSchemaItems[],
    provider?: V1ProjectsProjectIdSelfHostedDistributionCredentialsPostParametersProvider,
    body?: CreateProjectDistributionCredentialsV1Request,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<CreateProjectDistributionCredentialsV1Response>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({
      projectId: [projectId, string()],
      authorization: [authorization, string()],
      scopes: [
        scopes,
        optional(
          array(
            v1ProjectsProjectIdSelfHostedDistributionCredentialsPostParametersScopesSchemaItemsSchema
          )
        ),
      ],
      provider: [
        provider,
        optional(
          v1ProjectsProjectIdSelfHostedDistributionCredentialsPostParametersProviderSchema
        ),
      ],
      body: [
        body,
        optional(createProjectDistributionCredentialsV1RequestSchema),
      ],
    });
    req.header('Authorization', mapped.authorization);
    req.header('Content-Type', 'application/json');
    req.query('scopes', mapped.scopes);
    req.query('provider', mapped.provider);
    req.json(mapped.body);
    req.appendTemplatePath`/v1/projects/${mapped.projectId}/self-hosted/distribution/credentials`;
    req.throwOn(400, ApiError, 'Invalid Request');
    req.authenticate([]);
    return req.callAsJson(
      createProjectDistributionCredentialsV1ResponseSchema,
      requestOptions
    );
  }

  /**
   * Returns a set of distribution credentials for the specified project
   *
   * @param projectId                   The unique identifier of the project
   * @param distributionCredentialsId   The UUID of the distribution credentials
   * @param authorization               Use `Authorization: Token <API_KEY>` Example: `Authorization: Token
   *                                              12345abcdef`
   * @return Response from the API call
   */
  async get(
    projectId: string,
    distributionCredentialsId: string,
    authorization: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<GetProjectDistributionCredentialsV1Response>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      projectId: [projectId, string()],
      distributionCredentialsId: [distributionCredentialsId, string()],
      authorization: [authorization, string()],
    });
    req.header('Authorization', mapped.authorization);
    req.appendTemplatePath`/v1/projects/${mapped.projectId}/self-hosted/distribution/credentials/${mapped.distributionCredentialsId}`;
    req.throwOn(400, ApiError, 'Invalid Request');
    req.authenticate([]);
    return req.callAsJson(
      getProjectDistributionCredentialsV1ResponseSchema,
      requestOptions
    );
  }

  /**
   * Deletes a set of distribution credentials for the specified project
   *
   * @param projectId                   The unique identifier of the project
   * @param distributionCredentialsId   The UUID of the distribution credentials
   * @param authorization               Use `Authorization: Token <API_KEY>` Example: `Authorization: Token
   *                                              12345abcdef`
   * @return Response from the API call
   */
  async mDelete(
    projectId: string,
    distributionCredentialsId: string,
    authorization: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<GetProjectDistributionCredentialsV1Response>> {
    const req = this.createRequest('DELETE');
    const mapped = req.prepareArgs({
      projectId: [projectId, string()],
      distributionCredentialsId: [distributionCredentialsId, string()],
      authorization: [authorization, string()],
    });
    req.header('Authorization', mapped.authorization);
    req.appendTemplatePath`/v1/projects/${mapped.projectId}/self-hosted/distribution/credentials/${mapped.distributionCredentialsId}`;
    req.throwOn(400, ApiError, 'Invalid Request');
    req.authenticate([]);
    return req.callAsJson(
      getProjectDistributionCredentialsV1ResponseSchema,
      requestOptions
    );
  }
}
