/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  CreateProjectDistributionCredentialsV1Request,
  createProjectDistributionCredentialsV1RequestSchema,
} from '../models/createProjectDistributionCredentialsV1Request.js';
import {
  CreateProjectDistributionCredentialsV1Response,
  createProjectDistributionCredentialsV1ResponseSchema,
} from '../models/createProjectDistributionCredentialsV1Response.js';
import {
  GetProjectDistributionCredentialsV1Response,
  getProjectDistributionCredentialsV1ResponseSchema,
} from '../models/getProjectDistributionCredentialsV1Response.js';
import {
  ListProjectDistributionCredentialsV1Response,
  listProjectDistributionCredentialsV1ResponseSchema,
} from '../models/listProjectDistributionCredentialsV1Response.js';
import {
  V1ProjectsProjectIdSelfHostedDistributionCredentialsPostParametersProvider,
  v1ProjectsProjectIdSelfHostedDistributionCredentialsPostParametersProviderSchema,
} from '../models/v1ProjectsProjectIdSelfHostedDistributionCredentialsPostParametersProvider.js';
import {
  V1ProjectsProjectIdSelfHostedDistributionCredentialsPostParametersScopesSchemaItems,
  v1ProjectsProjectIdSelfHostedDistributionCredentialsPostParametersScopesSchemaItemsSchema,
} from '../models/v1ProjectsProjectIdSelfHostedDistributionCredentialsPostParametersScopesSchemaItems.js';
import { array, optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { ApiError } from '@apimatic/core';

export class SelfHostedV1DistributionCredentialsApi extends BaseApi {
  /**
   * Lists sets of distribution credentials for the specified project
   *
   * @param projectId  The unique identifier of the project
   * @return Response from the API call
   */
  async list(
    projectId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ListProjectDistributionCredentialsV1Response>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ projectId: [projectId, string()] });
    req.appendTemplatePath`/v1/projects/${mapped.projectId}/self-hosted/distribution/credentials`;
    req.throwOn(400, ApiError, 'Invalid Request');
    req.authenticate([{ apiKeyAuth: true }]);
    return req.callAsJson(
      listProjectDistributionCredentialsV1ResponseSchema,
      requestOptions
    );
  }

  /**
   * Creates a set of distribution credentials for the specified project
   *
   * @param projectId    The
   *                                                                                                              uniqu
   *                                                                                                              e
   *                                                                                                              ident
   *                                                                                                              ifier
   *                                                                                                              of
   *                                                                                                              the
   *                                                                                                              proje
   *                                                                                                              ct
   * @param scopes       List
   *                                                                                                              of
   *                                                                                                              permi
   *                                                                                                              ssion
   *                                                                                                              scope
   *                                                                                                              s for
   *                                                                                                              the
   *                                                                                                              crede
   *                                                                                                              ntial
   *                                                                                                              s
   * @param provider     The
   *                                                                                                              provi
   *                                                                                                              der
   *                                                                                                              of
   *                                                                                                              the
   *                                                                                                              distr
   *                                                                                                              ibuti
   *                                                                                                              on
   *                                                                                                              servi
   *                                                                                                              ce
   * @param body         The
   *                                                                                                              set
   *                                                                                                              of
   *                                                                                                              distr
   *                                                                                                              ibuti
   *                                                                                                              on
   *                                                                                                              crede
   *                                                                                                              ntial
   *                                                                                                              s to
   *                                                                                                              creat
   *                                                                                                              e
   * @return Response from the API call
   */
  async create(
    projectId: string,
    scopes?: V1ProjectsProjectIdSelfHostedDistributionCredentialsPostParametersScopesSchemaItems[],
    provider?: V1ProjectsProjectIdSelfHostedDistributionCredentialsPostParametersProvider,
    body?: CreateProjectDistributionCredentialsV1Request,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<CreateProjectDistributionCredentialsV1Response>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({
      projectId: [projectId, string()],
      scopes: [
        scopes,
        optional(
          array(
            v1ProjectsProjectIdSelfHostedDistributionCredentialsPostParametersScopesSchemaItemsSchema
          )
        ),
      ],
      provider: [
        provider,
        optional(
          v1ProjectsProjectIdSelfHostedDistributionCredentialsPostParametersProviderSchema
        ),
      ],
      body: [
        body,
        optional(createProjectDistributionCredentialsV1RequestSchema),
      ],
    });
    req.header('Content-Type', 'application/json');
    req.query('scopes', mapped.scopes);
    req.query('provider', mapped.provider);
    req.json(mapped.body);
    req.appendTemplatePath`/v1/projects/${mapped.projectId}/self-hosted/distribution/credentials`;
    req.throwOn(400, ApiError, 'Invalid Request');
    req.authenticate([{ apiKeyAuth: true }]);
    return req.callAsJson(
      createProjectDistributionCredentialsV1ResponseSchema,
      requestOptions
    );
  }

  /**
   * Returns a set of distribution credentials for the specified project
   *
   * @param projectId                   The unique identifier of the project
   * @param distributionCredentialsId   The UUID of the distribution credentials
   * @return Response from the API call
   */
  async get(
    projectId: string,
    distributionCredentialsId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<GetProjectDistributionCredentialsV1Response>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      projectId: [projectId, string()],
      distributionCredentialsId: [distributionCredentialsId, string()],
    });
    req.appendTemplatePath`/v1/projects/${mapped.projectId}/self-hosted/distribution/credentials/${mapped.distributionCredentialsId}`;
    req.throwOn(400, ApiError, 'Invalid Request');
    req.authenticate([{ apiKeyAuth: true }]);
    return req.callAsJson(
      getProjectDistributionCredentialsV1ResponseSchema,
      requestOptions
    );
  }

  /**
   * Deletes a set of distribution credentials for the specified project
   *
   * @param projectId                   The unique identifier of the project
   * @param distributionCredentialsId   The UUID of the distribution credentials
   * @return Response from the API call
   */
  async mDelete(
    projectId: string,
    distributionCredentialsId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<GetProjectDistributionCredentialsV1Response>> {
    const req = this.createRequest('DELETE');
    const mapped = req.prepareArgs({
      projectId: [projectId, string()],
      distributionCredentialsId: [distributionCredentialsId, string()],
    });
    req.appendTemplatePath`/v1/projects/${mapped.projectId}/self-hosted/distribution/credentials/${mapped.distributionCredentialsId}`;
    req.throwOn(400, ApiError, 'Invalid Request');
    req.authenticate([{ apiKeyAuth: true }]);
    return req.callAsJson(
      getProjectDistributionCredentialsV1ResponseSchema,
      requestOptions
    );
  }
}
