/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  GenerateBitRate2,
  generateBitRate2Schema,
} from '../models/containers/generateBitRate2.js';
import {
  GenerateContainer2,
  generateContainer2Schema,
} from '../models/containers/generateContainer2.js';
import {
  GenerateEncoding2,
  generateEncoding2Schema,
} from '../models/containers/generateEncoding2.js';
import {
  GenerateSampleRate2,
  generateSampleRate2Schema,
} from '../models/containers/generateSampleRate2.js';
import {
  V2SpeakPostParametersTag,
  v2SpeakPostParametersTagSchema,
} from '../models/containers/v2SpeakPostParametersTag.js';
import {
  SpeakV2AcceptedResponse,
  speakV2AcceptedResponseSchema,
} from '../models/speakV2AcceptedResponse.js';
import {
  SpeakV2Request,
  speakV2RequestSchema,
} from '../models/speakV2Request.js';
import {
  V1ListenPostParametersCallbackMethod,
  v1ListenPostParametersCallbackMethodSchema,
} from '../models/v1ListenPostParametersCallbackMethod.js';
import {
  V2SpeakPostParametersPriority,
  v2SpeakPostParametersPrioritySchema,
} from '../models/v2SpeakPostParametersPriority.js';
import { boolean, optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { ApiError } from '@apimatic/core';

export class SpeakV2AudioApi extends BaseApi {
  /**
   * Synthesize a complete block of text into a single audio response using Deepgram's Flux TTS batch
   * (REST) API. Use this for pre-rendering fixed audio (IVR prompts, notifications, narration) where the
   * whole text is known up front and you don't need incremental playback or interruption.
   *
   * @param model           Flux TTS model used to synthesize the submitted
   *                                                                text, in the form `flux-{voice}-{language}` (for
   *                                                                example, `flux-alexis-en`). Required; unlike the v1
   *                                                                (Aura) endpoint there is no default and only flux
   *                                                                models are accepted. English-only at launch.
   * @param authorization   Use `Authorization: Token <API_KEY>` Example:
   *                                                                `Authorization: Token 12345abcdef`
   * @param callback        URL to which we'll make the callback request
   * @param callbackMethod  HTTP method by which the callback request will be
   *                                                                made
   * @param mipOptOut       Opts out requests from the Deepgram Model
   *                                                                Improvement Program. Refer to our Docs for pricing
   *                                                                impacts before setting this to true. https://dpgr.
   *                                                                am/deepgram-mip
   * @param tag             Label your requests for the purpose of
   *                                                                identification during usage reporting
   * @param bitRate         The bitrate of the audio in bits per second.
   *                                                                Choose from predefined ranges or specific values
   *                                                                based on the encoding type.
   * @param container       Container specifies the file format wrapper for
   *                                                                the output audio. The available options depend on
   *                                                                the encoding type.
   * @param encoding        Encoding allows you to specify the expected
   *                                                                encoding of your audio output
   * @param sampleRate      Sample Rate specifies the sample rate for the
   *                                                                output audio. Based on the encoding, different
   *                                                                sample rates are supported. For some encodings, the
   *                                                                sample rate is not configurable
   * @param priority        Processing priority for asynchronous (callback)
   *                                                                requests. The only supported value is low.
   * @param body            Transform text to speech
   * @return Response from the API call
   */
  async generate(
    model: string,
    authorization: string,
    callback?: string,
    callbackMethod?: V1ListenPostParametersCallbackMethod,
    mipOptOut?: boolean,
    tag?: V2SpeakPostParametersTag,
    bitRate?: GenerateBitRate2,
    container?: GenerateContainer2,
    encoding?: GenerateEncoding2,
    sampleRate?: GenerateSampleRate2,
    priority?: V2SpeakPostParametersPriority,
    body?: SpeakV2Request,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<SpeakV2AcceptedResponse>> {
    const req = this.createRequest('POST', '/v2/speak');
    const mapped = req.prepareArgs({
      model: [model, string()],
      authorization: [authorization, string()],
      callback: [callback, optional(string())],
      callbackMethod: [
        callbackMethod,
        optional(v1ListenPostParametersCallbackMethodSchema),
      ],
      mipOptOut: [mipOptOut, optional(boolean())],
      tag: [tag, optional(v2SpeakPostParametersTagSchema)],
      bitRate: [bitRate, optional(generateBitRate2Schema)],
      container: [container, optional(generateContainer2Schema)],
      encoding: [encoding, optional(generateEncoding2Schema)],
      sampleRate: [sampleRate, optional(generateSampleRate2Schema)],
      priority: [priority, optional(v2SpeakPostParametersPrioritySchema)],
      body: [body, optional(speakV2RequestSchema)],
    });
    req.header('Authorization', mapped.authorization);
    req.header('Content-Type', 'application/json');
    req.query('model', mapped.model);
    req.query('callback', mapped.callback);
    req.query('callback_method', mapped.callbackMethod);
    req.query('mip_opt_out', mapped.mipOptOut);
    req.query('tag', mapped.tag);
    req.query('bit_rate', mapped.bitRate);
    req.query('container', mapped.container);
    req.query('encoding', mapped.encoding);
    req.query('sample_rate', mapped.sampleRate);
    req.query('priority', mapped.priority);
    req.json(mapped.body);
    req.throwOn(400, ApiError, 'Invalid Request');
    req.authenticate([]);
    return req.callAsJson(speakV2AcceptedResponseSchema, requestOptions);
  }
}
