/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  GenerateBitRate,
  generateBitRateSchema,
} from '../models/containers/generateBitRate.js';
import {
  GenerateContainer,
  generateContainerSchema,
} from '../models/containers/generateContainer.js';
import {
  GenerateEncoding,
  generateEncodingSchema,
} from '../models/containers/generateEncoding.js';
import {
  GenerateSampleRate,
  generateSampleRateSchema,
} from '../models/containers/generateSampleRate.js';
import {
  V1SpeakPostParametersTag,
  v1SpeakPostParametersTagSchema,
} from '../models/containers/v1SpeakPostParametersTag.js';
import {
  SpeakV1Request,
  speakV1RequestSchema,
} from '../models/speakV1Request.js';
import {
  V1ListenPostParametersCallbackMethod,
  v1ListenPostParametersCallbackMethodSchema,
} from '../models/v1ListenPostParametersCallbackMethod.js';
import {
  V1SpeakPostParametersModel,
  v1SpeakPostParametersModelSchema,
} from '../models/v1SpeakPostParametersModel.js';
import { boolean, number, optional, string, unknown } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { ApiError } from '@apimatic/core';

export class SpeakV1AudioApi extends BaseApi {
  /**
   * Convert text into natural-sounding speech using Deepgram's TTS REST API
   *
   * @param authorization   Use `Authorization: Token <API_KEY>` Example:
   *                                                                `Authorization: Token 12345abcdef`
   * @param callback        URL to which we'll make the callback request
   * @param callbackMethod  HTTP method by which the callback request will be
   *                                                                made
   * @param mipOptOut       Opts out requests from the Deepgram Model
   *                                                                Improvement Program. Refer to our Docs for pricing
   *                                                                impacts before setting this to true. https://dpgr.
   *                                                                am/deepgram-mip
   * @param tag             Label your requests for the purpose of
   *                                                                identification during usage reporting
   * @param bitRate         The bitrate of the audio in bits per second.
   *                                                                Choose from predefined ranges or specific values
   *                                                                based on the encoding type.
   * @param container       Container specifies the file format wrapper for
   *                                                                the output audio. The available options depend on
   *                                                                the encoding type.
   * @param encoding        Encoding allows you to specify the expected
   *                                                                encoding of your audio output
   * @param model           AI model used to process submitted text
   * @param sampleRate      Sample Rate specifies the sample rate for the
   *                                                                output audio. Based on the encoding, different
   *                                                                sample rates are supported. For some encodings, the
   *                                                                sample rate is not configurable
   * @param speed           Speaking rate multiplier that adjusts the pace of
   *                                                                generated speech while preserving natural prosody
   *                                                                and voice quality. Not yet supported in all
   *                                                                languages.
   * @param body            Transform text to speech
   * @return Response from the API call
   */
  async generate(
    authorization: string,
    callback?: string,
    callbackMethod?: V1ListenPostParametersCallbackMethod,
    mipOptOut?: boolean,
    tag?: V1SpeakPostParametersTag,
    bitRate?: GenerateBitRate,
    container?: GenerateContainer,
    encoding?: GenerateEncoding,
    model?: V1SpeakPostParametersModel,
    sampleRate?: GenerateSampleRate,
    speed?: number,
    body?: SpeakV1Request,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<unknown | undefined>> {
    const req = this.createRequest('POST', '/v1/speak');
    const mapped = req.prepareArgs({
      authorization: [authorization, string()],
      callback: [callback, optional(string())],
      callbackMethod: [
        callbackMethod,
        optional(v1ListenPostParametersCallbackMethodSchema),
      ],
      mipOptOut: [mipOptOut, optional(boolean())],
      tag: [tag, optional(v1SpeakPostParametersTagSchema)],
      bitRate: [bitRate, optional(generateBitRateSchema)],
      container: [container, optional(generateContainerSchema)],
      encoding: [encoding, optional(generateEncodingSchema)],
      model: [model, optional(v1SpeakPostParametersModelSchema)],
      sampleRate: [sampleRate, optional(generateSampleRateSchema)],
      speed: [speed, optional(number())],
      body: [body, optional(speakV1RequestSchema)],
    });
    req.header('Authorization', mapped.authorization);
    req.header('Content-Type', 'application/json');
    req.query('callback', mapped.callback);
    req.query('callback_method', mapped.callbackMethod);
    req.query('mip_opt_out', mapped.mipOptOut);
    req.query('tag', mapped.tag);
    req.query('bit_rate', mapped.bitRate);
    req.query('container', mapped.container);
    req.query('encoding', mapped.encoding);
    req.query('model', mapped.model);
    req.query('sample_rate', mapped.sampleRate);
    req.query('speed', mapped.speed);
    req.json(mapped.body);
    req.throwOn(400, ApiError, 'Invalid Request');
    req.authenticate([]);
    return req.callAsJson(optional(unknown()), requestOptions);
  }
}
