/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  AgentVariableV1,
  agentVariableV1Schema,
} from '../models/agentVariableV1.js';
import {
  CreateAgentVariableV1Request,
  createAgentVariableV1RequestSchema,
} from '../models/createAgentVariableV1Request.js';
import {
  ListAgentVariablesV1Response,
  listAgentVariablesV1ResponseSchema,
} from '../models/listAgentVariablesV1Response.js';
import {
  UpdateAgentVariableV1Request,
  updateAgentVariableV1RequestSchema,
} from '../models/updateAgentVariableV1Request.js';
import { optional, string, unknown } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { ApiError } from '@apimatic/core';

export class VoiceAgentVariablesApi extends BaseApi {
  /**
   * Creates a new template variable. Variables follow the `DG_<VARIABLE_NAME>` naming format and can
   * substitute any JSON value in an agent configuration.
   *
   * @param projectId     The unique identifier of the project
   * @param authorization Use `Authorization: Token <API_KEY>` Example:
   *                                                             `Authorization: Token 12345abcdef`
   * @param body          Agent variable details
   * @return Response from the API call
   */
  async create(
    projectId: string,
    authorization: string,
    body?: CreateAgentVariableV1Request,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<AgentVariableV1>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({
      projectId: [projectId, string()],
      authorization: [authorization, string()],
      body: [body, optional(createAgentVariableV1RequestSchema)],
    });
    req.header('Authorization', mapped.authorization);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/v1/projects/${mapped.projectId}/agent-variables`;
    req.throwOn(400, ApiError, 'Invalid Request');
    req.authenticate([]);
    return req.callAsJson(agentVariableV1Schema, requestOptions);
  }

  /**
   * Returns all template variables for the specified project
   *
   * @param projectId     The unique identifier of the project
   * @param authorization Use `Authorization: Token <API_KEY>` Example: `Authorization: Token 12345abcdef`
   * @return Response from the API call
   */
  async list(
    projectId: string,
    authorization: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ListAgentVariablesV1Response>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      projectId: [projectId, string()],
      authorization: [authorization, string()],
    });
    req.header('Authorization', mapped.authorization);
    req.appendTemplatePath`/v1/projects/${mapped.projectId}/agent-variables`;
    req.throwOn(400, ApiError, 'Invalid Request');
    req.authenticate([]);
    return req.callAsJson(listAgentVariablesV1ResponseSchema, requestOptions);
  }

  /**
   * Returns the specified template variable
   *
   * @param projectId     The unique identifier of the project
   * @param variableId    The unique identifier of the agent variable
   * @param authorization Use `Authorization: Token <API_KEY>` Example: `Authorization: Token 12345abcdef`
   * @return Response from the API call
   */
  async get(
    projectId: string,
    variableId: string,
    authorization: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<AgentVariableV1>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      projectId: [projectId, string()],
      variableId: [variableId, string()],
      authorization: [authorization, string()],
    });
    req.header('Authorization', mapped.authorization);
    req.appendTemplatePath`/v1/projects/${mapped.projectId}/agent-variables/${mapped.variableId}`;
    req.throwOn(400, ApiError, 'Invalid Request');
    req.authenticate([]);
    return req.callAsJson(agentVariableV1Schema, requestOptions);
  }

  /**
   * Updates the value of an existing template variable
   *
   * @param projectId     The unique identifier of the project
   * @param variableId    The unique identifier of the agent variable
   * @param authorization Use `Authorization: Token <API_KEY>` Example:
   *                                                             `Authorization: Token 12345abcdef`
   * @param body          Updated value for the agent variable
   * @return Response from the API call
   */
  async update(
    projectId: string,
    variableId: string,
    authorization: string,
    body?: UpdateAgentVariableV1Request,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<AgentVariableV1>> {
    const req = this.createRequest('PATCH');
    const mapped = req.prepareArgs({
      projectId: [projectId, string()],
      variableId: [variableId, string()],
      authorization: [authorization, string()],
      body: [body, optional(updateAgentVariableV1RequestSchema)],
    });
    req.header('Authorization', mapped.authorization);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/v1/projects/${mapped.projectId}/agent-variables/${mapped.variableId}`;
    req.throwOn(400, ApiError, 'Invalid Request');
    req.authenticate([]);
    return req.callAsJson(agentVariableV1Schema, requestOptions);
  }

  /**
   * Deletes the specified template variable
   *
   * @param projectId     The unique identifier of the project
   * @param variableId    The unique identifier of the agent variable
   * @param authorization Use `Authorization: Token <API_KEY>` Example: `Authorization: Token 12345abcdef`
   * @return Response from the API call
   */
  async mDelete(
    projectId: string,
    variableId: string,
    authorization: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<unknown | undefined>> {
    const req = this.createRequest('DELETE');
    const mapped = req.prepareArgs({
      projectId: [projectId, string()],
      variableId: [variableId, string()],
      authorization: [authorization, string()],
    });
    req.header('Authorization', mapped.authorization);
    req.appendTemplatePath`/v1/projects/${mapped.projectId}/agent-variables/${mapped.variableId}`;
    req.throwOn(400, ApiError, 'Invalid Request');
    req.authenticate([]);
    return req.callAsJson(optional(unknown()), requestOptions);
  }
}
