/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  AgentConfigurationV1,
  agentConfigurationV1Schema,
} from '../models/agentConfigurationV1.js';
import {
  CreateAgentConfigurationV1Request,
  createAgentConfigurationV1RequestSchema,
} from '../models/createAgentConfigurationV1Request.js';
import {
  CreateAgentConfigurationV1Response,
  createAgentConfigurationV1ResponseSchema,
} from '../models/createAgentConfigurationV1Response.js';
import {
  ListAgentConfigurationsV1Response,
  listAgentConfigurationsV1ResponseSchema,
} from '../models/listAgentConfigurationsV1Response.js';
import {
  UpdateAgentMetadataV1Request,
  updateAgentMetadataV1RequestSchema,
} from '../models/updateAgentMetadataV1Request.js';
import { optional, string, unknown } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { ApiError } from '@apimatic/core';

export class VoiceAgentConfigurationsApi extends BaseApi {
  /**
   * Creates a new reusable agent configuration. The `config` field must be a valid JSON string
   * representing the `agent` block of a Settings message. The returned `agent_id` can be passed in place
   * of the full `agent` object in future Settings messages.
   *
   * @param projectId     The unique identifier of the project
   * @param authorization Use `Authorization: Token <API_KEY>` Example:
   *                                                                  `Authorization: Token 12345abcdef`
   * @param body          Agent configuration details
   * @return Response from the API call
   */
  async create(
    projectId: string,
    authorization: string,
    body?: CreateAgentConfigurationV1Request,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<CreateAgentConfigurationV1Response>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({
      projectId: [projectId, string()],
      authorization: [authorization, string()],
      body: [body, optional(createAgentConfigurationV1RequestSchema)],
    });
    req.header('Authorization', mapped.authorization);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/v1/projects/${mapped.projectId}/agents`;
    req.throwOn(400, ApiError, 'Invalid Request');
    req.authenticate([]);
    return req.callAsJson(
      createAgentConfigurationV1ResponseSchema,
      requestOptions
    );
  }

  /**
   * Returns all agent configurations for the specified project. Configurations are returned in their
   * uninterpolated form—template variable placeholders appear as-is rather than with their substituted
   * values.
   *
   * @param projectId     The unique identifier of the project
   * @param authorization Use `Authorization: Token <API_KEY>` Example: `Authorization: Token 12345abcdef`
   * @return Response from the API call
   */
  async list(
    projectId: string,
    authorization: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ListAgentConfigurationsV1Response>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      projectId: [projectId, string()],
      authorization: [authorization, string()],
    });
    req.header('Authorization', mapped.authorization);
    req.appendTemplatePath`/v1/projects/${mapped.projectId}/agents`;
    req.throwOn(400, ApiError, 'Invalid Request');
    req.authenticate([]);
    return req.callAsJson(
      listAgentConfigurationsV1ResponseSchema,
      requestOptions
    );
  }

  /**
   * Returns the specified agent configuration in its uninterpolated form
   *
   * @param projectId     The unique identifier of the project
   * @param agentId       The unique identifier of the agent configuration
   * @param authorization Use `Authorization: Token <API_KEY>` Example: `Authorization: Token 12345abcdef`
   * @return Response from the API call
   */
  async get(
    projectId: string,
    agentId: string,
    authorization: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<AgentConfigurationV1>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      projectId: [projectId, string()],
      agentId: [agentId, string()],
      authorization: [authorization, string()],
    });
    req.header('Authorization', mapped.authorization);
    req.appendTemplatePath`/v1/projects/${mapped.projectId}/agents/${mapped.agentId}`;
    req.throwOn(400, ApiError, 'Invalid Request');
    req.authenticate([]);
    return req.callAsJson(agentConfigurationV1Schema, requestOptions);
  }

  /**
   * Updates the metadata associated with an agent configuration. The config itself is immutable—to
   * change the configuration, delete the existing agent and create a new one.
   *
   * @param projectId     The unique identifier of the project
   * @param agentId       The unique identifier of the agent configuration
   * @param authorization Use `Authorization: Token <API_KEY>` Example:
   *                                                             `Authorization: Token 12345abcdef`
   * @param body          Updated metadata for the agent configuration
   * @return Response from the API call
   */
  async update(
    projectId: string,
    agentId: string,
    authorization: string,
    body?: UpdateAgentMetadataV1Request,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<AgentConfigurationV1>> {
    const req = this.createRequest('PUT');
    const mapped = req.prepareArgs({
      projectId: [projectId, string()],
      agentId: [agentId, string()],
      authorization: [authorization, string()],
      body: [body, optional(updateAgentMetadataV1RequestSchema)],
    });
    req.header('Authorization', mapped.authorization);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/v1/projects/${mapped.projectId}/agents/${mapped.agentId}`;
    req.throwOn(400, ApiError, 'Invalid Request');
    req.authenticate([]);
    return req.callAsJson(agentConfigurationV1Schema, requestOptions);
  }

  /**
   * Deletes the specified agent configuration. Deleting an agent configuration can cause a production
   * outage if your service references this agent UUID. Migrate all active sessions to a new
   * configuration before deleting.
   *
   * @param projectId     The unique identifier of the project
   * @param agentId       The unique identifier of the agent configuration
   * @param authorization Use `Authorization: Token <API_KEY>` Example: `Authorization: Token 12345abcdef`
   * @return Response from the API call
   */
  async mDelete(
    projectId: string,
    agentId: string,
    authorization: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<unknown | undefined>> {
    const req = this.createRequest('DELETE');
    const mapped = req.prepareArgs({
      projectId: [projectId, string()],
      agentId: [agentId, string()],
      authorization: [authorization, string()],
    });
    req.header('Authorization', mapped.authorization);
    req.appendTemplatePath`/v1/projects/${mapped.projectId}/agents/${mapped.agentId}`;
    req.throwOn(400, ApiError, 'Invalid Request');
    req.authenticate([]);
    return req.callAsJson(optional(unknown()), requestOptions);
  }
}
