/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for AgentThinkModelsV1ResponseModelsItemsOneOf2Id
 */
export enum AgentThinkModelsV1ResponseModelsItemsOneOf2Id {
  EnumGemini25Flash = 'gemini-2.5-flash',
  EnumGemini20Flash = 'gemini-2.0-flash',
  EnumGemini20Flashlite = 'gemini-2.0-flash-lite',
}

/**
 * Schema for AgentThinkModelsV1ResponseModelsItemsOneOf2Id
 */
export const agentThinkModelsV1ResponseModelsItemsOneOf2IdSchema: Schema<AgentThinkModelsV1ResponseModelsItemsOneOf2Id> = stringEnum(
  AgentThinkModelsV1ResponseModelsItemsOneOf2Id
);
