/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  AgentThinkModelsV1ResponseModelsItemsOneOf0Id,
  agentThinkModelsV1ResponseModelsItemsOneOf0IdSchema,
} from './agentThinkModelsV1ResponseModelsItemsOneOf0Id.js';

/** OpenAI models */
export interface AgentThinkModelsV1ResponseModelsItems0 {
  /** The unique identifier of the OpenAI model */
  id: AgentThinkModelsV1ResponseModelsItemsOneOf0Id;
  /** The display name of the model */
  name: string;
  /** The provider of the model */
  provider?: unknown;
  additionalProperties?: Record<string, unknown>;
}

export const agentThinkModelsV1ResponseModelsItems0Schema: Schema<AgentThinkModelsV1ResponseModelsItems0> = typedExpandoObject(
  {
    id: ['id', agentThinkModelsV1ResponseModelsItemsOneOf0IdSchema],
    name: ['name', string()],
    provider: ['provider', optional(unknown())],
  },
  'additionalProperties',
  optional(unknown())
);
