/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  AgentThinkModelsV1ResponseModelsItemsOneOf1Id,
  agentThinkModelsV1ResponseModelsItemsOneOf1IdSchema,
} from './agentThinkModelsV1ResponseModelsItemsOneOf1Id.js';

/** Anthropic models */
export interface AgentThinkModelsV1ResponseModelsItems1 {
  /** The unique identifier of the Anthropic model */
  id: AgentThinkModelsV1ResponseModelsItemsOneOf1Id;
  /** The display name of the model */
  name: string;
  /** The provider of the model */
  provider?: unknown;
  additionalProperties?: Record<string, unknown>;
}

export const agentThinkModelsV1ResponseModelsItems1Schema: Schema<AgentThinkModelsV1ResponseModelsItems1> = typedExpandoObject(
  {
    id: ['id', agentThinkModelsV1ResponseModelsItemsOneOf1IdSchema],
    name: ['name', string()],
    provider: ['provider', optional(unknown())],
  },
  'additionalProperties',
  optional(unknown())
);
