/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** AWS Bedrock models (custom models accepted) */
export interface AgentThinkModelsV1ResponseModelsItems4 {
  /** The unique identifier of the AWS Bedrock model (any model string accepted for BYO LLMs) */
  id: string;
  /** The display name of the model */
  name: string;
  /** The provider of the model */
  provider?: unknown;
  additionalProperties?: Record<string, unknown>;
}

export const agentThinkModelsV1ResponseModelsItems4Schema: Schema<AgentThinkModelsV1ResponseModelsItems4> = typedExpandoObject(
  {
    id: ['id', string()],
    name: ['name', string()],
    provider: ['provider', optional(unknown())],
  },
  'additionalProperties',
  optional(unknown())
);
