/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  dict,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** A reusable agent configuration */
export interface AgentConfigurationV1 {
  /** The unique identifier of the agent configuration */
  agentId: string;
  /** The agent configuration object */
  config?: unknown;
  /** A map of arbitrary key-value pairs for labeling or organizing the agent configuration */
  metadata?: Record<string, string>;
  /** Timestamp when the configuration was created */
  createdAt?: string;
  /** Timestamp when the configuration was last updated */
  updatedAt?: string;
  additionalProperties?: Record<string, unknown>;
}

export const agentConfigurationV1Schema: Schema<AgentConfigurationV1> = typedExpandoObject(
  {
    agentId: ['agent_id', string()],
    config: ['config', optional(unknown())],
    metadata: ['metadata', optional(dict(string()))],
    createdAt: ['created_at', optional(string())],
    updatedAt: ['updated_at', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
