/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for AgentThinkModelsV1ResponseModelsItemsOneOf1Id
 */
export enum AgentThinkModelsV1ResponseModelsItemsOneOf1Id {
  Claude35Haikulatest = 'claude-3-5-haiku-latest',
  Claudesonnet420250514 = 'claude-sonnet-4-20250514',
}

/**
 * Schema for AgentThinkModelsV1ResponseModelsItemsOneOf1Id
 */
export const agentThinkModelsV1ResponseModelsItemsOneOf1IdSchema: Schema<AgentThinkModelsV1ResponseModelsItemsOneOf1Id> = stringEnum(
  AgentThinkModelsV1ResponseModelsItemsOneOf1Id
);
