/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  AgentThinkModelsV1ResponseModelsItems,
  agentThinkModelsV1ResponseModelsItemsSchema,
} from './containers/agentThinkModelsV1ResponseModelsItems.js';

export interface AgentThinkModelsV1Response {
  models: AgentThinkModelsV1ResponseModelsItems[];
  additionalProperties?: Record<string, unknown>;
}

export const agentThinkModelsV1ResponseSchema: Schema<AgentThinkModelsV1Response> = lazy(
  () =>
    typedExpandoObject(
      {
        models: ['models', array(agentThinkModelsV1ResponseModelsItemsSchema)],
      },
      'additionalProperties',
      optional(unknown())
    )
);
