/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  AgentThinkModelsV1ResponseModelsItemsOneOf3Id,
  agentThinkModelsV1ResponseModelsItemsOneOf3IdSchema,
} from './agentThinkModelsV1ResponseModelsItemsOneOf3Id.js';

/** Groq models */
export interface AgentThinkModelsV1ResponseModelsItems3 {
  /** The unique identifier of the Groq model */
  id: AgentThinkModelsV1ResponseModelsItemsOneOf3Id;
  /** The display name of the model */
  name: string;
  /** The provider of the model */
  provider?: unknown;
  additionalProperties?: Record<string, unknown>;
}

export const agentThinkModelsV1ResponseModelsItems3Schema: Schema<AgentThinkModelsV1ResponseModelsItems3> = typedExpandoObject(
  {
    id: ['id', agentThinkModelsV1ResponseModelsItemsOneOf3IdSchema],
    name: ['name', string()],
    provider: ['provider', optional(unknown())],
  },
  'additionalProperties',
  optional(unknown())
);
