/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  AgentThinkModelsV1ResponseModelsItemsOneOf2Id,
  agentThinkModelsV1ResponseModelsItemsOneOf2IdSchema,
} from './agentThinkModelsV1ResponseModelsItemsOneOf2Id.js';

/** Google models */
export interface AgentThinkModelsV1ResponseModelsItems2 {
  /** The unique identifier of the Google model */
  id: AgentThinkModelsV1ResponseModelsItemsOneOf2Id;
  /** The display name of the model */
  name: string;
  /** The provider of the model */
  provider?: unknown;
  additionalProperties?: Record<string, unknown>;
}

export const agentThinkModelsV1ResponseModelsItems2Schema: Schema<AgentThinkModelsV1ResponseModelsItems2> = typedExpandoObject(
  {
    id: ['id', agentThinkModelsV1ResponseModelsItemsOneOf2IdSchema],
    name: ['name', string()],
    provider: ['provider', optional(unknown())],
  },
  'additionalProperties',
  optional(unknown())
);
