/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** A template variable for agent configurations */
export interface AgentVariableV1 {
  /** The unique identifier of the variable */
  variableId: string;
  /** The variable name, following the DG_<VARIABLE_NAME> format */
  key: string;
  /** The value to substitute. Can be any valid JSON type */
  value?: unknown;
  /** Timestamp when the variable was created */
  createdAt?: string;
  /** Timestamp when the variable was last updated */
  updatedAt?: string;
  additionalProperties?: Record<string, unknown>;
}

export const agentVariableV1Schema: Schema<AgentVariableV1> = typedExpandoObject(
  {
    variableId: ['variable_id', string()],
    key: ['key', string()],
    value: ['value', optional(unknown())],
    createdAt: ['created_at', optional(string())],
    updatedAt: ['updated_at', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
