/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for AgentThinkModelsV1ResponseModelsItemsOneOf3Id
 */
export enum AgentThinkModelsV1ResponseModelsItemsOneOf3Id {
  EnumOpenaigptoss20B = 'openai/gpt-oss-20b',
}

/**
 * Schema for AgentThinkModelsV1ResponseModelsItemsOneOf3Id
 */
export const agentThinkModelsV1ResponseModelsItemsOneOf3IdSchema: Schema<AgentThinkModelsV1ResponseModelsItemsOneOf3Id> = stringEnum(
  AgentThinkModelsV1ResponseModelsItemsOneOf3Id
);
