/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for AgentThinkModelsV1ResponseModelsItemsOneOf0Id
 */
export enum AgentThinkModelsV1ResponseModelsItemsOneOf0Id {
  Gpt5 = 'gpt-5',
  Gpt5Mini = 'gpt-5-mini',
  Gpt5Nano = 'gpt-5-nano',
  EnumGpt41 = 'gpt-4.1',
  EnumGpt41Mini = 'gpt-4.1-mini',
  EnumGpt41Nano = 'gpt-4.1-nano',
  Gpt4O = 'gpt-4o',
  Gpt4Omini = 'gpt-4o-mini',
}

/**
 * Schema for AgentThinkModelsV1ResponseModelsItemsOneOf0Id
 */
export const agentThinkModelsV1ResponseModelsItemsOneOf0IdSchema: Schema<AgentThinkModelsV1ResponseModelsItemsOneOf0Id> = stringEnum(
  AgentThinkModelsV1ResponseModelsItemsOneOf0Id
);
