/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface BillingBreakdownV1ResponseResolution {
  /** Time unit for the resolution */
  units: string;
  /** Amount of units */
  amount: number;
  additionalProperties?: Record<string, unknown>;
}

export const billingBreakdownV1ResponseResolutionSchema: Schema<BillingBreakdownV1ResponseResolution> = typedExpandoObject(
  { units: ['units', string()], amount: ['amount', number()] },
  'additionalProperties',
  optional(unknown())
);
