/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  BillingBreakdownV1ResponseResultsItemsGrouping,
  billingBreakdownV1ResponseResultsItemsGroupingSchema,
} from './billingBreakdownV1ResponseResultsItemsGrouping.js';

export interface BillingBreakdownV1ResponseResultsItems {
  /** USD cost of the billing for this grouping */
  dollars: number;
  grouping: BillingBreakdownV1ResponseResultsItemsGrouping;
  additionalProperties?: Record<string, unknown>;
}

export const billingBreakdownV1ResponseResultsItemsSchema: Schema<BillingBreakdownV1ResponseResultsItems> = lazy(
  () =>
    typedExpandoObject(
      {
        dollars: ['dollars', number()],
        grouping: [
          'grouping',
          billingBreakdownV1ResponseResultsItemsGroupingSchema,
        ],
      },
      'additionalProperties',
      optional(unknown())
    )
);
