/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface BillingBreakdownV1ResponseResultsItemsGrouping {
  /** Start date for this group */
  start?: string;
  /** End date for this group */
  end?: string;
  /** Optional accessor identifier, null unless grouped by accessor. */
  accessor?: string | null;
  /** Optional deployment identifier, null unless grouped by deployment. */
  deployment?: string | null;
  /** Optional line item identifier, null unless grouped by line item. */
  lineItem?: string | null;
  /** Optional list of tags, null unless grouped by tags. */
  tags?: string[] | null;
  additionalProperties?: Record<string, unknown>;
}

export const billingBreakdownV1ResponseResultsItemsGroupingSchema: Schema<BillingBreakdownV1ResponseResultsItemsGrouping> = typedExpandoObject(
  {
    start: ['start', optional(string())],
    end: ['end', optional(string())],
    accessor: ['accessor', optional(nullable(string()))],
    deployment: ['deployment', optional(nullable(string()))],
    lineItem: ['line_item', optional(nullable(string()))],
    tags: ['tags', optional(nullable(array(string())))],
  },
  'additionalProperties',
  optional(unknown())
);
