/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  BillingBreakdownV1ResponseResolution,
  billingBreakdownV1ResponseResolutionSchema,
} from './billingBreakdownV1ResponseResolution.js';
import {
  BillingBreakdownV1ResponseResultsItems,
  billingBreakdownV1ResponseResultsItemsSchema,
} from './billingBreakdownV1ResponseResultsItems.js';

export interface BillingBreakdownV1Response {
  /** Start date of the billing summmary period */
  start: string;
  /** End date of the billing summary period */
  end: string;
  resolution: BillingBreakdownV1ResponseResolution;
  results: BillingBreakdownV1ResponseResultsItems[];
  additionalProperties?: Record<string, unknown>;
}

export const billingBreakdownV1ResponseSchema: Schema<BillingBreakdownV1Response> = lazy(
  () =>
    typedExpandoObject(
      {
        start: ['start', string()],
        end: ['end', string()],
        resolution: ['resolution', billingBreakdownV1ResponseResolutionSchema],
        results: [
          'results',
          array(billingBreakdownV1ResponseResultsItemsSchema),
        ],
      },
      'additionalProperties',
      optional(unknown())
    )
);
