/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Request body for creating an agent variable */
export interface CreateAgentVariableV1Request {
  /** The variable name, following the DG_<VARIABLE_NAME> format */
  key: string;
  /** The value to substitute. Can be any valid JSON type (string, number, boolean, object, or array) */
  value?: unknown;
  /** API version. Defaults to 1 */
  apiVersion?: number;
  additionalProperties?: Record<string, unknown>;
}

export const createAgentVariableV1RequestSchema: Schema<CreateAgentVariableV1Request> = typedExpandoObject(
  {
    key: ['key', string()],
    value: ['value', optional(unknown())],
    apiVersion: ['api_version', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
