/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface CreateProjectDistributionCredentialsV1ResponseMember {
  /** Unique identifier for the member */
  memberId: string;
  /** Email address of the member */
  email: string;
  additionalProperties?: Record<string, unknown>;
}

export const createProjectDistributionCredentialsV1ResponseMemberSchema: Schema<CreateProjectDistributionCredentialsV1ResponseMember> = typedExpandoObject(
  { memberId: ['member_id', string()], email: ['email', string()] },
  'additionalProperties',
  optional(unknown())
);
