/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** API key created */
export interface CreateKeyV1Response {
  /** The unique identifier of the API key */
  apiKeyId?: string;
  /** The API key */
  key?: string;
  /** A comment for the API key */
  comment?: string;
  /** The scopes for the API key */
  scopes?: string[];
  /** The tags for the API key */
  tags?: string[];
  /** The expiration date of the API key */
  expirationDate?: string;
  additionalProperties?: Record<string, unknown>;
}

export const createKeyV1ResponseSchema: Schema<CreateKeyV1Response> = typedExpandoObject(
  {
    apiKeyId: ['api_key_id', optional(string())],
    key: ['key', optional(string())],
    comment: ['comment', optional(string())],
    scopes: ['scopes', optional(array(string()))],
    tags: ['tags', optional(array(string()))],
    expirationDate: ['expiration_date', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
