/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  CreateProjectDistributionCredentialsV1ResponseDistributionCredentials,
  createProjectDistributionCredentialsV1ResponseDistributionCredentialsSchema,
} from './createProjectDistributionCredentialsV1ResponseDistributionCredentials.js';
import {
  CreateProjectDistributionCredentialsV1ResponseMember,
  createProjectDistributionCredentialsV1ResponseMemberSchema,
} from './createProjectDistributionCredentialsV1ResponseMember.js';

export interface CreateProjectDistributionCredentialsV1Response {
  member: CreateProjectDistributionCredentialsV1ResponseMember;
  distributionCredentials: CreateProjectDistributionCredentialsV1ResponseDistributionCredentials;
  additionalProperties?: Record<string, unknown>;
}

export const createProjectDistributionCredentialsV1ResponseSchema: Schema<CreateProjectDistributionCredentialsV1Response> = lazy(
  () =>
    typedExpandoObject(
      {
        member: [
          'member',
          createProjectDistributionCredentialsV1ResponseMemberSchema,
        ],
        distributionCredentials: [
          'distribution_credentials',
          createProjectDistributionCredentialsV1ResponseDistributionCredentialsSchema,
        ],
      },
      'additionalProperties',
      optional(unknown())
    )
);
