/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Request body for creating distribution credentials */
export interface CreateProjectDistributionCredentialsV1Request {
  /** Optional comment about the credentials */
  comment?: string;
  additionalProperties?: Record<string, unknown>;
}

export const createProjectDistributionCredentialsV1RequestSchema: Schema<CreateProjectDistributionCredentialsV1Request> = typedExpandoObject(
  { comment: ['comment', optional(string())] },
  'additionalProperties',
  optional(unknown())
);
