/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  dict,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface CreateAgentConfigurationV1Response {
  /** The unique identifier of the newly created agent configuration */
  agentId: string;
  /** The parsed agent configuration object */
  config?: unknown;
  /** Metadata associated with the agent configuration */
  metadata?: Record<string, string>;
  additionalProperties?: Record<string, unknown>;
}

export const createAgentConfigurationV1ResponseSchema: Schema<CreateAgentConfigurationV1Response> = typedExpandoObject(
  {
    agentId: ['agent_id', string()],
    config: ['config', optional(unknown())],
    metadata: ['metadata', optional(dict(string()))],
  },
  'additionalProperties',
  optional(unknown())
);
