/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  dict,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Request body for creating an agent configuration */
export interface CreateAgentConfigurationV1Request {
  /** A valid JSON string representing the agent block of a Settings message */
  config: string;
  /** A map of arbitrary key-value pairs for labeling or organizing the agent configuration */
  metadata?: Record<string, string>;
  /** API version. Defaults to 1 */
  apiVersion?: number;
  additionalProperties?: Record<string, unknown>;
}

export const createAgentConfigurationV1RequestSchema: Schema<CreateAgentConfigurationV1Request> = typedExpandoObject(
  {
    config: ['config', string()],
    metadata: ['metadata', optional(dict(string()))],
    apiVersion: ['api_version', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
