/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Request body for creating a project invite */
export interface CreateProjectInviteV1Request {
  /** The email address of the invitee */
  email: string;
  /** The scope of the invitee */
  scope: string;
  additionalProperties?: Record<string, unknown>;
}

export const createProjectInviteV1RequestSchema: Schema<CreateProjectInviteV1Request> = typedExpandoObject(
  { email: ['email', string()], scope: ['scope', string()] },
  'additionalProperties',
  optional(unknown())
);
