/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface DeleteProjectKeyV1Response {
  message?: string;
  additionalProperties?: Record<string, unknown>;
}

export const deleteProjectKeyV1ResponseSchema: Schema<DeleteProjectKeyV1Response> = typedExpandoObject(
  { message: ['message', optional(string())] },
  'additionalProperties',
  optional(unknown())
);
