/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ErrorResponseLegacyError {
  /** The error code */
  errCode?: string;
  /** The error message */
  errMsg?: string;
  /** The request ID */
  requestId?: string;
  additionalProperties?: Record<string, unknown>;
}

export const errorResponseLegacyErrorSchema: Schema<ErrorResponseLegacyError> = typedExpandoObject(
  {
    errCode: ['err_code', optional(string())],
    errMsg: ['err_msg', optional(string())],
    requestId: ['request_id', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
