/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ErrorResponseModernError {
  /** The category of the error */
  category?: string;
  /** A message about the error */
  message?: string;
  /** A description of the error */
  details?: string;
  /** The unique identifier of the request */
  requestId?: string;
  additionalProperties?: Record<string, unknown>;
}

export const errorResponseModernErrorSchema: Schema<ErrorResponseModernError> = typedExpandoObject(
  {
    category: ['category', optional(string())],
    message: ['message', optional(string())],
    details: ['details', optional(string())],
    requestId: ['request_id', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
