/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  GetModelV1ResponseOneOf1Metadata,
  getModelV1ResponseOneOf1MetadataSchema,
} from './getModelV1ResponseOneOf1Metadata.js';

export interface GetModelV1Response1 {
  name?: string;
  canonicalName?: string;
  architecture?: string;
  languages?: string[];
  version?: string;
  uuid?: string;
  metadata?: GetModelV1ResponseOneOf1Metadata;
  additionalProperties?: Record<string, unknown>;
}

export const getModelV1Response1Schema: Schema<GetModelV1Response1> = lazy(() =>
  typedExpandoObject(
    {
      name: ['name', optional(string())],
      canonicalName: ['canonical_name', optional(string())],
      architecture: ['architecture', optional(string())],
      languages: ['languages', optional(array(string()))],
      version: ['version', optional(string())],
      uuid: ['uuid', optional(string())],
      metadata: ['metadata', optional(getModelV1ResponseOneOf1MetadataSchema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
