/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface GetProjectDistributionCredentialsV1ResponseDistributionCredentials {
  /** Unique identifier for the distribution credentials */
  distributionCredentialsId: string;
  /** The provider of the distribution service */
  provider: string;
  /** Optional comment about the credentials */
  comment?: string;
  /** List of permission scopes for the credentials */
  scopes: string[];
  /** Timestamp when the credentials were created */
  created: string;
  additionalProperties?: Record<string, unknown>;
}

export const getProjectDistributionCredentialsV1ResponseDistributionCredentialsSchema: Schema<GetProjectDistributionCredentialsV1ResponseDistributionCredentials> = typedExpandoObject(
  {
    distributionCredentialsId: ['distribution_credentials_id', string()],
    provider: ['provider', string()],
    comment: ['comment', optional(string())],
    scopes: ['scopes', array(string())],
    created: ['created', string()],
  },
  'additionalProperties',
  optional(unknown())
);
