/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  GetProjectKeyV1ResponseItem,
  getProjectKeyV1ResponseItemSchema,
} from './getProjectKeyV1ResponseItem.js';

export interface GetProjectKeyV1Response {
  item?: GetProjectKeyV1ResponseItem;
  additionalProperties?: Record<string, unknown>;
}

export const getProjectKeyV1ResponseSchema: Schema<GetProjectKeyV1Response> = lazy(
  () =>
    typedExpandoObject(
      { item: ['item', optional(getProjectKeyV1ResponseItemSchema)] },
      'additionalProperties',
      optional(unknown())
    )
);
