/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  GetProjectKeyV1ResponseItemMember,
  getProjectKeyV1ResponseItemMemberSchema,
} from './getProjectKeyV1ResponseItemMember.js';

export interface GetProjectKeyV1ResponseItem {
  member?: GetProjectKeyV1ResponseItemMember;
  additionalProperties?: Record<string, unknown>;
}

export const getProjectKeyV1ResponseItemSchema: Schema<GetProjectKeyV1ResponseItem> = lazy(
  () =>
    typedExpandoObject(
      { member: ['member', optional(getProjectKeyV1ResponseItemMemberSchema)] },
      'additionalProperties',
      optional(unknown())
    )
);
