/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface GetProjectV1Response {
  /** The unique identifier of the project */
  projectId?: string;
  /** Model Improvement Program opt-out */
  mipOptOut?: boolean;
  /** The name of the project */
  name?: string;
  additionalProperties?: Record<string, unknown>;
}

export const getProjectV1ResponseSchema: Schema<GetProjectV1Response> = typedExpandoObject(
  {
    projectId: ['project_id', optional(string())],
    mipOptOut: ['mip_opt_out', optional(boolean())],
    name: ['name', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
