/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface GetProjectKeyV1ResponseItemMemberApiKey {
  apiKeyId?: string;
  comment?: string;
  scopes?: string[];
  tags?: string[];
  expirationDate?: string;
  created?: string;
  additionalProperties?: Record<string, unknown>;
}

export const getProjectKeyV1ResponseItemMemberApiKeySchema: Schema<GetProjectKeyV1ResponseItemMemberApiKey> = typedExpandoObject(
  {
    apiKeyId: ['api_key_id', optional(string())],
    comment: ['comment', optional(string())],
    scopes: ['scopes', optional(array(string()))],
    tags: ['tags', optional(array(string()))],
    expirationDate: ['expiration_date', optional(string())],
    created: ['created', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
