/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  GetProjectKeyV1ResponseItemMemberApiKey,
  getProjectKeyV1ResponseItemMemberApiKeySchema,
} from './getProjectKeyV1ResponseItemMemberApiKey.js';

export interface GetProjectKeyV1ResponseItemMember {
  memberId?: string;
  email?: string;
  firstName?: string;
  lastName?: string;
  apiKey?: GetProjectKeyV1ResponseItemMemberApiKey;
  additionalProperties?: Record<string, unknown>;
}

export const getProjectKeyV1ResponseItemMemberSchema: Schema<GetProjectKeyV1ResponseItemMember> = lazy(
  () =>
    typedExpandoObject(
      {
        memberId: ['member_id', optional(string())],
        email: ['email', optional(string())],
        firstName: ['first_name', optional(string())],
        lastName: ['last_name', optional(string())],
        apiKey: [
          'api_key',
          optional(getProjectKeyV1ResponseItemMemberApiKeySchema),
        ],
      },
      'additionalProperties',
      optional(unknown())
    )
);
