/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface GetProjectBalanceV1Response {
  /** The unique identifier of the balance */
  balanceId?: string;
  /** The amount of the balance */
  amount?: number;
  /** The units of the balance, such as "USD" */
  units?: string;
  /** Description or reference of the purchase */
  purchaseOrderId?: string;
  additionalProperties?: Record<string, unknown>;
}

export const getProjectBalanceV1ResponseSchema: Schema<GetProjectBalanceV1Response> = typedExpandoObject(
  {
    balanceId: ['balance_id', optional(string())],
    amount: ['amount', optional(number())],
    units: ['units', optional(string())],
    purchaseOrderId: ['purchase_order_id', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
