/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  GetProjectDistributionCredentialsV1ResponseDistributionCredentials,
  getProjectDistributionCredentialsV1ResponseDistributionCredentialsSchema,
} from './getProjectDistributionCredentialsV1ResponseDistributionCredentials.js';
import {
  GetProjectDistributionCredentialsV1ResponseMember,
  getProjectDistributionCredentialsV1ResponseMemberSchema,
} from './getProjectDistributionCredentialsV1ResponseMember.js';

export interface GetProjectDistributionCredentialsV1Response {
  member: GetProjectDistributionCredentialsV1ResponseMember;
  distributionCredentials: GetProjectDistributionCredentialsV1ResponseDistributionCredentials;
  additionalProperties?: Record<string, unknown>;
}

export const getProjectDistributionCredentialsV1ResponseSchema: Schema<GetProjectDistributionCredentialsV1Response> = lazy(
  () =>
    typedExpandoObject(
      {
        member: [
          'member',
          getProjectDistributionCredentialsV1ResponseMemberSchema,
        ],
        distributionCredentials: [
          'distribution_credentials',
          getProjectDistributionCredentialsV1ResponseDistributionCredentialsSchema,
        ],
      },
      'additionalProperties',
      optional(unknown())
    )
);
