/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ProjectRequestResponse,
  projectRequestResponseSchema,
} from './projectRequestResponse.js';

export interface GetProjectRequestV1Response {
  /** A single request */
  request?: ProjectRequestResponse;
  additionalProperties?: Record<string, unknown>;
}

export const getProjectRequestV1ResponseSchema: Schema<GetProjectRequestV1Response> = lazy(
  () =>
    typedExpandoObject(
      { request: ['request', optional(projectRequestResponseSchema)] },
      'additionalProperties',
      optional(unknown())
    )
);
