/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface GrantV1Request {
  /** Time to live in seconds for the token. Defaults to 30 seconds. */
  ttlSeconds?: number;
  additionalProperties?: Record<string, unknown>;
}

export const grantV1RequestSchema: Schema<GrantV1Request> = typedExpandoObject(
  { ttlSeconds: ['ttl_seconds', optional(number())] },
  'additionalProperties',
  optional(unknown())
);
