/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface GrantV1Response {
  /** JSON Web Token (JWT) */
  accessToken: string;
  /** Time in seconds until the JWT expires */
  expiresIn?: number;
  additionalProperties?: Record<string, unknown>;
}

export const grantV1ResponseSchema: Schema<GrantV1Response> = typedExpandoObject(
  {
    accessToken: ['access_token', string()],
    expiresIn: ['expires_in', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
