/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ListModelsV1ResponseSttModels,
  listModelsV1ResponseSttModelsSchema,
} from './listModelsV1ResponseSttModels.js';
import {
  ListModelsV1ResponseTtsModels,
  listModelsV1ResponseTtsModelsSchema,
} from './listModelsV1ResponseTtsModels.js';

export interface ListModelsV1Response {
  stt?: ListModelsV1ResponseSttModels[];
  tts?: ListModelsV1ResponseTtsModels[];
  additionalProperties?: Record<string, unknown>;
}

export const listModelsV1ResponseSchema: Schema<ListModelsV1Response> = lazy(
  () =>
    typedExpandoObject(
      {
        stt: ['stt', optional(array(listModelsV1ResponseSttModelsSchema))],
        tts: ['tts', optional(array(listModelsV1ResponseTtsModelsSchema))],
      },
      'additionalProperties',
      optional(unknown())
    )
);
