/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ListProjectDistributionCredentialsV1ResponseDistributionCredentialsItems,
  listProjectDistributionCredentialsV1ResponseDistributionCredentialsItemsSchema,
} from './listProjectDistributionCredentialsV1ResponseDistributionCredentialsItems.js';

export interface ListProjectDistributionCredentialsV1Response {
  /** Array of distribution credentials with associated member information */
  distributionCredentials?: ListProjectDistributionCredentialsV1ResponseDistributionCredentialsItems[];
  additionalProperties?: Record<string, unknown>;
}

export const listProjectDistributionCredentialsV1ResponseSchema: Schema<ListProjectDistributionCredentialsV1Response> = lazy(
  () =>
    typedExpandoObject(
      {
        distributionCredentials: [
          'distribution_credentials',
          optional(
            array(
              listProjectDistributionCredentialsV1ResponseDistributionCredentialsItemsSchema
            )
          ),
        ],
      },
      'additionalProperties',
      optional(unknown())
    )
);
