/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ListProjectPurchasesV1ResponseOrdersItems {
  orderId?: string;
  expiration?: string;
  created?: string;
  amount?: number;
  units?: string;
  orderType?: string;
  additionalProperties?: Record<string, unknown>;
}

export const listProjectPurchasesV1ResponseOrdersItemsSchema: Schema<ListProjectPurchasesV1ResponseOrdersItems> = typedExpandoObject(
  {
    orderId: ['order_id', optional(string())],
    expiration: ['expiration', optional(string())],
    created: ['created', optional(string())],
    amount: ['amount', optional(number())],
    units: ['units', optional(string())],
    orderType: ['order_type', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
