/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ListProjectsV1ResponseProjectsItems {
  /** The unique identifier of the project */
  projectId?: string;
  /** The name of the project */
  name?: string;
  additionalProperties?: Record<string, unknown>;
}

export const listProjectsV1ResponseProjectsItemsSchema: Schema<ListProjectsV1ResponseProjectsItems> = typedExpandoObject(
  {
    projectId: ['project_id', optional(string())],
    name: ['name', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
