/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ListProjectDistributionCredentialsV1ResponseDistributionCredentialsItemsDistributionCredentials,
  listProjectDistributionCredentialsV1ResponseDistributionCredentialsItemsDistributionCredentialsSchema,
} from './listProjectDistributionCredentialsV1ResponseDistributionCredentialsItemsDistributionCredentials.js';
import {
  ListProjectDistributionCredentialsV1ResponseDistributionCredentialsItemsMember,
  listProjectDistributionCredentialsV1ResponseDistributionCredentialsItemsMemberSchema,
} from './listProjectDistributionCredentialsV1ResponseDistributionCredentialsItemsMember.js';

export interface ListProjectDistributionCredentialsV1ResponseDistributionCredentialsItems {
  member: ListProjectDistributionCredentialsV1ResponseDistributionCredentialsItemsMember;
  distributionCredentials: ListProjectDistributionCredentialsV1ResponseDistributionCredentialsItemsDistributionCredentials;
  additionalProperties?: Record<string, unknown>;
}

export const listProjectDistributionCredentialsV1ResponseDistributionCredentialsItemsSchema: Schema<ListProjectDistributionCredentialsV1ResponseDistributionCredentialsItems> = lazy(
  () =>
    typedExpandoObject(
      {
        member: [
          'member',
          listProjectDistributionCredentialsV1ResponseDistributionCredentialsItemsMemberSchema,
        ],
        distributionCredentials: [
          'distribution_credentials',
          listProjectDistributionCredentialsV1ResponseDistributionCredentialsItemsDistributionCredentialsSchema,
        ],
      },
      'additionalProperties',
      optional(unknown())
    )
);
