/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ListModelsV1ResponseTtsModelsMetadata {
  accent?: string;
  age?: string;
  color?: string;
  image?: string;
  sample?: string;
  tags?: string[];
  useCases?: string[];
  additionalProperties?: Record<string, unknown>;
}

export const listModelsV1ResponseTtsModelsMetadataSchema: Schema<ListModelsV1ResponseTtsModelsMetadata> = typedExpandoObject(
  {
    accent: ['accent', optional(string())],
    age: ['age', optional(string())],
    color: ['color', optional(string())],
    image: ['image', optional(string())],
    sample: ['sample', optional(string())],
    tags: ['tags', optional(array(string()))],
    useCases: ['use_cases', optional(array(string()))],
  },
  'additionalProperties',
  optional(unknown())
);
