/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Accepted response for asynchronous transcription requests */
export interface ListenV1AcceptedResponse {
  /** Unique identifier for tracking the asynchronous request */
  requestId: string;
  additionalProperties?: Record<string, unknown>;
}

export const listenV1AcceptedResponseSchema: Schema<ListenV1AcceptedResponse> = typedExpandoObject(
  { requestId: ['request_id', string()] },
  'additionalProperties',
  optional(unknown())
);
