/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ListenV1ResponseResultsChannelsItemsAlternativesItemsWordsItems {
  word?: string;
  start?: number;
  end?: number;
  confidence?: number;
  additionalProperties?: Record<string, unknown>;
}

export const listenV1ResponseResultsChannelsItemsAlternativesItemsWordsItemsSchema: Schema<ListenV1ResponseResultsChannelsItemsAlternativesItemsWordsItems> = typedExpandoObject(
  {
    word: ['word', optional(string())],
    start: ['start', optional(number())],
    end: ['end', optional(number())],
    confidence: ['confidence', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
