/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ListProjectMembersV1ResponseMembersItems {
  /** The unique identifier of the member */
  memberId?: string;
  /** The API scopes of the member */
  scopes?: string[];
  email?: string;
  firstName?: string;
  lastName?: string;
  additionalProperties?: Record<string, unknown>;
}

export const listProjectMembersV1ResponseMembersItemsSchema: Schema<ListProjectMembersV1ResponseMembersItems> = typedExpandoObject(
  {
    memberId: ['member_id', optional(string())],
    scopes: ['scopes', optional(array(string()))],
    email: ['email', optional(string())],
    firstName: ['first_name', optional(string())],
    lastName: ['last_name', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
