/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ListenV1ResponseResultsChannelsItemsAlternativesItemsParagraphsParagraphsItemsSentencesItems {
  text?: string;
  start?: number;
  end?: number;
  additionalProperties?: Record<string, unknown>;
}

export const listenV1ResponseResultsChannelsItemsAlternativesItemsParagraphsParagraphsItemsSentencesItemsSchema: Schema<ListenV1ResponseResultsChannelsItemsAlternativesItemsParagraphsParagraphsItemsSentencesItems> = typedExpandoObject(
  {
    text: ['text', optional(string())],
    start: ['start', optional(number())],
    end: ['end', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
