/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ListProjectsV1ResponseProjectsItems,
  listProjectsV1ResponseProjectsItemsSchema,
} from './listProjectsV1ResponseProjectsItems.js';

export interface ListProjectsV1Response {
  projects?: ListProjectsV1ResponseProjectsItems[];
  additionalProperties?: Record<string, unknown>;
}

export const listProjectsV1ResponseSchema: Schema<ListProjectsV1Response> = lazy(
  () =>
    typedExpandoObject(
      {
        projects: [
          'projects',
          optional(array(listProjectsV1ResponseProjectsItemsSchema)),
        ],
      },
      'additionalProperties',
      optional(unknown())
    )
);
