/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ListenV1ResponseResultsChannelsItemsSearchItemsHitsItems,
  listenV1ResponseResultsChannelsItemsSearchItemsHitsItemsSchema,
} from './listenV1ResponseResultsChannelsItemsSearchItemsHitsItems.js';

export interface ListenV1ResponseResultsChannelsItemsSearchItems {
  query?: string;
  hits?: ListenV1ResponseResultsChannelsItemsSearchItemsHitsItems[];
  additionalProperties?: Record<string, unknown>;
}

export const listenV1ResponseResultsChannelsItemsSearchItemsSchema: Schema<ListenV1ResponseResultsChannelsItemsSearchItems> = lazy(
  () =>
    typedExpandoObject(
      {
        query: ['query', optional(string())],
        hits: [
          'hits',
          optional(
            array(
              listenV1ResponseResultsChannelsItemsSearchItemsHitsItemsSchema
            )
          ),
        ],
      },
      'additionalProperties',
      optional(unknown())
    )
);
