/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ListProjectKeysV1ResponseApiKeysItemsApiKey {
  apiKeyId?: string;
  comment?: string;
  scopes?: string[];
  created?: string;
  additionalProperties?: Record<string, unknown>;
}

export const listProjectKeysV1ResponseApiKeysItemsApiKeySchema: Schema<ListProjectKeysV1ResponseApiKeysItemsApiKey> = typedExpandoObject(
  {
    apiKeyId: ['api_key_id', optional(string())],
    comment: ['comment', optional(string())],
    scopes: ['scopes', optional(array(string()))],
    created: ['created', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
