/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ListenV1ResponseResultsChannelsItemsAlternativesItemsTopicsItems {
  text?: string;
  startWord?: number;
  endWord?: number;
  topics?: string[];
  additionalProperties?: Record<string, unknown>;
}

export const listenV1ResponseResultsChannelsItemsAlternativesItemsTopicsItemsSchema: Schema<ListenV1ResponseResultsChannelsItemsAlternativesItemsTopicsItems> = typedExpandoObject(
  {
    text: ['text', optional(string())],
    startWord: ['start_word', optional(number())],
    endWord: ['end_word', optional(number())],
    topics: ['topics', optional(array(string()))],
  },
  'additionalProperties',
  optional(unknown())
);
