/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ListenV1ResponseResultsChannelsItemsSearchItemsHitsItems {
  confidence?: number;
  start?: number;
  end?: number;
  snippet?: string;
  additionalProperties?: Record<string, unknown>;
}

export const listenV1ResponseResultsChannelsItemsSearchItemsHitsItemsSchema: Schema<ListenV1ResponseResultsChannelsItemsSearchItemsHitsItems> = typedExpandoObject(
  {
    confidence: ['confidence', optional(number())],
    start: ['start', optional(number())],
    end: ['end', optional(number())],
    snippet: ['snippet', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
