/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ListenV1ResponseResultsChannelsItemsAlternativesItemsEntitiesItems {
  label?: string;
  value?: string;
  rawValue?: string;
  confidence?: number;
  startWord?: number;
  endWord?: number;
  additionalProperties?: Record<string, unknown>;
}

export const listenV1ResponseResultsChannelsItemsAlternativesItemsEntitiesItemsSchema: Schema<ListenV1ResponseResultsChannelsItemsAlternativesItemsEntitiesItems> = typedExpandoObject(
  {
    label: ['label', optional(string())],
    value: ['value', optional(string())],
    rawValue: ['raw_value', optional(string())],
    confidence: ['confidence', optional(number())],
    startWord: ['start_word', optional(number())],
    endWord: ['end_word', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
