/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ListProjectKeysV1ResponseApiKeysItemsApiKey,
  listProjectKeysV1ResponseApiKeysItemsApiKeySchema,
} from './listProjectKeysV1ResponseApiKeysItemsApiKey.js';
import {
  ListProjectKeysV1ResponseApiKeysItemsMember,
  listProjectKeysV1ResponseApiKeysItemsMemberSchema,
} from './listProjectKeysV1ResponseApiKeysItemsMember.js';

export interface ListProjectKeysV1ResponseApiKeysItems {
  member?: ListProjectKeysV1ResponseApiKeysItemsMember;
  apiKey?: ListProjectKeysV1ResponseApiKeysItemsApiKey;
  additionalProperties?: Record<string, unknown>;
}

export const listProjectKeysV1ResponseApiKeysItemsSchema: Schema<ListProjectKeysV1ResponseApiKeysItems> = lazy(
  () =>
    typedExpandoObject(
      {
        member: [
          'member',
          optional(listProjectKeysV1ResponseApiKeysItemsMemberSchema),
        ],
        apiKey: [
          'api_key',
          optional(listProjectKeysV1ResponseApiKeysItemsApiKeySchema),
        ],
      },
      'additionalProperties',
      optional(unknown())
    )
);
