/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ListenV1ResponseResultsChannelsItemsAlternativesItemsParagraphsParagraphsItems,
  listenV1ResponseResultsChannelsItemsAlternativesItemsParagraphsParagraphsItemsSchema,
} from './listenV1ResponseResultsChannelsItemsAlternativesItemsParagraphsParagraphsItems.js';

export interface ListenV1ResponseResultsChannelsItemsAlternativesItemsParagraphs {
  transcript?: string;
  paragraphs?: ListenV1ResponseResultsChannelsItemsAlternativesItemsParagraphsParagraphsItems[];
  additionalProperties?: Record<string, unknown>;
}

export const listenV1ResponseResultsChannelsItemsAlternativesItemsParagraphsSchema: Schema<ListenV1ResponseResultsChannelsItemsAlternativesItemsParagraphs> = lazy(
  () =>
    typedExpandoObject(
      {
        transcript: ['transcript', optional(string())],
        paragraphs: [
          'paragraphs',
          optional(
            array(
              listenV1ResponseResultsChannelsItemsAlternativesItemsParagraphsParagraphsItemsSchema
            )
          ),
        ],
      },
      'additionalProperties',
      optional(unknown())
    )
);
