/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ListProjectKeysV1ResponseApiKeysItemsMember {
  memberId?: string;
  email?: string;
  additionalProperties?: Record<string, unknown>;
}

export const listProjectKeysV1ResponseApiKeysItemsMemberSchema: Schema<ListProjectKeysV1ResponseApiKeysItemsMember> = typedExpandoObject(
  {
    memberId: ['member_id', optional(string())],
    email: ['email', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
