/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ListProjectInvitesV1ResponseInvitesItems {
  /** The email address of the invitee */
  email?: string;
  /** The scope of the invitee */
  scope?: string;
  additionalProperties?: Record<string, unknown>;
}

export const listProjectInvitesV1ResponseInvitesItemsSchema: Schema<ListProjectInvitesV1ResponseInvitesItems> = typedExpandoObject(
  {
    email: ['email', optional(string())],
    scope: ['scope', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
