/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ListProjectMembersV1ResponseMembersItems,
  listProjectMembersV1ResponseMembersItemsSchema,
} from './listProjectMembersV1ResponseMembersItems.js';

export interface ListProjectMembersV1Response {
  members?: ListProjectMembersV1ResponseMembersItems[];
  additionalProperties?: Record<string, unknown>;
}

export const listProjectMembersV1ResponseSchema: Schema<ListProjectMembersV1Response> = lazy(
  () =>
    typedExpandoObject(
      {
        members: [
          'members',
          optional(array(listProjectMembersV1ResponseMembersItemsSchema)),
        ],
      },
      'additionalProperties',
      optional(unknown())
    )
);
