/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ListenV1ResponseResultsChannelsItemsAlternativesItemsEntitiesItems,
  listenV1ResponseResultsChannelsItemsAlternativesItemsEntitiesItemsSchema,
} from './listenV1ResponseResultsChannelsItemsAlternativesItemsEntitiesItems.js';
import {
  ListenV1ResponseResultsChannelsItemsAlternativesItemsParagraphs,
  listenV1ResponseResultsChannelsItemsAlternativesItemsParagraphsSchema,
} from './listenV1ResponseResultsChannelsItemsAlternativesItemsParagraphs.js';
import {
  ListenV1ResponseResultsChannelsItemsAlternativesItemsSummariesItems,
  listenV1ResponseResultsChannelsItemsAlternativesItemsSummariesItemsSchema,
} from './listenV1ResponseResultsChannelsItemsAlternativesItemsSummariesItems.js';
import {
  ListenV1ResponseResultsChannelsItemsAlternativesItemsTopicsItems,
  listenV1ResponseResultsChannelsItemsAlternativesItemsTopicsItemsSchema,
} from './listenV1ResponseResultsChannelsItemsAlternativesItemsTopicsItems.js';
import {
  ListenV1ResponseResultsChannelsItemsAlternativesItemsWordsItems,
  listenV1ResponseResultsChannelsItemsAlternativesItemsWordsItemsSchema,
} from './listenV1ResponseResultsChannelsItemsAlternativesItemsWordsItems.js';

export interface ListenV1ResponseResultsChannelsItemsAlternativesItems {
  transcript?: string;
  confidence?: number;
  words?: ListenV1ResponseResultsChannelsItemsAlternativesItemsWordsItems[];
  paragraphs?: ListenV1ResponseResultsChannelsItemsAlternativesItemsParagraphs;
  entities?: ListenV1ResponseResultsChannelsItemsAlternativesItemsEntitiesItems[];
  summaries?: ListenV1ResponseResultsChannelsItemsAlternativesItemsSummariesItems[];
  topics?: ListenV1ResponseResultsChannelsItemsAlternativesItemsTopicsItems[];
  additionalProperties?: Record<string, unknown>;
}

export const listenV1ResponseResultsChannelsItemsAlternativesItemsSchema: Schema<ListenV1ResponseResultsChannelsItemsAlternativesItems> = lazy(
  () =>
    typedExpandoObject(
      {
        transcript: ['transcript', optional(string())],
        confidence: ['confidence', optional(number())],
        words: [
          'words',
          optional(
            array(
              listenV1ResponseResultsChannelsItemsAlternativesItemsWordsItemsSchema
            )
          ),
        ],
        paragraphs: [
          'paragraphs',
          optional(
            listenV1ResponseResultsChannelsItemsAlternativesItemsParagraphsSchema
          ),
        ],
        entities: [
          'entities',
          optional(
            array(
              listenV1ResponseResultsChannelsItemsAlternativesItemsEntitiesItemsSchema
            )
          ),
        ],
        summaries: [
          'summaries',
          optional(
            array(
              listenV1ResponseResultsChannelsItemsAlternativesItemsSummariesItemsSchema
            )
          ),
        ],
        topics: [
          'topics',
          optional(
            array(
              listenV1ResponseResultsChannelsItemsAlternativesItemsTopicsItemsSchema
            )
          ),
        ],
      },
      'additionalProperties',
      optional(unknown())
    )
);
