/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { AgentVariableV1, agentVariableV1Schema } from './agentVariableV1.js';

export interface ListAgentVariablesV1Response {
  /** A list of agent variables for the project */
  variables?: AgentVariableV1[];
  additionalProperties?: Record<string, unknown>;
}

export const listAgentVariablesV1ResponseSchema: Schema<ListAgentVariablesV1Response> = lazy(
  () =>
    typedExpandoObject(
      { variables: ['variables', optional(array(agentVariableV1Schema))] },
      'additionalProperties',
      optional(unknown())
    )
);
