/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  AgentConfigurationV1,
  agentConfigurationV1Schema,
} from './agentConfigurationV1.js';

export interface ListAgentConfigurationsV1Response {
  /** A list of agent configurations for the project */
  agents?: AgentConfigurationV1[];
  additionalProperties?: Record<string, unknown>;
}

export const listAgentConfigurationsV1ResponseSchema: Schema<ListAgentConfigurationsV1Response> = lazy(
  () =>
    typedExpandoObject(
      { agents: ['agents', optional(array(agentConfigurationV1Schema))] },
      'additionalProperties',
      optional(unknown())
    )
);
