/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ListModelsV1ResponseSttModels {
  name?: string;
  canonicalName?: string;
  architecture?: string;
  languages?: string[];
  version?: string;
  uuid?: string;
  batch?: boolean;
  streaming?: boolean;
  formattedOutput?: boolean;
  additionalProperties?: Record<string, unknown>;
}

export const listModelsV1ResponseSttModelsSchema: Schema<ListModelsV1ResponseSttModels> = typedExpandoObject(
  {
    name: ['name', optional(string())],
    canonicalName: ['canonical_name', optional(string())],
    architecture: ['architecture', optional(string())],
    languages: ['languages', optional(array(string()))],
    version: ['version', optional(string())],
    uuid: ['uuid', optional(string())],
    batch: ['batch', optional(boolean())],
    streaming: ['streaming', optional(boolean())],
    formattedOutput: ['formatted_output', optional(boolean())],
  },
  'additionalProperties',
  optional(unknown())
);
