/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ListProjectBalancesV1ResponseBalancesItems,
  listProjectBalancesV1ResponseBalancesItemsSchema,
} from './listProjectBalancesV1ResponseBalancesItems.js';

export interface ListProjectBalancesV1Response {
  balances?: ListProjectBalancesV1ResponseBalancesItems[];
  additionalProperties?: Record<string, unknown>;
}

export const listProjectBalancesV1ResponseSchema: Schema<ListProjectBalancesV1Response> = lazy(
  () =>
    typedExpandoObject(
      {
        balances: [
          'balances',
          optional(array(listProjectBalancesV1ResponseBalancesItemsSchema)),
        ],
      },
      'additionalProperties',
      optional(unknown())
    )
);
