/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ListenV1ResponseResultsUtterancesItemsWordsItems {
  word?: string;
  start?: number;
  end?: number;
  confidence?: number;
  speaker?: number;
  speakerConfidence?: number;
  punctuatedWord?: string;
  additionalProperties?: Record<string, unknown>;
}

export const listenV1ResponseResultsUtterancesItemsWordsItemsSchema: Schema<ListenV1ResponseResultsUtterancesItemsWordsItems> = typedExpandoObject(
  {
    word: ['word', optional(string())],
    start: ['start', optional(number())],
    end: ['end', optional(number())],
    confidence: ['confidence', optional(number())],
    speaker: ['speaker', optional(number())],
    speakerConfidence: ['speaker_confidence', optional(number())],
    punctuatedWord: ['punctuated_word', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
