/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ListProjectMemberScopesV1Response {
  /** The API scopes of the member */
  scopes?: string[];
  additionalProperties?: Record<string, unknown>;
}

export const listProjectMemberScopesV1ResponseSchema: Schema<ListProjectMemberScopesV1Response> = typedExpandoObject(
  { scopes: ['scopes', optional(array(string()))] },
  'additionalProperties',
  optional(unknown())
);
