/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ListenV1ResponseMetadataIntentsInfo,
  listenV1ResponseMetadataIntentsInfoSchema,
} from './listenV1ResponseMetadataIntentsInfo.js';
import {
  ListenV1ResponseMetadataSentimentInfo,
  listenV1ResponseMetadataSentimentInfoSchema,
} from './listenV1ResponseMetadataSentimentInfo.js';
import {
  ListenV1ResponseMetadataSummaryInfo,
  listenV1ResponseMetadataSummaryInfoSchema,
} from './listenV1ResponseMetadataSummaryInfo.js';
import {
  ListenV1ResponseMetadataTopicsInfo,
  listenV1ResponseMetadataTopicsInfoSchema,
} from './listenV1ResponseMetadataTopicsInfo.js';

export interface ListenV1ResponseMetadata {
  transactionKey?: string;
  requestId: string;
  sha256: string;
  created: string;
  duration: number;
  channels: number;
  models: string[];
  modelInfo?: unknown;
  summaryInfo?: ListenV1ResponseMetadataSummaryInfo;
  sentimentInfo?: ListenV1ResponseMetadataSentimentInfo;
  topicsInfo?: ListenV1ResponseMetadataTopicsInfo;
  intentsInfo?: ListenV1ResponseMetadataIntentsInfo;
  tags?: string[];
  additionalProperties?: Record<string, unknown>;
}

export const listenV1ResponseMetadataSchema: Schema<ListenV1ResponseMetadata> = lazy(
  () =>
    typedExpandoObject(
      {
        transactionKey: ['transaction_key', optional(string())],
        requestId: ['request_id', string()],
        sha256: ['sha256', string()],
        created: ['created', string()],
        duration: ['duration', number()],
        channels: ['channels', number()],
        models: ['models', array(string())],
        modelInfo: ['model_info', optional(unknown())],
        summaryInfo: [
          'summary_info',
          optional(listenV1ResponseMetadataSummaryInfoSchema),
        ],
        sentimentInfo: [
          'sentiment_info',
          optional(listenV1ResponseMetadataSentimentInfoSchema),
        ],
        topicsInfo: [
          'topics_info',
          optional(listenV1ResponseMetadataTopicsInfoSchema),
        ],
        intentsInfo: [
          'intents_info',
          optional(listenV1ResponseMetadataIntentsInfoSchema),
        ],
        tags: ['tags', optional(array(string()))],
      },
      'additionalProperties',
      optional(unknown())
    )
);
