/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ListenV1ResponseResultsSummary {
  result?: string;
  mShort?: string;
  additionalProperties?: Record<string, unknown>;
}

export const listenV1ResponseResultsSummarySchema: Schema<ListenV1ResponseResultsSummary> = typedExpandoObject(
  {
    result: ['result', optional(string())],
    mShort: ['short', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
