/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ListenV1ResponseResultsUtterancesItemsWordsItems,
  listenV1ResponseResultsUtterancesItemsWordsItemsSchema,
} from './listenV1ResponseResultsUtterancesItemsWordsItems.js';

export interface ListenV1ResponseResultsUtterancesItems {
  start?: number;
  end?: number;
  confidence?: number;
  channel?: number;
  transcript?: string;
  words?: ListenV1ResponseResultsUtterancesItemsWordsItems[];
  speaker?: number;
  id?: string;
  additionalProperties?: Record<string, unknown>;
}

export const listenV1ResponseResultsUtterancesItemsSchema: Schema<ListenV1ResponseResultsUtterancesItems> = lazy(
  () =>
    typedExpandoObject(
      {
        start: ['start', optional(number())],
        end: ['end', optional(number())],
        confidence: ['confidence', optional(number())],
        channel: ['channel', optional(number())],
        transcript: ['transcript', optional(string())],
        words: [
          'words',
          optional(
            array(listenV1ResponseResultsUtterancesItemsWordsItemsSchema)
          ),
        ],
        speaker: ['speaker', optional(number())],
        id: ['id', optional(string())],
      },
      'additionalProperties',
      optional(unknown())
    )
);
