/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ListenV1ResponseResultsChannelsItemsAlternativesItemsSummariesItems {
  summary?: string;
  startWord?: number;
  endWord?: number;
  additionalProperties?: Record<string, unknown>;
}

export const listenV1ResponseResultsChannelsItemsAlternativesItemsSummariesItemsSchema: Schema<ListenV1ResponseResultsChannelsItemsAlternativesItemsSummariesItems> = typedExpandoObject(
  {
    summary: ['summary', optional(string())],
    startWord: ['start_word', optional(number())],
    endWord: ['end_word', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
