/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ListenV1ResponseResultsChannelsItems,
  listenV1ResponseResultsChannelsItemsSchema,
} from './listenV1ResponseResultsChannelsItems.js';
import {
  ListenV1ResponseResultsSummary,
  listenV1ResponseResultsSummarySchema,
} from './listenV1ResponseResultsSummary.js';
import {
  ListenV1ResponseResultsUtterancesItems,
  listenV1ResponseResultsUtterancesItemsSchema,
} from './listenV1ResponseResultsUtterancesItems.js';
import { SharedIntents, sharedIntentsSchema } from './sharedIntents.js';
import {
  SharedSentiments,
  sharedSentimentsSchema,
} from './sharedSentiments.js';
import { SharedTopics, sharedTopicsSchema } from './sharedTopics.js';

export interface ListenV1ResponseResults {
  channels: ListenV1ResponseResultsChannelsItems[];
  utterances?: ListenV1ResponseResultsUtterancesItems[];
  summary?: ListenV1ResponseResultsSummary;
  /** Output whenever `topics=true` is used */
  topics?: SharedTopics;
  /** Output whenever `intents=true` is used */
  intents?: SharedIntents;
  /** Output whenever `sentiment=true` is used */
  sentiments?: SharedSentiments;
  additionalProperties?: Record<string, unknown>;
}

export const listenV1ResponseResultsSchema: Schema<ListenV1ResponseResults> = lazy(
  () =>
    typedExpandoObject(
      {
        channels: [
          'channels',
          array(listenV1ResponseResultsChannelsItemsSchema),
        ],
        utterances: [
          'utterances',
          optional(array(listenV1ResponseResultsUtterancesItemsSchema)),
        ],
        summary: ['summary', optional(listenV1ResponseResultsSummarySchema)],
        topics: ['topics', optional(sharedTopicsSchema)],
        intents: ['intents', optional(sharedIntentsSchema)],
        sentiments: ['sentiments', optional(sharedSentimentsSchema)],
      },
      'additionalProperties',
      optional(unknown())
    )
);
