/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ListenV1ResponseResultsChannelsItemsAlternativesItems,
  listenV1ResponseResultsChannelsItemsAlternativesItemsSchema,
} from './listenV1ResponseResultsChannelsItemsAlternativesItems.js';
import {
  ListenV1ResponseResultsChannelsItemsSearchItems,
  listenV1ResponseResultsChannelsItemsSearchItemsSchema,
} from './listenV1ResponseResultsChannelsItemsSearchItems.js';

export interface ListenV1ResponseResultsChannelsItems {
  search?: ListenV1ResponseResultsChannelsItemsSearchItems[];
  alternatives?: ListenV1ResponseResultsChannelsItemsAlternativesItems[];
  detectedLanguage?: string;
  additionalProperties?: Record<string, unknown>;
}

export const listenV1ResponseResultsChannelsItemsSchema: Schema<ListenV1ResponseResultsChannelsItems> = lazy(
  () =>
    typedExpandoObject(
      {
        search: [
          'search',
          optional(
            array(listenV1ResponseResultsChannelsItemsSearchItemsSchema)
          ),
        ],
        alternatives: [
          'alternatives',
          optional(
            array(listenV1ResponseResultsChannelsItemsAlternativesItemsSchema)
          ),
        ],
        detectedLanguage: ['detected_language', optional(string())],
      },
      'additionalProperties',
      optional(unknown())
    )
);
