/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Audio file URL to transcribe */
export interface ListenV1RequestUrl {
  url: string;
  additionalProperties?: Record<string, unknown>;
}

export const listenV1RequestUrlSchema: Schema<ListenV1RequestUrl> = typedExpandoObject(
  { url: ['url', string()] },
  'additionalProperties',
  optional(unknown())
);
