/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ListProjectPurchasesV1ResponseOrdersItems,
  listProjectPurchasesV1ResponseOrdersItemsSchema,
} from './listProjectPurchasesV1ResponseOrdersItems.js';

export interface ListProjectPurchasesV1Response {
  orders?: ListProjectPurchasesV1ResponseOrdersItems[];
  additionalProperties?: Record<string, unknown>;
}

export const listProjectPurchasesV1ResponseSchema: Schema<ListProjectPurchasesV1Response> = lazy(
  () =>
    typedExpandoObject(
      {
        orders: [
          'orders',
          optional(array(listProjectPurchasesV1ResponseOrdersItemsSchema)),
        ],
      },
      'additionalProperties',
      optional(unknown())
    )
);
