/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  dict,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ListBillingFieldsV1ResponseDeploymentsItems,
  listBillingFieldsV1ResponseDeploymentsItemsSchema,
} from './listBillingFieldsV1ResponseDeploymentsItems.js';

export interface ListBillingFieldsV1Response {
  /** List of accessor UUIDs for the time period */
  accessors?: string[];
  /** List of deployment types for the time period */
  deployments?: ListBillingFieldsV1ResponseDeploymentsItems[];
  /** List of tags for the time period */
  tags?: string[];
  /** Map of line item names to human-readable descriptions for the time period */
  lineItems?: Record<string, string>;
  additionalProperties?: Record<string, unknown>;
}

export const listBillingFieldsV1ResponseSchema: Schema<ListBillingFieldsV1Response> = typedExpandoObject(
  {
    accessors: ['accessors', optional(array(string()))],
    deployments: [
      'deployments',
      optional(array(listBillingFieldsV1ResponseDeploymentsItemsSchema)),
    ],
    tags: ['tags', optional(array(string()))],
    lineItems: ['line_items', optional(dict(string()))],
  },
  'additionalProperties',
  optional(unknown())
);
