/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ListenV1ResponseResultsChannelsItemsAlternativesItemsParagraphsParagraphsItemsSentencesItems,
  listenV1ResponseResultsChannelsItemsAlternativesItemsParagraphsParagraphsItemsSentencesItemsSchema,
} from './listenV1ResponseResultsChannelsItemsAlternativesItemsParagraphsParagraphsItemsSentencesItems.js';

export interface ListenV1ResponseResultsChannelsItemsAlternativesItemsParagraphsParagraphsItems {
  sentences?: ListenV1ResponseResultsChannelsItemsAlternativesItemsParagraphsParagraphsItemsSentencesItems[];
  speaker?: number;
  numWords?: number;
  start?: number;
  end?: number;
  additionalProperties?: Record<string, unknown>;
}

export const listenV1ResponseResultsChannelsItemsAlternativesItemsParagraphsParagraphsItemsSchema: Schema<ListenV1ResponseResultsChannelsItemsAlternativesItemsParagraphsParagraphsItems> = lazy(
  () =>
    typedExpandoObject(
      {
        sentences: [
          'sentences',
          optional(
            array(
              listenV1ResponseResultsChannelsItemsAlternativesItemsParagraphsParagraphsItemsSentencesItemsSchema
            )
          ),
        ],
        speaker: ['speaker', optional(number())],
        numWords: ['num_words', optional(number())],
        start: ['start', optional(number())],
        end: ['end', optional(number())],
      },
      'additionalProperties',
      optional(unknown())
    )
);
