/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ListenV1ResponseMetadata,
  listenV1ResponseMetadataSchema,
} from './listenV1ResponseMetadata.js';
import {
  ListenV1ResponseResults,
  listenV1ResponseResultsSchema,
} from './listenV1ResponseResults.js';

/** The standard transcription response */
export interface ListenV1Response {
  metadata: ListenV1ResponseMetadata;
  results: ListenV1ResponseResults;
  additionalProperties?: Record<string, unknown>;
}

export const listenV1ResponseSchema: Schema<ListenV1Response> = lazy(() =>
  typedExpandoObject(
    {
      metadata: ['metadata', listenV1ResponseMetadataSchema],
      results: ['results', listenV1ResponseResultsSchema],
    },
    'additionalProperties',
    optional(unknown())
  )
);
