/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for ListBillingFieldsV1ResponseDeploymentsItems
 */
export enum ListBillingFieldsV1ResponseDeploymentsItems {
  Hosted = 'hosted',
  Beta = 'beta',
  Selfhosted = 'self-hosted',
  Dedicated = 'dedicated',
}

/**
 * Schema for ListBillingFieldsV1ResponseDeploymentsItems
 */
export const listBillingFieldsV1ResponseDeploymentsItemsSchema: Schema<ListBillingFieldsV1ResponseDeploymentsItems> = stringEnum(
  ListBillingFieldsV1ResponseDeploymentsItems
);
