/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ProjectRequestResponse,
  projectRequestResponseSchema,
} from './projectRequestResponse.js';

export interface ListProjectRequestsV1Response {
  /** The page number of the paginated response */
  page?: number;
  /** The number of results per page */
  limit?: number;
  requests?: ProjectRequestResponse[];
  additionalProperties?: Record<string, unknown>;
}

export const listProjectRequestsV1ResponseSchema: Schema<ListProjectRequestsV1Response> = lazy(
  () =>
    typedExpandoObject(
      {
        page: ['page', optional(number())],
        limit: ['limit', optional(number())],
        requests: ['requests', optional(array(projectRequestResponseSchema))],
      },
      'additionalProperties',
      optional(unknown())
    )
);
