/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ListProjectKeysV1ResponseApiKeysItems,
  listProjectKeysV1ResponseApiKeysItemsSchema,
} from './listProjectKeysV1ResponseApiKeysItems.js';

export interface ListProjectKeysV1Response {
  apiKeys?: ListProjectKeysV1ResponseApiKeysItems[];
  additionalProperties?: Record<string, unknown>;
}

export const listProjectKeysV1ResponseSchema: Schema<ListProjectKeysV1Response> = lazy(
  () =>
    typedExpandoObject(
      {
        apiKeys: [
          'api_keys',
          optional(array(listProjectKeysV1ResponseApiKeysItemsSchema)),
        ],
      },
      'additionalProperties',
      optional(unknown())
    )
);
