/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ListModelsV1ResponseTtsModelsMetadata,
  listModelsV1ResponseTtsModelsMetadataSchema,
} from './listModelsV1ResponseTtsModelsMetadata.js';

export interface ListModelsV1ResponseTtsModels {
  name?: string;
  canonicalName?: string;
  architecture?: string;
  languages?: string[];
  version?: string;
  uuid?: string;
  metadata?: ListModelsV1ResponseTtsModelsMetadata;
  additionalProperties?: Record<string, unknown>;
}

export const listModelsV1ResponseTtsModelsSchema: Schema<ListModelsV1ResponseTtsModels> = lazy(
  () =>
    typedExpandoObject(
      {
        name: ['name', optional(string())],
        canonicalName: ['canonical_name', optional(string())],
        architecture: ['architecture', optional(string())],
        languages: ['languages', optional(array(string()))],
        version: ['version', optional(string())],
        uuid: ['uuid', optional(string())],
        metadata: [
          'metadata',
          optional(listModelsV1ResponseTtsModelsMetadataSchema),
        ],
      },
      'additionalProperties',
      optional(unknown())
    )
);
