/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ListProjectInvitesV1ResponseInvitesItems,
  listProjectInvitesV1ResponseInvitesItemsSchema,
} from './listProjectInvitesV1ResponseInvitesItems.js';

export interface ListProjectInvitesV1Response {
  invites?: ListProjectInvitesV1ResponseInvitesItems[];
  additionalProperties?: Record<string, unknown>;
}

export const listProjectInvitesV1ResponseSchema: Schema<ListProjectInvitesV1Response> = lazy(
  () =>
    typedExpandoObject(
      {
        invites: [
          'invites',
          optional(array(listProjectInvitesV1ResponseInvitesItemsSchema)),
        ],
      },
      'additionalProperties',
      optional(unknown())
    )
);
