/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** A single request */
export interface ProjectRequestResponse {
  /** The unique identifier of the request */
  requestId?: string;
  /** The unique identifier of the project */
  projectUuid?: string;
  /** The date and time the request was created */
  created?: string;
  /** The API path of the request */
  path?: string;
  /** The unique identifier of the API key */
  apiKeyId?: string;
  /** The response of the request */
  response?: unknown;
  /** The response code of the request */
  code?: number;
  /** The deployment type */
  deployment?: string;
  /** The callback URL for the request */
  callback?: string;
  additionalProperties?: Record<string, unknown>;
}

export const projectRequestResponseSchema: Schema<ProjectRequestResponse> = typedExpandoObject(
  {
    requestId: ['request_id', optional(string())],
    projectUuid: ['project_uuid', optional(string())],
    created: ['created', optional(string())],
    path: ['path', optional(string())],
    apiKeyId: ['api_key_id', optional(string())],
    response: ['response', optional(unknown())],
    code: ['code', optional(number())],
    deployment: ['deployment', optional(string())],
    callback: ['callback', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
