/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ReadV1ResponseMetadata,
  readV1ResponseMetadataSchema,
} from './readV1ResponseMetadata.js';
import {
  ReadV1ResponseResults,
  readV1ResponseResultsSchema,
} from './readV1ResponseResults.js';

/** The standard text response */
export interface ReadV1Response {
  metadata: ReadV1ResponseMetadata;
  results: ReadV1ResponseResults;
  additionalProperties?: Record<string, unknown>;
}

export const readV1ResponseSchema: Schema<ReadV1Response> = lazy(() =>
  typedExpandoObject(
    {
      metadata: ['metadata', readV1ResponseMetadataSchema],
      results: ['results', readV1ResponseResultsSchema],
    },
    'additionalProperties',
    optional(unknown())
  )
);
