/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ReadV1ResponseMetadataMetadata,
  readV1ResponseMetadataMetadataSchema,
} from './readV1ResponseMetadataMetadata.js';

export interface ReadV1ResponseMetadata {
  metadata?: ReadV1ResponseMetadataMetadata;
  additionalProperties?: Record<string, unknown>;
}

export const readV1ResponseMetadataSchema: Schema<ReadV1ResponseMetadata> = lazy(
  () =>
    typedExpandoObject(
      {
        metadata: ['metadata', optional(readV1ResponseMetadataMetadataSchema)],
      },
      'additionalProperties',
      optional(unknown())
    )
);
