/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ReadV1RequestUrl {
  /** A URL pointing to the text source */
  url: string;
  additionalProperties?: Record<string, unknown>;
}

export const readV1RequestUrlSchema: Schema<ReadV1RequestUrl> = typedExpandoObject(
  { url: ['url', string()] },
  'additionalProperties',
  optional(unknown())
);
