/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ReadV1ResponseMetadataMetadataTopicsInfo {
  modelUuid?: string;
  inputTokens?: number;
  outputTokens?: number;
  additionalProperties?: Record<string, unknown>;
}

export const readV1ResponseMetadataMetadataTopicsInfoSchema: Schema<ReadV1ResponseMetadataMetadataTopicsInfo> = typedExpandoObject(
  {
    modelUuid: ['model_uuid', optional(string())],
    inputTokens: ['input_tokens', optional(number())],
    outputTokens: ['output_tokens', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
