/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ReadV1RequestText {
  /** The plain text to analyze */
  text: string;
  additionalProperties?: Record<string, unknown>;
}

export const readV1RequestTextSchema: Schema<ReadV1RequestText> = typedExpandoObject(
  { text: ['text', string()] },
  'additionalProperties',
  optional(unknown())
);
