/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ReadV1ResponseResultsSummary,
  readV1ResponseResultsSummarySchema,
} from './readV1ResponseResultsSummary.js';
import { SharedIntents, sharedIntentsSchema } from './sharedIntents.js';
import {
  SharedSentiments,
  sharedSentimentsSchema,
} from './sharedSentiments.js';
import { SharedTopics, sharedTopicsSchema } from './sharedTopics.js';

export interface ReadV1ResponseResults {
  /** Output whenever `summary=true` is used */
  summary?: ReadV1ResponseResultsSummary;
  /** Output whenever `topics=true` is used */
  topics?: SharedTopics;
  /** Output whenever `intents=true` is used */
  intents?: SharedIntents;
  /** Output whenever `sentiment=true` is used */
  sentiments?: SharedSentiments;
  additionalProperties?: Record<string, unknown>;
}

export const readV1ResponseResultsSchema: Schema<ReadV1ResponseResults> = lazy(
  () =>
    typedExpandoObject(
      {
        summary: ['summary', optional(readV1ResponseResultsSummarySchema)],
        topics: ['topics', optional(sharedTopicsSchema)],
        intents: ['intents', optional(sharedIntentsSchema)],
        sentiments: ['sentiments', optional(sharedSentimentsSchema)],
      },
      'additionalProperties',
      optional(unknown())
    )
);
