/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ReadV1ResponseResultsSummaryResultsSummary,
  readV1ResponseResultsSummaryResultsSummarySchema,
} from './readV1ResponseResultsSummaryResultsSummary.js';

export interface ReadV1ResponseResultsSummaryResults {
  summary?: ReadV1ResponseResultsSummaryResultsSummary;
  additionalProperties?: Record<string, unknown>;
}

export const readV1ResponseResultsSummaryResultsSchema: Schema<ReadV1ResponseResultsSummaryResults> = lazy(
  () =>
    typedExpandoObject(
      {
        summary: [
          'summary',
          optional(readV1ResponseResultsSummaryResultsSummarySchema),
        ],
      },
      'additionalProperties',
      optional(unknown())
    )
);
