/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ReadV1ResponseResultsSummaryResultsSummary {
  text?: string;
  additionalProperties?: Record<string, unknown>;
}

export const readV1ResponseResultsSummaryResultsSummarySchema: Schema<ReadV1ResponseResultsSummaryResultsSummary> = typedExpandoObject(
  { text: ['text', optional(string())] },
  'additionalProperties',
  optional(unknown())
);
