/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ReadV1ResponseMetadataMetadataIntentsInfo,
  readV1ResponseMetadataMetadataIntentsInfoSchema,
} from './readV1ResponseMetadataMetadataIntentsInfo.js';
import {
  ReadV1ResponseMetadataMetadataSentimentInfo,
  readV1ResponseMetadataMetadataSentimentInfoSchema,
} from './readV1ResponseMetadataMetadataSentimentInfo.js';
import {
  ReadV1ResponseMetadataMetadataSummaryInfo,
  readV1ResponseMetadataMetadataSummaryInfoSchema,
} from './readV1ResponseMetadataMetadataSummaryInfo.js';
import {
  ReadV1ResponseMetadataMetadataTopicsInfo,
  readV1ResponseMetadataMetadataTopicsInfoSchema,
} from './readV1ResponseMetadataMetadataTopicsInfo.js';

export interface ReadV1ResponseMetadataMetadata {
  requestId?: string;
  created?: string;
  language?: string;
  summaryInfo?: ReadV1ResponseMetadataMetadataSummaryInfo;
  sentimentInfo?: ReadV1ResponseMetadataMetadataSentimentInfo;
  topicsInfo?: ReadV1ResponseMetadataMetadataTopicsInfo;
  intentsInfo?: ReadV1ResponseMetadataMetadataIntentsInfo;
  additionalProperties?: Record<string, unknown>;
}

export const readV1ResponseMetadataMetadataSchema: Schema<ReadV1ResponseMetadataMetadata> = lazy(
  () =>
    typedExpandoObject(
      {
        requestId: ['request_id', optional(string())],
        created: ['created', optional(string())],
        language: ['language', optional(string())],
        summaryInfo: [
          'summary_info',
          optional(readV1ResponseMetadataMetadataSummaryInfoSchema),
        ],
        sentimentInfo: [
          'sentiment_info',
          optional(readV1ResponseMetadataMetadataSentimentInfoSchema),
        ],
        topicsInfo: [
          'topics_info',
          optional(readV1ResponseMetadataMetadataTopicsInfoSchema),
        ],
        intentsInfo: [
          'intents_info',
          optional(readV1ResponseMetadataMetadataIntentsInfoSchema),
        ],
      },
      'additionalProperties',
      optional(unknown())
    )
);
