/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ReadV1ResponseResultsSummaryResults,
  readV1ResponseResultsSummaryResultsSchema,
} from './readV1ResponseResultsSummaryResults.js';

/** Output whenever `summary=true` is used */
export interface ReadV1ResponseResultsSummary {
  results?: ReadV1ResponseResultsSummaryResults;
  additionalProperties?: Record<string, unknown>;
}

export const readV1ResponseResultsSummarySchema: Schema<ReadV1ResponseResultsSummary> = lazy(
  () =>
    typedExpandoObject(
      {
        results: [
          'results',
          optional(readV1ResponseResultsSummaryResultsSchema),
        ],
      },
      'additionalProperties',
      optional(unknown())
    )
);
