/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  SharedTopicsResultsTopics,
  sharedTopicsResultsTopicsSchema,
} from './sharedTopicsResultsTopics.js';

export interface SharedTopicsResults {
  topics?: SharedTopicsResultsTopics;
  additionalProperties?: Record<string, unknown>;
}

export const sharedTopicsResultsSchema: Schema<SharedTopicsResults> = lazy(() =>
  typedExpandoObject(
    { topics: ['topics', optional(sharedTopicsResultsTopicsSchema)] },
    'additionalProperties',
    optional(unknown())
  )
);
