/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  SharedIntentsResultsIntentsSegmentsItems,
  sharedIntentsResultsIntentsSegmentsItemsSchema,
} from './sharedIntentsResultsIntentsSegmentsItems.js';

export interface SharedIntentsResultsIntents {
  segments?: SharedIntentsResultsIntentsSegmentsItems[];
  additionalProperties?: Record<string, unknown>;
}

export const sharedIntentsResultsIntentsSchema: Schema<SharedIntentsResultsIntents> = lazy(
  () =>
    typedExpandoObject(
      {
        segments: [
          'segments',
          optional(array(sharedIntentsResultsIntentsSegmentsItemsSchema)),
        ],
      },
      'additionalProperties',
      optional(unknown())
    )
);
