/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  SharedIntentsResultsIntentsSegmentsItemsIntentsItems,
  sharedIntentsResultsIntentsSegmentsItemsIntentsItemsSchema,
} from './sharedIntentsResultsIntentsSegmentsItemsIntentsItems.js';

export interface SharedIntentsResultsIntentsSegmentsItems {
  text?: string;
  startWord?: number;
  endWord?: number;
  intents?: SharedIntentsResultsIntentsSegmentsItemsIntentsItems[];
  additionalProperties?: Record<string, unknown>;
}

export const sharedIntentsResultsIntentsSegmentsItemsSchema: Schema<SharedIntentsResultsIntentsSegmentsItems> = lazy(
  () =>
    typedExpandoObject(
      {
        text: ['text', optional(string())],
        startWord: ['start_word', optional(number())],
        endWord: ['end_word', optional(number())],
        intents: [
          'intents',
          optional(
            array(sharedIntentsResultsIntentsSegmentsItemsIntentsItemsSchema)
          ),
        ],
      },
      'additionalProperties',
      optional(unknown())
    )
);
