/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  SharedTopicsResultsTopicsSegmentsItems,
  sharedTopicsResultsTopicsSegmentsItemsSchema,
} from './sharedTopicsResultsTopicsSegmentsItems.js';

export interface SharedTopicsResultsTopics {
  segments?: SharedTopicsResultsTopicsSegmentsItems[];
  additionalProperties?: Record<string, unknown>;
}

export const sharedTopicsResultsTopicsSchema: Schema<SharedTopicsResultsTopics> = lazy(
  () =>
    typedExpandoObject(
      {
        segments: [
          'segments',
          optional(array(sharedTopicsResultsTopicsSegmentsItemsSchema)),
        ],
      },
      'additionalProperties',
      optional(unknown())
    )
);
