/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  SharedTopicsResults,
  sharedTopicsResultsSchema,
} from './sharedTopicsResults.js';

/** Output whenever `topics=true` is used */
export interface SharedTopics {
  results?: SharedTopicsResults;
  additionalProperties?: Record<string, unknown>;
}

export const sharedTopicsSchema: Schema<SharedTopics> = lazy(() =>
  typedExpandoObject(
    { results: ['results', optional(sharedTopicsResultsSchema)] },
    'additionalProperties',
    optional(unknown())
  )
);
