/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface SharedSentimentsSegmentsItems {
  text?: string;
  startWord?: number;
  endWord?: number;
  sentiment?: string;
  sentimentScore?: number;
  additionalProperties?: Record<string, unknown>;
}

export const sharedSentimentsSegmentsItemsSchema: Schema<SharedSentimentsSegmentsItems> = typedExpandoObject(
  {
    text: ['text', optional(string())],
    startWord: ['start_word', optional(number())],
    endWord: ['end_word', optional(number())],
    sentiment: ['sentiment', optional(string())],
    sentimentScore: ['sentiment_score', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
