/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface SharedSentimentsAverage {
  sentiment?: string;
  sentimentScore?: number;
  additionalProperties?: Record<string, unknown>;
}

export const sharedSentimentsAverageSchema: Schema<SharedSentimentsAverage> = typedExpandoObject(
  {
    sentiment: ['sentiment', optional(string())],
    sentimentScore: ['sentiment_score', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
