/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  SharedIntentsResultsIntents,
  sharedIntentsResultsIntentsSchema,
} from './sharedIntentsResultsIntents.js';

export interface SharedIntentsResults {
  intents?: SharedIntentsResultsIntents;
  additionalProperties?: Record<string, unknown>;
}

export const sharedIntentsResultsSchema: Schema<SharedIntentsResults> = lazy(
  () =>
    typedExpandoObject(
      { intents: ['intents', optional(sharedIntentsResultsIntentsSchema)] },
      'additionalProperties',
      optional(unknown())
    )
);
