/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface SharedTopicsResultsTopicsSegmentsItemsTopicsItems {
  topic?: string;
  confidenceScore?: number;
  additionalProperties?: Record<string, unknown>;
}

export const sharedTopicsResultsTopicsSegmentsItemsTopicsItemsSchema: Schema<SharedTopicsResultsTopicsSegmentsItemsTopicsItems> = typedExpandoObject(
  {
    topic: ['topic', optional(string())],
    confidenceScore: ['confidence_score', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
