/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  SharedTopicsResultsTopicsSegmentsItemsTopicsItems,
  sharedTopicsResultsTopicsSegmentsItemsTopicsItemsSchema,
} from './sharedTopicsResultsTopicsSegmentsItemsTopicsItems.js';

export interface SharedTopicsResultsTopicsSegmentsItems {
  text?: string;
  startWord?: number;
  endWord?: number;
  topics?: SharedTopicsResultsTopicsSegmentsItemsTopicsItems[];
  additionalProperties?: Record<string, unknown>;
}

export const sharedTopicsResultsTopicsSegmentsItemsSchema: Schema<SharedTopicsResultsTopicsSegmentsItems> = lazy(
  () =>
    typedExpandoObject(
      {
        text: ['text', optional(string())],
        startWord: ['start_word', optional(number())],
        endWord: ['end_word', optional(number())],
        topics: [
          'topics',
          optional(
            array(sharedTopicsResultsTopicsSegmentsItemsTopicsItemsSchema)
          ),
        ],
      },
      'additionalProperties',
      optional(unknown())
    )
);
