/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  SharedSentimentsAverage,
  sharedSentimentsAverageSchema,
} from './sharedSentimentsAverage.js';
import {
  SharedSentimentsSegmentsItems,
  sharedSentimentsSegmentsItemsSchema,
} from './sharedSentimentsSegmentsItems.js';

/** Output whenever `sentiment=true` is used */
export interface SharedSentiments {
  segments?: SharedSentimentsSegmentsItems[];
  average?: SharedSentimentsAverage;
  additionalProperties?: Record<string, unknown>;
}

export const sharedSentimentsSchema: Schema<SharedSentiments> = lazy(() =>
  typedExpandoObject(
    {
      segments: [
        'segments',
        optional(array(sharedSentimentsSegmentsItemsSchema)),
      ],
      average: ['average', optional(sharedSentimentsAverageSchema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
