/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Request body for Flux TTS batch (REST) text-to-speech conversion. The full block of text is synthesized in a single request and returned as one audio response. */
export interface SpeakV2Request {
  /** The text content to be converted to speech. The server normalizes and preprocesses the text (e.g. stripping inline controls) before synthesis. */
  text: string;
  additionalProperties?: Record<string, unknown>;
}

export const speakV2RequestSchema: Schema<SpeakV2Request> = typedExpandoObject(
  { text: ['text', string()] },
  'additionalProperties',
  optional(unknown())
);
