/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Request body for text-to-speech conversion */
export interface SpeakV1Request {
  /** The text content to be converted to speech */
  text: string;
  additionalProperties?: Record<string, unknown>;
}

export const speakV1RequestSchema: Schema<SpeakV1Request> = typedExpandoObject(
  { text: ['text', string()] },
  'additionalProperties',
  optional(unknown())
);
