/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Accepted response returned when a callback URL is supplied; the audio is delivered asynchronously to that URL. */
export interface SpeakV2AcceptedResponse {
  /** Unique identifier for tracking the asynchronous request */
  requestId: string;
  additionalProperties?: Record<string, unknown>;
}

export const speakV2AcceptedResponseSchema: Schema<SpeakV2AcceptedResponse> = typedExpandoObject(
  { requestId: ['request_id', string()] },
  'additionalProperties',
  optional(unknown())
);
