/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { optional, Schema, typedExpandoObject, unknown } from '../schema.js';

/** Request body for updating an agent variable */
export interface UpdateAgentVariableV1Request {
  /** The new value to substitute */
  value?: unknown;
  additionalProperties?: Record<string, unknown>;
}

export const updateAgentVariableV1RequestSchema: Schema<UpdateAgentVariableV1Request> = typedExpandoObject(
  { value: ['value', optional(unknown())] },
  'additionalProperties',
  optional(unknown())
);
