/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  dict,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Request body for updating agent configuration metadata */
export interface UpdateAgentMetadataV1Request {
  /** A map of string key-value pairs to associate with this agent configuration */
  metadata: Record<string, string>;
  additionalProperties?: Record<string, unknown>;
}

export const updateAgentMetadataV1RequestSchema: Schema<UpdateAgentMetadataV1Request> = typedExpandoObject(
  { metadata: ['metadata', dict(string())] },
  'additionalProperties',
  optional(unknown())
);
