/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface UpdateProjectMemberScopesV1Request {
  /** A scope to update */
  scope: string;
  additionalProperties?: Record<string, unknown>;
}

export const updateProjectMemberScopesV1RequestSchema: Schema<UpdateProjectMemberScopesV1Request> = typedExpandoObject(
  { scope: ['scope', string()] },
  'additionalProperties',
  optional(unknown())
);
