/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface UpdateProjectMemberScopesV1Response {
  /** confirmation message */
  message?: string;
  additionalProperties?: Record<string, unknown>;
}

export const updateProjectMemberScopesV1ResponseSchema: Schema<UpdateProjectMemberScopesV1Response> = typedExpandoObject(
  { message: ['message', optional(string())] },
  'additionalProperties',
  optional(unknown())
);
