/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface UpdateProjectV1Request {
  /** The name of the project */
  name?: string;
  additionalProperties?: Record<string, unknown>;
}

export const updateProjectV1RequestSchema: Schema<UpdateProjectV1Request> = typedExpandoObject(
  { name: ['name', optional(string())] },
  'additionalProperties',
  optional(unknown())
);
