/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  UsageBreakdownV1ResponseResultsItemsGrouping,
  usageBreakdownV1ResponseResultsItemsGroupingSchema,
} from './usageBreakdownV1ResponseResultsItemsGrouping.js';

export interface UsageBreakdownV1ResponseResultsItems {
  /** Audio hours processed */
  hours: number;
  /** Total hours including all processing */
  totalHours: number;
  /** Agent hours used */
  agentHours: number;
  /** Number of input tokens */
  tokensIn: number;
  /** Number of output tokens */
  tokensOut: number;
  /** Number of text-to-speech characters processed */
  ttsCharacters: number;
  /** Number of requests */
  requests: number;
  grouping: UsageBreakdownV1ResponseResultsItemsGrouping;
  additionalProperties?: Record<string, unknown>;
}

export const usageBreakdownV1ResponseResultsItemsSchema: Schema<UsageBreakdownV1ResponseResultsItems> = lazy(
  () =>
    typedExpandoObject(
      {
        hours: ['hours', number()],
        totalHours: ['total_hours', number()],
        agentHours: ['agent_hours', number()],
        tokensIn: ['tokens_in', number()],
        tokensOut: ['tokens_out', number()],
        ttsCharacters: ['tts_characters', number()],
        requests: ['requests', number()],
        grouping: [
          'grouping',
          usageBreakdownV1ResponseResultsItemsGroupingSchema,
        ],
      },
      'additionalProperties',
      optional(unknown())
    )
);
