/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  UsageFieldsV1ResponseModelsItems,
  usageFieldsV1ResponseModelsItemsSchema,
} from './usageFieldsV1ResponseModelsItems.js';

export interface UsageFieldsV1Response {
  /** List of tags associated with the project */
  tags?: string[];
  /** List of models available for the project. */
  models?: UsageFieldsV1ResponseModelsItems[];
  /** Processing methods supported by the API */
  processingMethods?: string[];
  /** API features available to the project */
  features?: string[];
  additionalProperties?: Record<string, unknown>;
}

export const usageFieldsV1ResponseSchema: Schema<UsageFieldsV1Response> = lazy(
  () =>
    typedExpandoObject(
      {
        tags: ['tags', optional(array(string()))],
        models: [
          'models',
          optional(array(usageFieldsV1ResponseModelsItemsSchema)),
        ],
        processingMethods: ['processing_methods', optional(array(string()))],
        features: ['features', optional(array(string()))],
      },
      'additionalProperties',
      optional(unknown())
    )
);
