/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface UsageBreakdownV1ResponseResultsItemsGrouping {
  /** Start date for this group */
  start?: string;
  /** End date for this group */
  end?: string;
  /** Optional accessor identifier */
  accessor?: string | null;
  /** Optional endpoint identifier */
  endpoint?: string | null;
  /** Optional feature set identifier */
  featureSet?: string | null;
  models?: string[];
  /** Optional method identifier */
  method?: string | null;
  /** Optional list of tags, null unless grouped by tags. */
  tags?: string[] | null;
  /** Optional deployment identifier */
  deployment?: string | null;
  additionalProperties?: Record<string, unknown>;
}

export const usageBreakdownV1ResponseResultsItemsGroupingSchema: Schema<UsageBreakdownV1ResponseResultsItemsGrouping> = typedExpandoObject(
  {
    start: ['start', optional(string())],
    end: ['end', optional(string())],
    accessor: ['accessor', optional(nullable(string()))],
    endpoint: ['endpoint', optional(nullable(string()))],
    featureSet: ['feature_set', optional(nullable(string()))],
    models: ['models', optional(array(string()))],
    method: ['method', optional(nullable(string()))],
    tags: ['tags', optional(nullable(array(string())))],
    deployment: ['deployment', optional(nullable(string()))],
  },
  'additionalProperties',
  optional(unknown())
);
