/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  UsageV1ResponseResolution,
  usageV1ResponseResolutionSchema,
} from './usageV1ResponseResolution.js';

export interface UsageV1Response {
  start?: string;
  end?: string;
  resolution?: UsageV1ResponseResolution;
  additionalProperties?: Record<string, unknown>;
}

export const usageV1ResponseSchema: Schema<UsageV1Response> = lazy(() =>
  typedExpandoObject(
    {
      start: ['start', optional(string())],
      end: ['end', optional(string())],
      resolution: ['resolution', optional(usageV1ResponseResolutionSchema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
