/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface UsageFieldsV1ResponseModelsItems {
  /** Name of the model. */
  name?: string;
  /** The language supported by the model (IETF language tag). */
  language?: string;
  /** Version identifier of the model, typically with a date and a revision number. */
  version?: string;
  /** Unique identifier for the model. */
  modelId?: string;
  additionalProperties?: Record<string, unknown>;
}

export const usageFieldsV1ResponseModelsItemsSchema: Schema<UsageFieldsV1ResponseModelsItems> = typedExpandoObject(
  {
    name: ['name', optional(string())],
    language: ['language', optional(string())],
    version: ['version', optional(string())],
    modelId: ['model_id', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
