/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  UsageBreakdownV1ResponseResolution,
  usageBreakdownV1ResponseResolutionSchema,
} from './usageBreakdownV1ResponseResolution.js';
import {
  UsageBreakdownV1ResponseResultsItems,
  usageBreakdownV1ResponseResultsItemsSchema,
} from './usageBreakdownV1ResponseResultsItems.js';

export interface UsageBreakdownV1Response {
  /** Start date of the usage period */
  start: string;
  /** End date of the usage period */
  end: string;
  resolution: UsageBreakdownV1ResponseResolution;
  results: UsageBreakdownV1ResponseResultsItems[];
  additionalProperties?: Record<string, unknown>;
}

export const usageBreakdownV1ResponseSchema: Schema<UsageBreakdownV1Response> = lazy(
  () =>
    typedExpandoObject(
      {
        start: ['start', string()],
        end: ['end', string()],
        resolution: ['resolution', usageBreakdownV1ResponseResolutionSchema],
        results: ['results', array(usageBreakdownV1ResponseResultsItemsSchema)],
      },
      'additionalProperties',
      optional(unknown())
    )
);
