/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface UsageV1ResponseResolution {
  units?: string;
  amount?: number;
  additionalProperties?: Record<string, unknown>;
}

export const usageV1ResponseResolutionSchema: Schema<UsageV1ResponseResolution> = typedExpandoObject(
  {
    units: ['units', optional(string())],
    amount: ['amount', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
