/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for V1ListenPostParametersModel0
 */
export enum V1ListenPostParametersModel0 {
  Nova3 = 'nova-3',
  Nova3General = 'nova-3-general',
  Nova3Medical = 'nova-3-medical',
  Nova2 = 'nova-2',
  Nova2General = 'nova-2-general',
  Nova2Meeting = 'nova-2-meeting',
  Nova2Finance = 'nova-2-finance',
  Nova2Conversationalai = 'nova-2-conversationalai',
  Nova2Voicemail = 'nova-2-voicemail',
  Nova2Video = 'nova-2-video',
  Nova2Medical = 'nova-2-medical',
  Nova2Drivethru = 'nova-2-drivethru',
  Nova2Automotive = 'nova-2-automotive',
  Nova = 'nova',
  Novageneral = 'nova-general',
  Novaphonecall = 'nova-phonecall',
  Novamedical = 'nova-medical',
  Enhanced = 'enhanced',
  Enhancedgeneral = 'enhanced-general',
  Enhancedmeeting = 'enhanced-meeting',
  Enhancedphonecall = 'enhanced-phonecall',
  Enhancedfinance = 'enhanced-finance',
  Base = 'base',
  Meeting = 'meeting',
  Phonecall = 'phonecall',
  Finance = 'finance',
  Conversationalai = 'conversationalai',
  Voicemail = 'voicemail',
  Video = 'video',
}

/**
 * Schema for V1ListenPostParametersModel0
 */
export const v1ListenPostParametersModel0Schema: Schema<V1ListenPostParametersModel0> = stringEnum(
  V1ListenPostParametersModel0
);
