/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for V1ListenPostParametersDiarizeModel
 */
export enum V1ListenPostParametersDiarizeModel {
  Latest = 'latest',
  V1 = 'v1',
  V2 = 'v2',
}

/**
 * Schema for V1ListenPostParametersDiarizeModel
 */
export const v1ListenPostParametersDiarizeModelSchema: Schema<V1ListenPostParametersDiarizeModel> = stringEnum(
  V1ListenPostParametersDiarizeModel
);
