/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for V1ListenPostParametersCustomIntentMode
 */
export enum V1ListenPostParametersCustomIntentMode {
  Extended = 'extended',
  Strict = 'strict',
}

/**
 * Schema for V1ListenPostParametersCustomIntentMode
 */
export const v1ListenPostParametersCustomIntentModeSchema: Schema<V1ListenPostParametersCustomIntentMode> = stringEnum(
  V1ListenPostParametersCustomIntentMode
);
