/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for V1ListenPostParametersEncoding
 */
export enum V1ListenPostParametersEncoding {
  Linear16 = 'linear16',
  Flac = 'flac',
  Mulaw = 'mulaw',
  Amrnb = 'amr-nb',
  Amrwb = 'amr-wb',
  Opus = 'opus',
  Speex = 'speex',
  G729 = 'g729',
}

/**
 * Schema for V1ListenPostParametersEncoding
 */
export const v1ListenPostParametersEncodingSchema: Schema<V1ListenPostParametersEncoding> = stringEnum(
  V1ListenPostParametersEncoding
);
