/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for V1ListenPostParametersSummarize0
 */
export enum V1ListenPostParametersSummarize0 {
  V2 = 'v2',
}

/**
 * Schema for V1ListenPostParametersSummarize0
 */
export const v1ListenPostParametersSummarize0Schema: Schema<V1ListenPostParametersSummarize0> = stringEnum(
  V1ListenPostParametersSummarize0
);
