/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for V1ListenPostParametersVersion0
 */
export enum V1ListenPostParametersVersion0 {
  Latest = 'latest',
}

/**
 * Schema for V1ListenPostParametersVersion0
 */
export const v1ListenPostParametersVersion0Schema: Schema<V1ListenPostParametersVersion0> = stringEnum(
  V1ListenPostParametersVersion0
);
