/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for V1ListenPostParametersRedactSchemaOneOf1Items
 */
export enum V1ListenPostParametersRedactSchemaOneOf1Items {
  Pci = 'pci',
  Pii = 'pii',
  Numbers = 'numbers',
}

/**
 * Schema for V1ListenPostParametersRedactSchemaOneOf1Items
 */
export const v1ListenPostParametersRedactSchemaOneOf1ItemsSchema: Schema<V1ListenPostParametersRedactSchemaOneOf1Items> = stringEnum(
  V1ListenPostParametersRedactSchemaOneOf1Items
);
