/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for V1ListenPostParametersCallbackMethod
 */
export enum V1ListenPostParametersCallbackMethod {
  Post = 'POST',
  Put = 'PUT',
}

/**
 * Schema for V1ListenPostParametersCallbackMethod
 */
export const v1ListenPostParametersCallbackMethodSchema: Schema<V1ListenPostParametersCallbackMethod> = stringEnum(
  V1ListenPostParametersCallbackMethod
);
