/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for V1ListenPostParametersCustomTopicMode
 */
export enum V1ListenPostParametersCustomTopicMode {
  Extended = 'extended',
  Strict = 'strict',
}

/**
 * Schema for V1ListenPostParametersCustomTopicMode
 */
export const v1ListenPostParametersCustomTopicModeSchema: Schema<V1ListenPostParametersCustomTopicMode> = stringEnum(
  V1ListenPostParametersCustomTopicMode
);
