/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for V1ProjectsProjectIdUsageGetParametersMethod
 */
export enum V1ProjectsProjectIdUsageGetParametersMethod {
  Sync = 'sync',
  Async = 'async',
  Streaming = 'streaming',
}

/**
 * Schema for V1ProjectsProjectIdUsageGetParametersMethod
 */
export const v1ProjectsProjectIdUsageGetParametersMethodSchema: Schema<V1ProjectsProjectIdUsageGetParametersMethod> = stringEnum(
  V1ProjectsProjectIdUsageGetParametersMethod
);
