/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for V1ProjectsProjectIdRequestsGetParametersDeployment
 */
export enum V1ProjectsProjectIdRequestsGetParametersDeployment {
  Hosted = 'hosted',
  Beta = 'beta',
  Selfhosted = 'self-hosted',
}

/**
 * Schema for V1ProjectsProjectIdRequestsGetParametersDeployment
 */
export const v1ProjectsProjectIdRequestsGetParametersDeploymentSchema: Schema<V1ProjectsProjectIdRequestsGetParametersDeployment> = stringEnum(
  V1ProjectsProjectIdRequestsGetParametersDeployment
);
