/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for V1ProjectsProjectIdRequestsGetParametersMethod
 */
export enum V1ProjectsProjectIdRequestsGetParametersMethod {
  Sync = 'sync',
  Async = 'async',
  Streaming = 'streaming',
}

/**
 * Schema for V1ProjectsProjectIdRequestsGetParametersMethod
 */
export const v1ProjectsProjectIdRequestsGetParametersMethodSchema: Schema<V1ProjectsProjectIdRequestsGetParametersMethod> = stringEnum(
  V1ProjectsProjectIdRequestsGetParametersMethod
);
