/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for V1ProjectsProjectIdBillingBreakdownGetParametersGroupingSchemaItems
 */
export enum V1ProjectsProjectIdBillingBreakdownGetParametersGroupingSchemaItems {
  Accessor = 'accessor',
  Deployment = 'deployment',
  LineItem = 'line_item',
  Tags = 'tags',
}

/**
 * Schema for V1ProjectsProjectIdBillingBreakdownGetParametersGroupingSchemaItems
 */
export const v1ProjectsProjectIdBillingBreakdownGetParametersGroupingSchemaItemsSchema: Schema<V1ProjectsProjectIdBillingBreakdownGetParametersGroupingSchemaItems> = stringEnum(
  V1ProjectsProjectIdBillingBreakdownGetParametersGroupingSchemaItems
);
