/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for V1ProjectsProjectIdSelfHostedDistributionCredentialsPostParametersScopesSchemaItems
 */
export enum V1ProjectsProjectIdSelfHostedDistributionCredentialsPostParametersScopesSchemaItems {
  EnumSelfhostedproducts = 'self-hosted:products',
  EnumSelfhostedproductapi = 'self-hosted:product:api',
  EnumSelfhostedproductengine = 'self-hosted:product:engine',
  EnumSelfhostedproductlicenseproxy = 'self-hosted:product:license-proxy',
  EnumSelfhostedproductdgtools = 'self-hosted:product:dgtools',
  EnumSelfhostedproductbilling = 'self-hosted:product:billing',
  EnumSelfhostedproducthotpepper = 'self-hosted:product:hotpepper',
  EnumSelfhostedproductmetricsserver = 'self-hosted:product:metrics-server',
}

/**
 * Schema for V1ProjectsProjectIdSelfHostedDistributionCredentialsPostParametersScopesSchemaItems
 */
export const v1ProjectsProjectIdSelfHostedDistributionCredentialsPostParametersScopesSchemaItemsSchema: Schema<V1ProjectsProjectIdSelfHostedDistributionCredentialsPostParametersScopesSchemaItems> = stringEnum(
  V1ProjectsProjectIdSelfHostedDistributionCredentialsPostParametersScopesSchemaItems
);
