/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for V1ProjectsProjectIdUsageGetParametersDeployment
 */
export enum V1ProjectsProjectIdUsageGetParametersDeployment {
  Hosted = 'hosted',
  Beta = 'beta',
  Selfhosted = 'self-hosted',
}

/**
 * Schema for V1ProjectsProjectIdUsageGetParametersDeployment
 */
export const v1ProjectsProjectIdUsageGetParametersDeploymentSchema: Schema<V1ProjectsProjectIdUsageGetParametersDeployment> = stringEnum(
  V1ProjectsProjectIdUsageGetParametersDeployment
);
