/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for V1ProjectsProjectIdRequestsGetParametersEndpoint
 */
export enum V1ProjectsProjectIdRequestsGetParametersEndpoint {
  Listen = 'listen',
  Read = 'read',
  Speak = 'speak',
  Agent = 'agent',
}

/**
 * Schema for V1ProjectsProjectIdRequestsGetParametersEndpoint
 */
export const v1ProjectsProjectIdRequestsGetParametersEndpointSchema: Schema<V1ProjectsProjectIdRequestsGetParametersEndpoint> = stringEnum(
  V1ProjectsProjectIdRequestsGetParametersEndpoint
);
