/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for V1ProjectsProjectIdUsageBreakdownGetParametersEndpoint
 */
export enum V1ProjectsProjectIdUsageBreakdownGetParametersEndpoint {
  Listen = 'listen',
  Read = 'read',
  Speak = 'speak',
  Agent = 'agent',
}

/**
 * Schema for V1ProjectsProjectIdUsageBreakdownGetParametersEndpoint
 */
export const v1ProjectsProjectIdUsageBreakdownGetParametersEndpointSchema: Schema<V1ProjectsProjectIdUsageBreakdownGetParametersEndpoint> = stringEnum(
  V1ProjectsProjectIdUsageBreakdownGetParametersEndpoint
);
