/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for V1ProjectsProjectIdUsageBreakdownGetParametersMethod
 */
export enum V1ProjectsProjectIdUsageBreakdownGetParametersMethod {
  Sync = 'sync',
  Async = 'async',
  Streaming = 'streaming',
}

/**
 * Schema for V1ProjectsProjectIdUsageBreakdownGetParametersMethod
 */
export const v1ProjectsProjectIdUsageBreakdownGetParametersMethodSchema: Schema<V1ProjectsProjectIdUsageBreakdownGetParametersMethod> = stringEnum(
  V1ProjectsProjectIdUsageBreakdownGetParametersMethod
);
