/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for V1ProjectsProjectIdUsageGetParametersEndpoint
 */
export enum V1ProjectsProjectIdUsageGetParametersEndpoint {
  Listen = 'listen',
  Read = 'read',
  Speak = 'speak',
  Agent = 'agent',
}

/**
 * Schema for V1ProjectsProjectIdUsageGetParametersEndpoint
 */
export const v1ProjectsProjectIdUsageGetParametersEndpointSchema: Schema<V1ProjectsProjectIdUsageGetParametersEndpoint> = stringEnum(
  V1ProjectsProjectIdUsageGetParametersEndpoint
);
