/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for V1ProjectsProjectIdSelfHostedDistributionCredentialsPostParametersProvider
 */
export enum V1ProjectsProjectIdSelfHostedDistributionCredentialsPostParametersProvider {
  Quay = 'quay',
}

/**
 * Schema for V1ProjectsProjectIdSelfHostedDistributionCredentialsPostParametersProvider
 */
export const v1ProjectsProjectIdSelfHostedDistributionCredentialsPostParametersProviderSchema: Schema<V1ProjectsProjectIdSelfHostedDistributionCredentialsPostParametersProvider> = stringEnum(
  V1ProjectsProjectIdSelfHostedDistributionCredentialsPostParametersProvider
);
