/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for V1ProjectsProjectIdUsageBreakdownGetParametersGrouping
 */
export enum V1ProjectsProjectIdUsageBreakdownGetParametersGrouping {
  Accessor = 'accessor',
  Endpoint = 'endpoint',
  FeatureSet = 'feature_set',
  Models = 'models',
  Method = 'method',
  Tags = 'tags',
  Deployment = 'deployment',
}

/**
 * Schema for V1ProjectsProjectIdUsageBreakdownGetParametersGrouping
 */
export const v1ProjectsProjectIdUsageBreakdownGetParametersGroupingSchema: Schema<V1ProjectsProjectIdUsageBreakdownGetParametersGrouping> = stringEnum(
  V1ProjectsProjectIdUsageBreakdownGetParametersGrouping
);
