/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for V1ProjectsProjectIdUsageBreakdownGetParametersDeployment
 */
export enum V1ProjectsProjectIdUsageBreakdownGetParametersDeployment {
  Hosted = 'hosted',
  Beta = 'beta',
  Selfhosted = 'self-hosted',
}

/**
 * Schema for V1ProjectsProjectIdUsageBreakdownGetParametersDeployment
 */
export const v1ProjectsProjectIdUsageBreakdownGetParametersDeploymentSchema: Schema<V1ProjectsProjectIdUsageBreakdownGetParametersDeployment> = stringEnum(
  V1ProjectsProjectIdUsageBreakdownGetParametersDeployment
);
