/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for V1ProjectsProjectIdBillingBreakdownGetParametersDeployment
 */
export enum V1ProjectsProjectIdBillingBreakdownGetParametersDeployment {
  Hosted = 'hosted',
  Beta = 'beta',
  Selfhosted = 'self-hosted',
}

/**
 * Schema for V1ProjectsProjectIdBillingBreakdownGetParametersDeployment
 */
export const v1ProjectsProjectIdBillingBreakdownGetParametersDeploymentSchema: Schema<V1ProjectsProjectIdBillingBreakdownGetParametersDeployment> = stringEnum(
  V1ProjectsProjectIdBillingBreakdownGetParametersDeployment
);
