/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for V1ProjectsProjectIdKeysGetParametersStatus
 */
export enum V1ProjectsProjectIdKeysGetParametersStatus {
  Active = 'active',
  Expired = 'expired',
}

/**
 * Schema for V1ProjectsProjectIdKeysGetParametersStatus
 */
export const v1ProjectsProjectIdKeysGetParametersStatusSchema: Schema<V1ProjectsProjectIdKeysGetParametersStatus> = stringEnum(
  V1ProjectsProjectIdKeysGetParametersStatus
);
