/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for V1ProjectsProjectIdRequestsGetParametersStatus
 */
export enum V1ProjectsProjectIdRequestsGetParametersStatus {
  Succeeded = 'succeeded',
  Failed = 'failed',
}

/**
 * Schema for V1ProjectsProjectIdRequestsGetParametersStatus
 */
export const v1ProjectsProjectIdRequestsGetParametersStatusSchema: Schema<V1ProjectsProjectIdRequestsGetParametersStatus> = stringEnum(
  V1ProjectsProjectIdRequestsGetParametersStatus
);
