/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for V1ReadPostParametersCustomTopicMode
 */
export enum V1ReadPostParametersCustomTopicMode {
  Extended = 'extended',
  Strict = 'strict',
}

/**
 * Schema for V1ReadPostParametersCustomTopicMode
 */
export const v1ReadPostParametersCustomTopicModeSchema: Schema<V1ReadPostParametersCustomTopicMode> = stringEnum(
  V1ReadPostParametersCustomTopicMode
);
