/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for V1ReadPostParametersCustomIntentMode
 */
export enum V1ReadPostParametersCustomIntentMode {
  Extended = 'extended',
  Strict = 'strict',
}

/**
 * Schema for V1ReadPostParametersCustomIntentMode
 */
export const v1ReadPostParametersCustomIntentModeSchema: Schema<V1ReadPostParametersCustomIntentMode> = stringEnum(
  V1ReadPostParametersCustomIntentMode
);
