/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for V1ReadPostParametersCallbackMethod
 */
export enum V1ReadPostParametersCallbackMethod {
  Post = 'POST',
  Put = 'PUT',
}

/**
 * Schema for V1ReadPostParametersCallbackMethod
 */
export const v1ReadPostParametersCallbackMethodSchema: Schema<V1ReadPostParametersCallbackMethod> = stringEnum(
  V1ReadPostParametersCallbackMethod
);
