/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for V1ReadPostParametersSummarize0
 */
export enum V1ReadPostParametersSummarize0 {
  V2 = 'v2',
}

/**
 * Schema for V1ReadPostParametersSummarize0
 */
export const v1ReadPostParametersSummarize0Schema: Schema<V1ReadPostParametersSummarize0> = stringEnum(
  V1ReadPostParametersSummarize0
);
