/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for V1SpeakPostParametersContainer4
 */
export enum V1SpeakPostParametersContainer4 {
  Ogg = 'ogg',
}

/**
 * Schema for V1SpeakPostParametersContainer4
 */
export const v1SpeakPostParametersContainer4Schema: Schema<V1SpeakPostParametersContainer4> = stringEnum(
  V1SpeakPostParametersContainer4
);
