/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for V1SpeakPostParametersEncoding2
 */
export enum V1SpeakPostParametersEncoding2 {
  Mulaw = 'mulaw',
}

/**
 * Schema for V1SpeakPostParametersEncoding2
 */
export const v1SpeakPostParametersEncoding2Schema: Schema<V1SpeakPostParametersEncoding2> = stringEnum(
  V1SpeakPostParametersEncoding2
);
