/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for V1SpeakPostParametersSampleRate3
 */
export enum V1SpeakPostParametersSampleRate3 {
  Enum22050 = '22050',
}

/**
 * Schema for V1SpeakPostParametersSampleRate3
 */
export const v1SpeakPostParametersSampleRate3Schema: Schema<V1SpeakPostParametersSampleRate3> = stringEnum(
  V1SpeakPostParametersSampleRate3
);
