/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for V1SpeakPostParametersContainer3
 */
export enum V1SpeakPostParametersContainer3 {
  Wav = 'wav',
}

/**
 * Schema for V1SpeakPostParametersContainer3
 */
export const v1SpeakPostParametersContainer3Schema: Schema<V1SpeakPostParametersContainer3> = stringEnum(
  V1SpeakPostParametersContainer3
);
