/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for V1SpeakPostParametersContainer1
 */
export enum V1SpeakPostParametersContainer1 {
  Wav = 'wav',
}

/**
 * Schema for V1SpeakPostParametersContainer1
 */
export const v1SpeakPostParametersContainer1Schema: Schema<V1SpeakPostParametersContainer1> = stringEnum(
  V1SpeakPostParametersContainer1
);
