/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for V1SpeakPostParametersSampleRate2
 */
export enum V1SpeakPostParametersSampleRate2 {
  Enum8000 = '8000',
  Enum16000 = '16000',
}

/**
 * Schema for V1SpeakPostParametersSampleRate2
 */
export const v1SpeakPostParametersSampleRate2Schema: Schema<V1SpeakPostParametersSampleRate2> = stringEnum(
  V1SpeakPostParametersSampleRate2
);
