/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for V1SpeakPostParametersContainer0
 */
export enum V1SpeakPostParametersContainer0 {
  None = 'none',
}

/**
 * Schema for V1SpeakPostParametersContainer0
 */
export const v1SpeakPostParametersContainer0Schema: Schema<V1SpeakPostParametersContainer0> = stringEnum(
  V1SpeakPostParametersContainer0
);
