/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for V1SpeakPostParametersSampleRate4
 */
export enum V1SpeakPostParametersSampleRate4 {
  Enum48000 = '48000',
}

/**
 * Schema for V1SpeakPostParametersSampleRate4
 */
export const v1SpeakPostParametersSampleRate4Schema: Schema<V1SpeakPostParametersSampleRate4> = stringEnum(
  V1SpeakPostParametersSampleRate4
);
