/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for V1SpeakPostParametersBitRate0
 */
export enum V1SpeakPostParametersBitRate0 {
  Enum32000 = '32000',
  Enum48000 = '48000',
}

/**
 * Schema for V1SpeakPostParametersBitRate0
 */
export const v1SpeakPostParametersBitRate0Schema: Schema<V1SpeakPostParametersBitRate0> = stringEnum(
  V1SpeakPostParametersBitRate0
);
