/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for V1SpeakPostParametersEncoding4
 */
export enum V1SpeakPostParametersEncoding4 {
  Mp3 = 'mp3',
}

/**
 * Schema for V1SpeakPostParametersEncoding4
 */
export const v1SpeakPostParametersEncoding4Schema: Schema<V1SpeakPostParametersEncoding4> = stringEnum(
  V1SpeakPostParametersEncoding4
);
