/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for V1SpeakPostParametersEncoding1
 */
export enum V1SpeakPostParametersEncoding1 {
  Flac = 'flac',
}

/**
 * Schema for V1SpeakPostParametersEncoding1
 */
export const v1SpeakPostParametersEncoding1Schema: Schema<V1SpeakPostParametersEncoding1> = stringEnum(
  V1SpeakPostParametersEncoding1
);
