/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for V1SpeakPostParametersEncoding6
 */
export enum V1SpeakPostParametersEncoding6 {
  Aac = 'aac',
}

/**
 * Schema for V1SpeakPostParametersEncoding6
 */
export const v1SpeakPostParametersEncoding6Schema: Schema<V1SpeakPostParametersEncoding6> = stringEnum(
  V1SpeakPostParametersEncoding6
);
