/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for V1SpeakPostParametersEncoding3
 */
export enum V1SpeakPostParametersEncoding3 {
  Alaw = 'alaw',
}

/**
 * Schema for V1SpeakPostParametersEncoding3
 */
export const v1SpeakPostParametersEncoding3Schema: Schema<V1SpeakPostParametersEncoding3> = stringEnum(
  V1SpeakPostParametersEncoding3
);
