/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for V1SpeakPostParametersEncoding5
 */
export enum V1SpeakPostParametersEncoding5 {
  Opus = 'opus',
}

/**
 * Schema for V1SpeakPostParametersEncoding5
 */
export const v1SpeakPostParametersEncoding5Schema: Schema<V1SpeakPostParametersEncoding5> = stringEnum(
  V1SpeakPostParametersEncoding5
);
