/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for V1SpeakPostParametersCallbackMethod
 */
export enum V1SpeakPostParametersCallbackMethod {
  Post = 'POST',
  Put = 'PUT',
}

/**
 * Schema for V1SpeakPostParametersCallbackMethod
 */
export const v1SpeakPostParametersCallbackMethodSchema: Schema<V1SpeakPostParametersCallbackMethod> = stringEnum(
  V1SpeakPostParametersCallbackMethod
);
