/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for V1SpeakPostParametersEncoding0
 */
export enum V1SpeakPostParametersEncoding0 {
  Linear16 = 'linear16',
}

/**
 * Schema for V1SpeakPostParametersEncoding0
 */
export const v1SpeakPostParametersEncoding0Schema: Schema<V1SpeakPostParametersEncoding0> = stringEnum(
  V1SpeakPostParametersEncoding0
);
