/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for V1SpeakPostParametersSampleRate0
 */
export enum V1SpeakPostParametersSampleRate0 {
  Enum8000 = '8000',
  Enum16000 = '16000',
  Enum24000 = '24000',
  Enum32000 = '32000',
  Enum48000 = '48000',
}

/**
 * Schema for V1SpeakPostParametersSampleRate0
 */
export const v1SpeakPostParametersSampleRate0Schema: Schema<V1SpeakPostParametersSampleRate0> = stringEnum(
  V1SpeakPostParametersSampleRate0
);
