/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for V2SpeakPostParametersContainer4
 */
export enum V2SpeakPostParametersContainer4 {
  Ogg = 'ogg',
}

/**
 * Schema for V2SpeakPostParametersContainer4
 */
export const v2SpeakPostParametersContainer4Schema: Schema<V2SpeakPostParametersContainer4> = stringEnum(
  V2SpeakPostParametersContainer4
);
