/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for V2SpeakPostParametersContainer2
 */
export enum V2SpeakPostParametersContainer2 {
  Wav = 'wav',
}

/**
 * Schema for V2SpeakPostParametersContainer2
 */
export const v2SpeakPostParametersContainer2Schema: Schema<V2SpeakPostParametersContainer2> = stringEnum(
  V2SpeakPostParametersContainer2
);
