/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for V2SpeakPostParametersContainer3
 */
export enum V2SpeakPostParametersContainer3 {
  Wav = 'wav',
}

/**
 * Schema for V2SpeakPostParametersContainer3
 */
export const v2SpeakPostParametersContainer3Schema: Schema<V2SpeakPostParametersContainer3> = stringEnum(
  V2SpeakPostParametersContainer3
);
