/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for V2SpeakPostParametersEncoding2
 */
export enum V2SpeakPostParametersEncoding2 {
  Mulaw = 'mulaw',
}

/**
 * Schema for V2SpeakPostParametersEncoding2
 */
export const v2SpeakPostParametersEncoding2Schema: Schema<V2SpeakPostParametersEncoding2> = stringEnum(
  V2SpeakPostParametersEncoding2
);
