/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for V2SpeakPostParametersSampleRate0
 */
export enum V2SpeakPostParametersSampleRate0 {
  Enum8000 = '8000',
  Enum16000 = '16000',
  Enum24000 = '24000',
  Enum32000 = '32000',
  Enum44100 = '44100',
  Enum48000 = '48000',
}

/**
 * Schema for V2SpeakPostParametersSampleRate0
 */
export const v2SpeakPostParametersSampleRate0Schema: Schema<V2SpeakPostParametersSampleRate0> = stringEnum(
  V2SpeakPostParametersSampleRate0
);
