/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for V2SpeakPostParametersEncoding6
 */
export enum V2SpeakPostParametersEncoding6 {
  Aac = 'aac',
}

/**
 * Schema for V2SpeakPostParametersEncoding6
 */
export const v2SpeakPostParametersEncoding6Schema: Schema<V2SpeakPostParametersEncoding6> = stringEnum(
  V2SpeakPostParametersEncoding6
);
