/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for V2SpeakPostParametersContainer0
 */
export enum V2SpeakPostParametersContainer0 {
  None = 'none',
}

/**
 * Schema for V2SpeakPostParametersContainer0
 */
export const v2SpeakPostParametersContainer0Schema: Schema<V2SpeakPostParametersContainer0> = stringEnum(
  V2SpeakPostParametersContainer0
);
