/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for V2SpeakPostParametersEncoding3
 */
export enum V2SpeakPostParametersEncoding3 {
  Alaw = 'alaw',
}

/**
 * Schema for V2SpeakPostParametersEncoding3
 */
export const v2SpeakPostParametersEncoding3Schema: Schema<V2SpeakPostParametersEncoding3> = stringEnum(
  V2SpeakPostParametersEncoding3
);
