/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for V2SpeakPostParametersEncoding1
 */
export enum V2SpeakPostParametersEncoding1 {
  Flac = 'flac',
}

/**
 * Schema for V2SpeakPostParametersEncoding1
 */
export const v2SpeakPostParametersEncoding1Schema: Schema<V2SpeakPostParametersEncoding1> = stringEnum(
  V2SpeakPostParametersEncoding1
);
