/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for V2SpeakPostParametersEncoding4
 */
export enum V2SpeakPostParametersEncoding4 {
  Mp3 = 'mp3',
}

/**
 * Schema for V2SpeakPostParametersEncoding4
 */
export const v2SpeakPostParametersEncoding4Schema: Schema<V2SpeakPostParametersEncoding4> = stringEnum(
  V2SpeakPostParametersEncoding4
);
