/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for V2SpeakPostParametersCallbackMethod
 */
export enum V2SpeakPostParametersCallbackMethod {
  Post = 'POST',
  Put = 'PUT',
}

/**
 * Schema for V2SpeakPostParametersCallbackMethod
 */
export const v2SpeakPostParametersCallbackMethodSchema: Schema<V2SpeakPostParametersCallbackMethod> = stringEnum(
  V2SpeakPostParametersCallbackMethod
);
