/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for V2SpeakPostParametersSampleRate3
 */
export enum V2SpeakPostParametersSampleRate3 {
  Enum8000 = '8000',
  Enum16000 = '16000',
  Enum22050 = '22050',
  Enum32000 = '32000',
  Enum48000 = '48000',
}

/**
 * Schema for V2SpeakPostParametersSampleRate3
 */
export const v2SpeakPostParametersSampleRate3Schema: Schema<V2SpeakPostParametersSampleRate3> = stringEnum(
  V2SpeakPostParametersSampleRate3
);
