/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for V2SpeakPostParametersSampleRate2
 */
export enum V2SpeakPostParametersSampleRate2 {
  Enum8000 = '8000',
  Enum16000 = '16000',
}

/**
 * Schema for V2SpeakPostParametersSampleRate2
 */
export const v2SpeakPostParametersSampleRate2Schema: Schema<V2SpeakPostParametersSampleRate2> = stringEnum(
  V2SpeakPostParametersSampleRate2
);
