/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for V2SpeakPostParametersBitRate0
 */
export enum V2SpeakPostParametersBitRate0 {
  Enum8000 = '8000',
  Enum16000 = '16000',
  Enum24000 = '24000',
  Enum32000 = '32000',
  Enum40000 = '40000',
  Enum48000 = '48000',
}

/**
 * Schema for V2SpeakPostParametersBitRate0
 */
export const v2SpeakPostParametersBitRate0Schema: Schema<V2SpeakPostParametersBitRate0> = stringEnum(
  V2SpeakPostParametersBitRate0
);
