/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for V2SpeakPostParametersContainer1
 */
export enum V2SpeakPostParametersContainer1 {
  Wav = 'wav',
}

/**
 * Schema for V2SpeakPostParametersContainer1
 */
export const v2SpeakPostParametersContainer1Schema: Schema<V2SpeakPostParametersContainer1> = stringEnum(
  V2SpeakPostParametersContainer1
);
