/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for V2SpeakPostParametersEncoding5
 */
export enum V2SpeakPostParametersEncoding5 {
  Opus = 'opus',
}

/**
 * Schema for V2SpeakPostParametersEncoding5
 */
export const v2SpeakPostParametersEncoding5Schema: Schema<V2SpeakPostParametersEncoding5> = stringEnum(
  V2SpeakPostParametersEncoding5
);
