/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for V2SpeakPostParametersSampleRate1
 */
export enum V2SpeakPostParametersSampleRate1 {
  Enum8000 = '8000',
  Enum16000 = '16000',
}

/**
 * Schema for V2SpeakPostParametersSampleRate1
 */
export const v2SpeakPostParametersSampleRate1Schema: Schema<V2SpeakPostParametersSampleRate1> = stringEnum(
  V2SpeakPostParametersSampleRate1
);
