/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for V2SpeakPostParametersEncoding0
 */
export enum V2SpeakPostParametersEncoding0 {
  Linear16 = 'linear16',
}

/**
 * Schema for V2SpeakPostParametersEncoding0
 */
export const v2SpeakPostParametersEncoding0Schema: Schema<V2SpeakPostParametersEncoding0> = stringEnum(
  V2SpeakPostParametersEncoding0
);
