/**
 * REST APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for V2SpeakPostParametersPriority
 */
export enum V2SpeakPostParametersPriority {
  Low = 'low',
}

/**
 * Schema for V2SpeakPostParametersPriority
 */
export const v2SpeakPostParametersPrioritySchema: Schema<V2SpeakPostParametersPriority> = stringEnum(
  V2SpeakPostParametersPriority
);
