/**
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  accessTokenAuthenticationProvider,
  compositeAuthenticationProvider,
  customHeaderAuthenticationProvider,
} from './authentication.js';
import { Configuration } from './configuration.js';

export function createAuthProviderFromConfig(config: Partial<Configuration>) {
  const authConfig = {
    apiKeyAuth:
      config.apiKeyAuthCredentials &&
      customHeaderAuthenticationProvider(config.apiKeyAuthCredentials),
    jwtAuth:
      config.jwtAuthCredentials &&
      accessTokenAuthenticationProvider(config.jwtAuthCredentials),
  };

  return compositeAuthenticationProvider<
    keyof typeof authConfig,
    typeof authConfig
  >(authConfig);
}
